# -*- coding: utf-8 -*-
C3=dict(
 TITLE=('Fix the defects before they get ported','Corrigir os defeitos antes de serem portados'),
 GOAL=('Clear the known bugs in the code being moved, so the migration <b>does not copy them into a second place</b> where they must be fixed twice.',
       'Limpar os bugs conhecidos no código que vai ser movido, para a migração <b>não copiá-los para um segundo lugar</b> onde terão de ser corrigidos duas vezes.'),
 GLANCE=[
  ('crit',('Severity','Severidade'),('Housekeeping','Higiene'),
   ('None of these is an outage. All of them get more expensive after the code is duplicated. Source: analysis §11.5.',
    'Nenhum deles é uma queda. Todos ficam mais caros depois que o código for duplicado. Fonte: análise §11.5.')),
  ('dep',('Depends on','Depende de'),('Nothing','Nada'),
   ('<strong>Do it early.</strong> B2 is about to extract one of these modules into a second repository.',
    '<strong>Faça cedo.</strong> A B2 está prestes a extrair um destes módulos para um segundo repositório.')),
  ('wave',('Wave','Onda'),('Wave 0','Onda 0'),
   ('Runs in parallel with everything else in wave 0 — no contention with S1, S4, S5 or S7.',
    'Roda em paralelo com todo o resto da onda 0 — sem disputa com S1, S4, S5 ou S7.')),
  ('ship',('Shape','Formato'),('Six defects','Seis defeitos'),
   ('Two verified in this repository, four reported by the step documentation and needing proof first.',
    'Dois verificados neste repositório, quatro reportados pela documentação de passos e que precisam de prova antes.')),
 ],
 LEDE=('<p>Every defect in this list lives in code that another task is about to <strong>move, extract or duplicate</strong>. Fixed now, each is a one-line change in one place. Fixed later, each is the same change in two repositories that have already started to drift.</p>'
       '<p>The list is deliberately split: <strong>two are verified here</strong>, and <strong>four are reported by the step documentation and must be proven before anything is deleted</strong>. Code absence in one repo is not proof of no traffic.</p>',
       '<p>Todo defeito desta lista vive em código que outra task está prestes a <strong>mover, extrair ou duplicar</strong>. Corrigido agora, cada um é uma mudança de uma linha em um lugar. Corrigido depois, cada um é a mesma mudança em dois repositórios que já começaram a divergir.</p>'
       '<p>A lista é dividida de propósito: <strong>dois estão verificados aqui</strong>, e <strong>quatro são reportados pela documentação de passos e precisam de prova antes de qualquer remoção</strong>. Ausência de código num repo não é prova de ausência de tráfego.</p>'),
 TABLE=dict(head=[('#','#'),('Defect','Defeito'),('Status','Status'),('Why it must go first','Por que vai primeiro')],
  rows=[
   [{'t':'1','mono':True},('<code>previewResponses</code> trim uses strict equality — <code>responses.length === 10</code> at six sites','O corte de <code>previewResponses</code> usa igualdade estrita — <code>responses.length === 10</code> em seis lugares'),
    {'t':('Verified','Verificado'),'pill':'ok'},
    ('Any array that reaches eleven by another path <strong>never trims again</strong> and grows without bound inside <code>flows_nodes.data</code> — the known front-end performance offender','Qualquer array que chegue a onze por outro caminho <strong>nunca mais é cortado</strong> e cresce sem limite dentro de <code>flows_nodes.data</code> — o conhecido vilão de performance no front')],
   [{'t':'2','mono':True},('<code>endNode</code> called twice on the same handle','<code>endNode</code> chamado duas vezes no mesmo handle'),
    {'t':('Verified','Verificado'),'pill':'ok'},
    ('Harmless today, but it will confuse anyone porting the collector — and <strong>E1 is about to</strong>','Inofensivo hoje, mas vai confundir quem portar o coletor — e <strong>a E1 está prestes a fazer isso</strong>')],
   [{'t':'3','mono':True},('<code>processFlowWithSubstitution</code> may be dead code','<code>processFlowWithSubstitution</code> pode ser código morto'),
    {'t':('Needs proof','Precisa de prova'),'pill':'weak'},
    ('<strong>B2 is about to extract this module.</strong> Extracting dead code and then maintaining it in two repos is the specific waste to avoid','<strong>A B2 vai extrair este módulo.</strong> Extrair código morto e depois mantê-lo em dois repos é exatamente o desperdício a evitar')],
   [{'t':'4','mono':True},('<code>GOOGLE_LOGIN_CLIENT_SECRECT</code> — a typo in an env var name','<code>GOOGLE_LOGIN_CLIENT_SECRECT</code> — um erro de digitação no nome de uma env var'),
    {'t':('Coordinated','Coordenada'),'pill':'weak'},
    ('Renaming requires changing dev, CI and production <strong>together</strong> — run <code>env-vars-sync</code>, not find-and-replace','Renomear exige mudar dev, CI e produção <strong>juntos</strong> — rode o <code>env-vars-sync</code>, não um localizar-e-substituir')],
   [{'t':'5','mono':True},('<code>api-caller-polling.ts</code> has no importers','<code>api-caller-polling.ts</code> não tem quem o importe'),
    {'t':('Needs proof','Precisa de prova'),'pill':'weak'},
    ('The polling it implements already lives in the worker as <code>execute-polling</code>. Same proof burden as #3 — all repos plus <code>origin/production</code>','O polling que ele implementa já vive no worker como <code>execute-polling</code>. Mesmo ônus de prova do #3 — todos os repos mais <code>origin/production</code>')],
   [{'t':'6','mono':True},('The friendly error timestamp records “now”, not when the error occurred','O timestamp do erro amigável grava “agora”, não quando o erro ocorreu'),
    {'t':('Verified','Verificado'),'pill':'ok'},
    ('Every downstream reader of that timestamp is wrong by however long the error took to surface','Todo leitor a jusante desse timestamp erra pelo tempo que o erro levou para aparecer')],
  ]),
 PARTS=[
  {'n':'1','title':('The proof burden on the deletions','O ônus de prova nas remoções'),
   'loc':'node-reference-substitution.service.ts · api-caller-polling.ts',
   'purpose':('Two of these defects are deletions, and a deletion made on a bad grep is the most expensive mistake on this list.',
              'Dois destes defeitos são remoções, e uma remoção feita com um grep ruim é o erro mais caro desta lista.'),
   'body':('<p>Items 3 and 5 both claim code is unreachable. That claim needs <strong>owner-anchored greps across <code>back</code>, <code>front</code>, <code>worker</code>, <code>mcp-server</code> and <code>origin/production</code></strong> — not just the local checkout.</p>'
           '<p>Dev can lag production. A symbol that has no importer on this branch may still be serving traffic from the deployed one.</p>',
           '<p>Os itens 3 e 5 afirmam que um código é inalcançável. Essa afirmação exige <strong>greps ancorados no dono, em <code>back</code>, <code>front</code>, <code>worker</code>, <code>mcp-server</code> e <code>origin/production</code></strong> — não só no checkout local.</p>'
           '<p>Dev pode estar atrás de produção. Um símbolo sem quem o importe neste branch pode ainda estar servindo tráfego a partir do que está publicado.</p>'),
   'ba':(('Two modules that look dead. One of them is about to be extracted into a second repository by B2, where it would then be maintained twice.',
          'Dois módulos que parecem mortos. Um deles está prestes a ser extraído para um segundo repositório pela B2, onde passaria a ser mantido duas vezes.'),
         ('Each is either deleted with the proof recorded, or kept with the reason recorded. Either outcome is fine; an unproven deletion is not.',
          'Cada um é removido com a prova registrada, ou mantido com a razão registrada. Qualquer um dos dois desfechos serve; uma remoção sem prova não.')),
   'callouts':[('mig',('Out of scope','Fora de escopo'),
     ('<p>Anything that changes execution semantics. This task is for defects whose fix is <strong>behaviour-preserving in the normal case</strong>; a fix that changes what a run produces belongs to the task that owns that behaviour.</p>',
      '<p>Qualquer coisa que mude semântica de execução. Esta task é para defeitos cuja correção é <strong>preservadora de comportamento no caso normal</strong>; uma correção que muda o que um run produz pertence à task dona daquele comportamento.</p>'))]},
 ],
 VERIF=[
  (True,('Negative control, per fix','Controle negativo, por correção'),
   ('<strong>Each of these needs a test that fails on the current code.</strong> For the trim: seed a node with <strong>eleven</strong> stored responses, run it, and assert the array does not grow — that test fails today. For the duplicate <code>endNode</code>: assert one end event per node. A fix without a test that failed first is indistinguishable from a fix that changed nothing.',
    '<strong>Cada um destes precisa de um teste que falhe no código atual.</strong> Para o corte: semeie um node com <strong>onze</strong> respostas guardadas, rode, e afirme que o array não cresce — esse teste falha hoje. Para o <code>endNode</code> duplicado: afirme um evento de fim por node. Uma correção sem um teste que falhou antes é indistinguível de uma correção que não mudou nada.')),
  (True,('Measure before the backfill','Medir antes do backfill'),
   ('Query the real data for <code>previewResponses</code> arrays longer than ten <strong>before</strong> deciding whether a backfill is needed, and report the count. <strong>If none exist, say so</strong> — an unnecessary data migration is its own risk.',
    'Consulte o dado real por arrays <code>previewResponses</code> com mais de dez itens <strong>antes</strong> de decidir se um backfill é necessário, e reporte a contagem. <strong>Se não houver nenhum, diga isso</strong> — uma migração de dados desnecessária é um risco por si só.')),
  (False,('Prove the dead code across every repo','Provar o código morto em todos os repos'),
   ('Owner-anchored greps across <code>back</code>, <code>front</code>, <code>worker</code>, <code>mcp-server</code> <strong>and <code>origin/production</code></strong>, not just the local checkout. Record the proof in the PR.',
    'Greps ancorados no dono em <code>back</code>, <code>front</code>, <code>worker</code>, <code>mcp-server</code> <strong>e <code>origin/production</code></strong>, não só no checkout local. Registre a prova no PR.')),
 ],
 DONE=('Each defect has <strong>a test that failed before the fix</strong>, the trim&#x27;s data impact is <strong>measured rather than assumed</strong>, and the dead-code claim is <strong>proven across every repo</strong> before anything is deleted.',
       'Cada defeito tem <strong>um teste que falhou antes da correção</strong>, o impacto de dados do corte é <strong>medido em vez de suposto</strong>, e a afirmação de código morto é <strong>provada em todos os repos</strong> antes de qualquer remoção.'),
 FILES=[('back/src/app-api/flux/flux.service.ts (responses.length === 10 ×6 · the two consecutive endNode calls on genericRunLogNode · the friendly-error timestamp)',False),
        ('back/src/app-api/node-reference-substitution/node-reference-substitution.service.ts (processFlowWithSubstitution)',False),
        ('back/src/app-api/flux/api-caller-polling.ts',False),
        ('back/.env.example and every environment carrying the Google client secret',False)],
)

C3_DEC={
 'k':'decision','id':'C3-a','status':'open','open':True,
 'q':('Does the <code>previewResponses</code> fix need a data backfill, or only a forward fix?',
      'A correção do <code>previewResponses</code> precisa de backfill, ou só de correção daqui para frente?'),
 'intro':('Changing <code>=== 10</code> to <code>&gt;= 10</code> stops <em>new</em> arrays from escaping the cap. It does nothing for arrays that <strong>already escaped</strong> and are sitting oversized in <code>flows_nodes.data</code> today. '
          'Whether any exist is a question about the stored data, not about the code — and the spec is explicit that it must be <strong>measured before it is decided</strong>.',
          'Mudar <code>=== 10</code> para <code>&gt;= 10</code> impede que arrays <em>novos</em> escapem do teto. Não faz nada pelos arrays que <strong>já escaparam</strong> e estão hoje grandes demais dentro de <code>flows_nodes.data</code>. '
          'Se algum existe é uma pergunta sobre o dado guardado, não sobre o código — e a spec é explícita que isso precisa ser <strong>medido antes de ser decidido</strong>.'),
 'opts':[
  {'ltr':'A','pick':True,'name':('Measure first, then decide','Medir primeiro, decidir depois'),
   'tag':('recommended','recomendada'),
   'how':('Ship the <code>&gt;=</code> fix, and separately count how many stored <code>previewResponses</code> arrays are longer than ten. Let that number choose between B and C.',
          'Entregar a correção do <code>&gt;=</code>, e à parte contar quantos arrays <code>previewResponses</code> guardados têm mais de dez itens. Deixar esse número escolher entre B e C.'),
   'pros':[('The forward fix ships immediately and cannot regress anything','A correção daqui para frente sobe imediatamente e não pode regredir nada'),
           ('<strong>If the count is zero, there is no migration to run</strong> — and an unnecessary data migration is its own risk','<strong>Se a contagem for zero, não há migração a rodar</strong> — e uma migração de dados desnecessária é um risco por si só'),
           ('The count is a one-line query against a JSONB column','A contagem é uma consulta de uma linha contra uma coluna JSONB')],
   'cons':[('Two steps instead of one','Dois passos em vez de um')],
   'cost':[('lo',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('lo',('Ours: <b>one query</b>','Nosso: <b>uma consulta</b>'))]},
  {'ltr':'B','name':('Forward fix only','Só a correção para frente'),
   'how':('Change the comparison and stop there. Oversized arrays stay oversized, but stop growing, because the next append hits <code>&gt;=</code>.',
          'Mudar a comparação e parar por aí. Arrays grandes demais continuam grandes, mas param de crescer, porque o próximo append bate no <code>&gt;=</code>.'),
   'pros':[('No data migration at all — the least risky thing you can do to a JSONB column','Nenhuma migração de dados — a coisa menos arriscada que se pode fazer com uma coluna JSONB'),
           ('Growth stops immediately for every affected row','O crescimento para imediatamente para toda linha afetada')],
   'cons':[('The front-end performance problem persists for whoever is already affected','O problema de performance no front persiste para quem já foi afetado'),
           ('Those rows never shrink — the trim only ever removes on append','Essas linhas nunca encolhem — o corte só remove no append')],
   'cost':[('',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('lo',('Ours: <b>one character</b>','Nosso: <b>um caractere</b>'))]},
  {'ltr':'C','name':('Fix plus a backfill','Correção mais backfill'),
   'how':('Change the comparison and run a migration that trims every stored array back to ten.',
          'Mudar a comparação e rodar uma migração que corte todo array guardado de volta para dez.'),
   'pros':[('Everyone affected gets the performance back, not just future runs','Todo afetado recupera a performance, não só os runs futuros')],
   'cons':[('A write migration over a JSONB column on production data — the riskiest option here','Uma migração de escrita sobre uma coluna JSONB em dado de produção — a opção mais arriscada'),
           ('Deletes stored customer output. If ten was never the right cap, this is irreversible','Apaga saída guardada do cliente. Se dez nunca foi o teto certo, isto é irreversível'),
           ('<strong>Pointless if the count turns out to be zero</strong>','<strong>Inútil se a contagem for zero</strong>')],
   'cost':[('',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('hi',('Ours: <b>a production data migration</b>','Nosso: <b>uma migração de dados em produção</b>'))]},
 ],
 'rec':('<p><strong>A, and let the number decide.</strong> The measurement is cheap, and it is the difference between a justified migration and a gratuitous one.</p>'
        '<p>Note that C also has a product question hiding inside it: trimming stored arrays <strong>deletes customer output</strong>. If any row is affected, that is worth one sentence of confirmation before the migration runs — not a silent cleanup.</p>',
        '<p><strong>A, e deixe o número decidir.</strong> A medição é barata, e é a diferença entre uma migração justificada e uma gratuita.</p>'
        '<p>Note que C esconde uma questão de produto: cortar arrays guardados <strong>apaga saída do cliente</strong>. Se alguma linha for afetada, isso merece uma frase de confirmação antes de a migração rodar — não uma limpeza silenciosa.</p>'),
 'who':[('Engineering, after the count','Engenharia, depois da contagem'),('Product if any row is affected','Produto se alguma linha for afetada')],
}
