# -*- coding: utf-8 -*-
# A5 — Migrate the image family.  Source: TASK-A5-IMAGE-FAMILY.md, analysis §3.2/§4.1/§4.3, DELIVERY-PLAN wave 3.

TASK = {
 'code':'A5','vnum':'3',
 'title':('Migrate the image family','Migrar a família de imagem'),
 'goal':('Migrate <b><code>imageGenerator</code></b> and <b><code>imageReaderNode</code></b> over <b>one shared provider layer</b>, so their overlapping provider paths are written once instead of twice.',
         'Migrar o <b><code>imageGenerator</code></b> e o <b><code>imageReaderNode</code></b> sobre <b>uma camada de provedor compartilhada</b>, para que os caminhos de provedor sobrepostos sejam escritos uma vez, e não duas.'),
 'glance':[
  ('crit',('Cost','Custo'),('Breadth, not architecture','Amplitude, não arquitetura'),
   ('<code>imageGenerator</code> is architecturally identical to <code>commandTextNode</code>, in the worker in production the longest. Six provider paths is the real bill.',
    'O <code>imageGenerator</code> é arquiteturalmente idêntico ao <code>commandTextNode</code>, o mais antigo em produção no worker. Seis caminhos de provedor são a conta de verdade.')),
  ('dep',('Depends on','Depende de'),('A1 · A4 · D3','A1 · A4 · D3'),
   ('A4 must have validated the template first. The <code>imageReaderNode</code> half is <strong>blocked on D3</strong>, decided in A6.',
    'A A4 precisa ter validado o template antes. A metade do <code>imageReaderNode</code> está <strong>bloqueada pela D3</strong>, decidida na A6.')),
  ('wave',('Wave','Onda'),('Wave 3','Onda 3'),
   ('Second migration of the wave — the first one with a provider surface and real billing to keep identical.',
    'Segunda migração da onda — a primeira com superfície de provedor e cobrança real a manter idêntica.')),
  ('ship',('Shape','Formato'),('One layer, two nodes','Uma camada, dois nodes'),
   ('They are one task because migrating them apart means writing the provider layer twice and letting the copies drift.',
    'São uma task só porque migrá-los separados significa escrever a camada de provedor duas vezes e deixar as cópias divergirem.')),
 ],
 'lede':(
  '<p><code>imageGenerator</code> resolves a prompt from up to seven fields, interpolates placeholders against the resolved run schema, then dispatches to <strong>one of six provider paths</strong> — <code>openAiService.createImageWithBilling</code>, <code>geminiService.generateImage</code>, <code>replicateService.kandinsky</code> and <code>imageService.{imageCore,sd,textToImage}</code>. Every contract it needs already exists.</p>'
  '<p><code>imageReaderNode</code> overlaps heavily — OpenAI, Anthropic, Replicate, Ideogram, plus file and upload — but it is a different kind of work: it is <strong>one of the nine front-driven types</strong>, so this task <em>adds</em> its execution rather than moving it, and it waits on <strong>D3</strong>.</p>',
  '<p>O <code>imageGenerator</code> resolve um prompt a partir de até sete campos, interpola placeholders contra o schema resolvido do run e então despacha para <strong>um de seis caminhos de provedor</strong> — <code>openAiService.createImageWithBilling</code>, <code>geminiService.generateImage</code>, <code>replicateService.kandinsky</code> e <code>imageService.{imageCore,sd,textToImage}</code>. Todo contrato de que precisa já existe.</p>'
  '<p>O <code>imageReaderNode</code> se sobrepõe bastante — OpenAI, Anthropic, Replicate, Ideogram, mais arquivo e upload — mas é um trabalho de outra natureza: é <strong>um dos nove tipos só-front</strong>, então esta task <em>acrescenta</em> a execução dele em vez de movê-la, e ele espera pela <strong>D3</strong>.</p>'),
 'blocks':[
  {'k':'label','n':'1','t':('Two halves that are not the same kind of work','Duas metades que não são o mesmo tipo de trabalho')},
  {'k':'table',
   'head':[('The two halves','As duas metades'),('<code>imageGenerator</code>','<code>imageGenerator</code>'),('<code>imageReaderNode</code>','<code>imageReaderNode</code>')],
   'rows':[
    [{'t':('Where it runs today','Onde roda hoje')},
     {'t':('Inline in the engine','Inline no engine')},
     {'t':('Only in the browser','Só no navegador'),'pill':'no'}],
    [{'t':('Entry points in the code','Pontos de entrada no código')},
     {'t':('Handler <code>:6972</code>, dispatch <code>:1145</code>','Handler <code>:6972</code>, dispatch <code>:1145</code>')},
     {'t':('<code>ImageReader.tsx</code> calls the providers directly','O <code>ImageReader.tsx</code> chama os provedores direto')}],
    [{'t':('What this task does to it','O que esta task faz com ele')},
     {'t':('Moves execution','Move a execução'),'pill':'ok'},
     {'t':('<b>Adds</b> execution (§4.3)','<b>Acrescenta</b> execução (§4.3)'),'pill':'weak'}],
    [{'t':('Provider surface','Superfície de provedor')},
     ('Six paths: <code>openAiService.createImageWithBilling</code>, <code>geminiService.generateImage</code>, <code>replicateService.kandinsky</code>, <code>imageService.{imageCore,sd,textToImage}</code>',
      'Seis caminhos: <code>openAiService.createImageWithBilling</code>, <code>geminiService.generateImage</code>, <code>replicateService.kandinsky</code>, <code>imageService.{imageCore,sd,textToImage}</code>'),
     ('OpenAI, Anthropic, Replicate, Ideogram, plus file and upload','OpenAI, Anthropic, Replicate, Ideogram, mais arquivo e upload')],
    [{'t':('Contracts it needs','Contratos de que precisa')},
     ('All three already exist: <code>/worker/charge-tokens</code>, <code>/worker/validate-model-access</code>, <code>/worker/generate-file</code>',
      'Os três já existem: <code>/worker/charge-tokens</code>, <code>/worker/validate-model-access</code>, <code>/worker/generate-file</code>'),
     ('The same three, <strong>plus an engine dispatch that does not exist today</strong>',
      'Os mesmos três, <strong>mais um dispatch do engine que hoje não existe</strong>')],
    [{'t':('Blocked on','Bloqueado por')},
     {'t':('Nothing beyond A1 and A4','Nada além da A1 e da A4'),'pill':'ok'},
     {'t':('D3, answered in A6','D3, respondida na A6'),'pill':'weak'}],
   ]},
  {'k':'prose','t':(
    'The spec leaves <strong>no open call of its own</strong> here: providers, models, prompt fields and the billing formula are explicitly out of scope, and provider selection is a behaviour port with no redesign. '
    'The one decision that touches this task is <strong>D3</strong>, and it belongs to <code>A6</code> — the <code>imageReaderNode</code> half simply waits for it.',
    'A spec <strong>não deixa nenhuma decisão própria em aberto</strong> aqui: provedores, modelos, campos de prompt e a fórmula de cobrança estão explicitamente fora de escopo, e a seleção de provedor é porte de comportamento sem redesenho. '
    'A única decisão que toca esta task é a <strong>D3</strong>, e ela pertence à <code>A6</code> — a metade do <code>imageReaderNode</code> apenas espera por ela.')},
  {'k':'label','n':'2','t':('What the task does, in four parts','O que a task faz, em quatro partes')},
  {'k':'part','n':'1',
   'title':('The shared provider layer','A camada de provedor compartilhada'),
   'loc':'worker/src/modules/ai-provider/image/',
   'purpose':('Write each provider path once, so the two nodes cannot drift apart later.',
              'Escrever cada caminho de provedor uma vez, para que os dois nodes não possam divergir depois.'),
   'body':('<p>One entry per path, ported from the back&#x27;s services. <strong>Behaviour port only — no redesign of provider selection.</strong> The layer is the reason the two nodes are one task: migrating them separately means writing this twice and letting the two copies diverge, which is the failure mode this epic keeps finding in the dispatch lists.</p>',
           '<p>Uma entrada por caminho, portada dos serviços do back. <strong>Só porte de comportamento — sem redesenhar a seleção de provedor.</strong> A camada é a razão de os dois nodes serem uma task só: migrá-los separados significa escrever isto duas vezes e deixar as duas cópias divergirem, que é o modo de falha que este épico não para de encontrar nas listas de dispatch.</p>'),
   'ba':(('Six provider paths live inside the engine handler, and a second node reaching the same providers would copy them.',
          'Seis caminhos de provedor vivem dentro do handler do engine, e um segundo node que alcance os mesmos provedores os copiaria.'),
         ('One layer in the worker, consumed by both nodes, with one place to fix when a provider changes.',
          'Uma camada no worker, consumida pelos dois nodes, com um único lugar para corrigir quando um provedor mudar.'))},
  {'k':'part','n':'2',
   'title':('<code>imageGenerator</code>: prove, flip, delete the twin','<code>imageGenerator</code>: provar, virar, apagar o gêmeo'),
   'loc':'flux.service.ts:1145, 6972',
   'purpose':('Move an execution that already works, without changing a single thing a customer can observe.',
              'Mover uma execução que já funciona, sem mudar nada que um cliente possa observar.'),
   'body':('<p>The module, the registry entry behind the flag, the proof, the flip, then the deletion of the handler at <code>:6972</code> and the dispatch at <code>:1145</code>.</p>'
           '<p><strong>Prompt resolution is the detail that carries the behaviour.</strong> Seven prompt fields — <code>prompt</code>, <code>subject</code>, <code>environment</code>, <code>tone</code>, <code>view</code>, <code>style</code>, <code>negativePrompt</code> — with placeholder interpolation against the resolved run schema. That is the same pattern every migrated node with variable inputs already uses; it is established, not new.</p>',
           '<p>O módulo, a entrada no registro atrás da flag, a prova, a virada, e então a deleção do handler em <code>:6972</code> e do dispatch em <code>:1145</code>.</p>'
           '<p><strong>A resolução de prompt é o detalhe que carrega o comportamento.</strong> Sete campos de prompt — <code>prompt</code>, <code>subject</code>, <code>environment</code>, <code>tone</code>, <code>view</code>, <code>style</code>, <code>negativePrompt</code> — com interpolação de placeholders contra o schema resolvido do run. É o mesmo padrão que todo node migrado com entradas variáveis já usa; é estabelecido, não novo.</p>'),
   'ba':(('One handler chooses among six providers inside the engine process, and its billing is written from there.',
          'Um handler escolhe entre seis provedores dentro do processo do engine, e a cobrança dele é escrita de lá.'),
         ('An activity chooses among the same six through the shared layer, and bills through <code>/worker/charge-tokens</code> — <strong>with the rows proven to match</strong>.',
          'Uma activity escolhe entre os mesmos seis pela camada compartilhada, e cobra via <code>/worker/charge-tokens</code> — <strong>com as linhas provadas iguais</strong>.'))},
  {'k':'part','n':'3',
   'title':('<code>imageReaderNode</code>: the half that adds execution','<code>imageReaderNode</code>: a metade que acrescenta execução'),
   'loc':('front/src/components/nodes/ImageReader.tsx (Run path)', 'front/src/components/nodes/ImageReader.tsx (caminho do Run)'),
   'purpose':('Give the ninth front-driven type the dispatch the other eight get in A6 — over the layer built in Part 1.',
              'Dar ao nono tipo só-front o dispatch que os outros oito recebem na A6 — sobre a camada da Parte 1.'),
   'body':('<p>This module sits on the same provider layer, but the work around it is different in kind: <code>imageReaderNode</code> is one of the nine front-driven types, so <strong>nothing executes it server-side today</strong>. It needs an engine dispatch that does not exist, and the front&#x27;s Run button has to stop calling the providers directly once it does.</p>'
           '<p>That is a behaviour change for existing flows, not a refactor — which is why this half waits for <strong>D3</strong>.</p>',
           '<p>Este módulo fica sobre a mesma camada de provedor, mas o trabalho ao redor é de outra natureza: o <code>imageReaderNode</code> é um dos nove tipos só-front, então <strong>nada o executa no servidor hoje</strong>. Ele precisa de um dispatch do engine que não existe, e o botão Run do front tem de parar de chamar os provedores direto assim que ele existir.</p>'
           '<p>Isso é mudança de comportamento para fluxos existentes, não refatoração — e por isso esta metade espera pela <strong>D3</strong>.</p>'),
   'ba':(('In a headless run the node contributes whatever the last manual click left behind, or nothing at all.',
          'Num run sem interface o node contribui com o que o último clique manual deixou, ou com nada.'),
         ('The engine dispatches it like any other node, and the browser stops being the only place it can run.',
          'O engine o despacha como qualquer outro node, e o navegador deixa de ser o único lugar onde ele roda.')),
   'callouts':[
    ('decide',('This half is gated by D3, and D3 lives in A6','Esta metade é travada pela D3, e a D3 mora na A6'),
     ('<p>Do not answer it here. <strong>D3</strong> asks whether the nine front-driven types running headless is a fix or a customer-visible behaviour change, and the plan treats it as a <strong>product change requiring sign-off</strong> that gates the whole wave.</p>'
      '<p>Ship Part 1 and Part 2 without waiting. Part 3 starts when D3 has an answer.</p>',
      '<p>Não responda aqui. A <strong>D3</strong> pergunta se os nove tipos só-front rodando sem interface é correção ou mudança de comportamento visível ao cliente, e o plano a trata como <strong>mudança de produto que exige aprovação</strong> e trava a onda inteira.</p>'
      '<p>Entregue as Partes 1 e 2 sem esperar. A Parte 3 começa quando a D3 tiver resposta.</p>'))]},
  {'k':'part','n':'4',
   'title':('Timeouts chosen, not inherited','Timeouts escolhidos, não herdados'),
   'loc':'worker/src/modules/temporal/workflows/configs.ts',
   'purpose':('Set each provider&#x27;s timeout deliberately, because image generation is slow enough that the default is a guess.',
              'Definir o timeout de cada provedor deliberadamente, porque geração de imagem é lenta o bastante para o padrão ser um chute.'),
   'body':('<p>The spec is direct about it: image generation is slow enough that the default <code>startToCloseTimeout</code> is <strong>a guess, not a decision</strong>. Set it per provider path, in <code>configs.ts</code>, with the slowest real generation as the input rather than a round number.</p>',
           '<p>A spec é direta: geração de imagem é lenta o bastante para o <code>startToCloseTimeout</code> padrão ser <strong>um chute, não uma decisão</strong>. Defina-o por caminho de provedor, no <code>configs.ts</code>, tendo a geração real mais lenta como entrada, e não um número redondo.</p>'),
   'ba':(('The inline handler waits as long as the provider takes, inside the request, with no stated bound.',
          'O handler inline espera o quanto o provedor levar, dentro da requisição, sem limite declarado.'),
         ('Each provider path has a timeout someone chose, so a slow provider fails as a timeout instead of hanging the run.',
          'Cada caminho de provedor tem um timeout que alguém escolheu, então um provedor lento falha como timeout em vez de travar o run.')),
   'callouts':[
    ('mig',('And the wave&#x27;s latency regression applies here too','E a regressão de latência da onda também vale aqui'),
     ('<p>Both nodes become <strong>blocking round trips</strong> until Wave 5 turns on parallelism (review §4.5, risk <strong>R4</strong>). On an image node the provider call dominates the wall clock, so the added hop is a smaller share of the total than it is for <code>A4</code>&#x27;s <code>reportBuilder</code> — <strong>but measure it and state the number in the PR anyway</strong>, per DELIVERY-PLAN.</p>',
      '<p>Os dois nodes viram <strong>round trips bloqueantes</strong> até a Onda 5 ligar o paralelismo (review §4.5, risco <strong>R4</strong>). Num node de imagem a chamada ao provedor domina o relógio, então o salto adicional é uma fatia menor do total do que no <code>reportBuilder</code> da <code>A4</code> — <strong>mas meça e informe o número no PR mesmo assim</strong>, conforme o DELIVERY-PLAN.</p>'))]},
 ],
 'verif':[
  (True,('Negative control — one per provider path','Controle negativo — um por caminho de provedor'),
   ('For <strong>each</strong> provider path, break the selection so it falls through to the wrong provider, and confirm a test catches it. <strong>Six paths means six ways to silently call the wrong API</strong>; a suite that only exercises the default path is not protection.',
    'Para <strong>cada</strong> caminho de provedor, quebre a seleção para cair no provedor errado, e confirme que um teste pega. <strong>Seis caminhos significam seis formas de chamar a API errada em silêncio</strong>; uma suíte que só exercita o caminho padrão não é proteção.')),
  (True,('Billing parity against real runs','Paridade de cobrança contra runs reais'),
   ('For the same prompt and model, the <code>token_transactions</code> rows written by the worker must match what the inline path wrote. <strong>Compare against real stored runs</strong>, not synthetic ones.',
    'Para o mesmo prompt e modelo, as linhas de <code>token_transactions</code> escritas pelo worker precisam bater com o que o caminho inline escreveu. <strong>Compare contra runs reais guardados</strong>, não sintéticos.')),
  (True,('Model-access refusal, measured first','Recusa por acesso a modelo, medida antes'),
   ('A model the user is not entitled to must produce the same refusal through <code>/worker/validate-model-access</code> as it does inline. <strong>PLAN §3.3.2</strong> applies: run the check against real entitlements and <strong>drive false refusals to zero</strong> — a user refused a model they own is worse than the defect.',
    'Um modelo a que o usuário não tem direito precisa produzir a mesma recusa via <code>/worker/validate-model-access</code> que produz inline. Vale o <strong>PLAN §3.3.2</strong>: rode a checagem contra direitos reais e <strong>leve as recusas falsas a zero</strong> — um usuário recusado num modelo que ele tem é pior que o defeito.')),
  (False,('One layer, not two','Uma camada, não duas'),
   ('Confirm both node modules consume <code>ai-provider/image/</code> and neither carries its own copy of a provider call. The shared layer is the reason these two are one task — if it ends up bypassed, the task did not happen.',
    'Confirme que os dois módulos consomem <code>ai-provider/image/</code> e que nenhum carrega cópia própria de chamada a provedor. A camada compartilhada é a razão de os dois serem uma task — se ela acabar contornada, a task não aconteceu.')),
  (False,('State the latency number','Diga o número da latência'),
   ('<strong>DELIVERY-PLAN, wave 3.</strong> Both nodes become blocking round trips until Wave 5. Measure per provider path and state the numbers in the PR.',
    '<strong>DELIVERY-PLAN, onda 3.</strong> Os dois nodes viram round trips bloqueantes até a Onda 5. Meça por caminho de provedor e informe os números no PR.')),
 ],
 'done':('Both types satisfy <strong>PLAN §3.4</strong>, they <strong>share one provider layer</strong>, billing matches the inline path on real runs, timeouts were chosen per provider, and <strong>both inline handlers are deleted</strong>.',
         'Os dois tipos satisfazem o <strong>PLAN §3.4</strong>, <strong>compartilham uma camada de provedor</strong>, a cobrança bate com o caminho inline em runs reais, os timeouts foram escolhidos por provedor, e <strong>os dois handlers inline foram apagados</strong>.'),
 'files':[
  ('worker/src/modules/ai-provider/image/**',True),
  ('worker/src/modules/nodes/{image-generator,image-reader}/',True),
  ('worker/src/modules/temporal/workflows/configs.ts',False),
  ('back/src/app-api/flux/flux.service.ts:1145, 6972',False),
  ('front/src/components/nodes/ImageReader.tsx (Run path)',False),
  ('the A1 dispatch registry',False),
 ],
}
