# -*- coding: utf-8 -*-
# A6 — Give the eight front-driven types server-side execution.
# Source: TASK-A6-FRONT-DRIVEN-NODES.md, PLAN §7 D3 + risk R8, analysis §4.1/§4.2/§4.3, DELIVERY-PLAN wave 3.

DEC_D3 = {
 'k':'decision','id':'A6-a','plan':'D3','status':'open','open':True,
 'q':('Do the eight front-driven types running headless count as a <em>fix</em>, or as a behaviour change customers must be told about?',
      'Os oito tipos só-front rodando sem interface contam como <em>correção</em>, ou como mudança de comportamento que os clientes precisam saber?'),
 'intro':(
  'This is the strongest call in the wave, and the plan gates the whole wave on it: <strong>“it needs the D3 answer before this wave, not during it”</strong>. '
  'Today these nodes produce output only when someone clicks Run in the builder. In an API, cron, chatbot, form or MCP run the engine never dispatches them, '
  'so the flow uses <strong>whatever the last manual run left behind — or nothing</strong>. Analysis §4.2 puts it plainly: if a customer has an <code>animationNode</code> '
  'or a <code>documentSummarizer</code> in a scheduled flow, <strong>that flow is silently producing stale output today</strong>.'
  '<p style="margin:10px 0 0">Fixing it is almost certainly right. It is also visible: a flow that has been quietly reusing an old value starts producing a fresh one — '
  'with fresh provider spend, and, for <code>fileSave</code>, a fresh upload into someone&#x27;s Drive folder. That is why <strong>PLAN §7 treats D3 as a product change requiring sign-off</strong>, not a refactor.</p>',
  'Esta é a decisão mais forte da onda, e o plano trava a onda inteira nela: <strong>“precisa da resposta da D3 antes desta onda, não durante”</strong>. '
  'Hoje esses nodes só produzem saída quando alguém clica em Run no builder. Num run por API, cron, chatbot, formulário ou MCP o engine nunca os despacha, '
  'então o fluxo usa <strong>o que o último run manual deixou — ou nada</strong>. A análise §4.2 é direta: se um cliente tem um <code>animationNode</code> '
  'ou um <code>documentSummarizer</code> num fluxo agendado, <strong>esse fluxo está produzindo saída velha em silêncio hoje</strong>.'
  '<p style="margin:10px 0 0">Corrigir é quase certamente o certo. Também é visível: um fluxo que vinha reaproveitando um valor antigo passa a produzir um novo — '
  'com gasto novo de provedor e, no caso do <code>fileSave</code>, um upload novo na pasta do Drive de alguém. Por isso <strong>o PLAN §7 trata a D3 como mudança de produto que exige aprovação</strong>, não refatoração.</p>'),
 'opts':[
  {'ltr':'A','name':('Treat it as a bug and fix it silently','Tratar como bug e corrigir em silêncio'),
   'how':('Ship the dispatch, announce nothing. The flows simply start doing what their authors always believed they were doing.',
          'Entregar o dispatch, sem anunciar nada. Os fluxos simplesmente passam a fazer o que seus autores sempre acharam que faziam.'),
   'pros':[('It is what customers already assume is happening — nobody configured a node in order for it not to run',
            'É o que os clientes já supõem estar acontecendo — ninguém configura um node para ele não rodar'),
           ('No coordination cost, no cohort, no message to write','Sem custo de coordenação, sem coorte, sem mensagem a escrever'),
           ('One behaviour everywhere, immediately','Um único comportamento em todo lugar, de imediato')],
   'cons':[('Scheduled output changes with no warning — anything downstream that consumes it sees the change first',
            'A saída agendada muda sem aviso — quem consome a jusante vê a mudança primeiro'),
           ('New provider spend appears on the invoice for nodes that never charged in a headless run',
            'Gasto novo de provedor aparece na fatura por nodes que nunca cobraram num run sem interface'),
           ('For <code>fileSave</code>, a scheduled run starts writing files into a Drive folder that has never received one',
            'No <code>fileSave</code>, um run agendado passa a gravar arquivos numa pasta do Drive que nunca recebeu nenhum')],
   'cost':[('lo',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('hi',('Ours: <b>every surprise arrives as a ticket</b>','Nosso: <b>cada surpresa chega como chamado</b>'))]},
  {'ltr':'B','pick':True,'name':('Treat it as a behaviour change, with comms and cohorts','Tratar como mudança de comportamento, com aviso e coortes'),
   'tag':('recommended','recomendada'),
   'how':('Find the flows that contain one of the eight <em>and</em> have a headless trigger, tell their owners what will start happening, then enable per cohort behind the flag PLAN §3.2 already requires.',
          'Encontrar os fluxos que contêm um dos oito <em>e</em> têm gatilho sem interface, avisar os donos do que passará a acontecer, e habilitar por coorte atrás da flag que o PLAN §3.2 já exige.'),
   'pros':[('It is the answer the plan asks for — explicit, signed off, and recorded before the wave starts',
            'É a resposta que o plano pede — explícita, aprovada e registrada antes de a onda começar'),
           ('The owners of affected flows hear about the new spend before the invoice does',
            'Os donos dos fluxos afetados sabem do gasto novo antes da fatura'),
           ('The flag and the per-flow rollback already exist for other reasons, so the cohort costs almost nothing extra',
            'A flag e o rollback por fluxo já existem por outros motivos, então a coorte custa quase nada a mais'),
           ('The query that finds the affected flows is also the measurement the wave exit gate wants',
            'A consulta que encontra os fluxos afetados também é a medição que o gate de saída da onda quer')],
   'cons':[('Someone has to write the query and send the message, and stage the enablement',
            'Alguém precisa escrever a consulta, enviar a mensagem e escalonar a habilitação'),
           ('Slower than A — the fix waits on a human loop','Mais lento que A — a correção espera por um ciclo humano')],
   'cost':[('',('Client effort: <b>read one message</b>','Esforço do cliente: <b>ler uma mensagem</b>')),
           ('hi',('Ours: <b>a query, a message, a staged rollout</b>','Nosso: <b>uma consulta, uma mensagem, um rollout escalonado</b>'))]},
  {'ltr':'C','name':('Leave headless unsupported — but refuse it out loud','Deixar sem suporte headless — mas recusar em voz alta'),
   'how':('Keep the eight builder-only, and make validation refuse a flow that pairs a headless trigger with one of them, instead of silently skipping the node at run time.',
          'Manter os oito só no builder, e fazer a validação recusar um fluxo que junte gatilho sem interface com um deles, em vez de pular o node em silêncio no run.'),
   'pros':[('No behaviour change and no new spend','Sem mudança de comportamento e sem gasto novo'),
           ('It still fixes the <em>silent</em> half of the defect: the flow says so instead of passing a stale value off as output',
            'Ainda corrige a metade <em>silenciosa</em> do defeito: o fluxo avisa, em vez de passar um valor velho como se fosse saída'),
           ('Cheapest of the three — one validation rule','A mais barata das três — uma regra de validação')],
   'cons':[('It refuses work customers are asking for, and giving these eight server-side execution is the entire point of <code>A6</code>',
            'Recusa trabalho que os clientes estão pedindo, e dar execução no servidor a esses oito é o propósito inteiro da <code>A6</code>'),
           ('It is a refusal, so <strong>PLAN §3.3.2</strong> applies: measure it against the stored flows first, or it becomes the false refusal',
            'É uma recusa, então vale o <strong>PLAN §3.3.2</strong>: medir contra os fluxos guardados antes, senão vira a recusa falsa'),
           ('Leaves <code>fileSave</code> permanently browser-bound even though the server-side token already exists',
            'Deixa o <code>fileSave</code> preso ao navegador para sempre, mesmo com o token de servidor já existindo')],
   'cost':[('hi',('Client effort: <b>edit the flow, or drop the node</b>','Esforço do cliente: <b>editar o fluxo, ou tirar o node</b>')),
           ('lo',('Ours: <b>one validation rule</b>','Nosso: <b>uma regra de validação</b>'))]},
 ],
 'rec':(
  '<p><strong>B — and borrow C&#x27;s honesty for the gap.</strong> While a flow is still waiting for its cohort, the run log should say the node <em>was not executed</em>, rather than let a stale value pass as this run&#x27;s output. That single line turns the remaining months of the rollout from a silent defect into a stated limitation.</p>'
  '<p>The distinction that decides the cohort order is <strong>spend and side effects</strong>, not node count: <code>fileSave</code> writes into a customer&#x27;s Drive and <code>documentSummarizer</code> is LLM-backed and bills, so those flows are what the message is for. A flow whose only affected node reads a public data source is the safe cohort to start with.</p>'
  '<p><strong>A is not wrong, it is just untimed.</strong> The plan already recorded this as a product change; shipping it as a silent fix contradicts a decision that has been written down since PLAN §7, and the first person to notice will be a customer reading an invoice.</p>',
  '<p><strong>B — e pegar emprestada a honestidade da C para o intervalo.</strong> Enquanto um fluxo ainda espera a coorte dele, o log do run deve dizer que o node <em>não foi executado</em>, em vez de deixar um valor velho passar como saída deste run. Essa única linha transforma os meses restantes do rollout de defeito silencioso em limitação declarada.</p>'
  '<p>O que decide a ordem das coortes é <strong>gasto e efeito colateral</strong>, não quantidade de nodes: o <code>fileSave</code> escreve no Drive do cliente e o <code>documentSummarizer</code> é baseado em LLM e cobra, então é para esses fluxos que a mensagem serve. Um fluxo cujo único node afetado lê uma fonte pública é a coorte segura para começar.</p>'
  '<p><strong>A não é errada, só está fora de hora.</strong> O plano já registrou isto como mudança de produto; entregar como correção silenciosa contradiz uma decisão escrita desde o PLAN §7, e a primeira pessoa a notar será um cliente lendo uma fatura.</p>'),
 'who':[('Product — sign-off, per PLAN §7','Produto — aprovação, conforme PLAN §7'),
        ('Engineering owns the affected-flow query','Engenharia é dona da consulta dos fluxos afetados'),
        ('Support, before the first cohort','Suporte, antes da primeira coorte')],
}

TASK = {
 'code':'A6','vnum':'4',
 'title':('Give the front-driven types server-side execution','Dar execução no servidor aos tipos só-front'),
 'goal':('Eight node types that today run <b>only from the browser</b> get an activity and, for the first time, <b>engine dispatch</b> — so a headless run produces output instead of reusing what a person last left behind.',
         'Oito tipos de node que hoje rodam <b>só a partir do navegador</b> ganham uma activity e, pela primeira vez, <b>dispatch do engine</b> — para que um run sem interface produza saída em vez de reaproveitar o que alguém deixou por último.'),
 'glance':[
  ('crit',('Severity','Severidade'),('A product change','Uma mudança de produto'),
   ('Risk <strong>R8</strong>: flows that silently produced stale output start producing fresh output. Sign-off first — <strong>PLAN §7, D3</strong>.',
    'Risco <strong>R8</strong>: fluxos que produziam saída velha em silêncio passam a produzir saída fresca. Aprovação antes — <strong>PLAN §7, D3</strong>.')),
  ('dep',('Depends on','Depende de'),('A1 · blocked on D3','A1 · travada pela D3'),
   ('And it does not ship a relocated fetcher until <code>S6</code>&#x27;s egress decision exists and applies to it.',
    'E não entrega um buscador relocado enquanto a decisão de egresso da <code>S6</code> não existir e não se aplicar a ele.')),
  ('wave',('Wave','Onda'),('Wave 3','Onda 3'),
   ('The wave&#x27;s observable outcome is this task: headless runs stop reusing stale output. <code>S6</code> ships <em>with</em> it, not after.',
    'O resultado observável da onda é esta task: runs sem interface param de reaproveitar saída velha. A <code>S6</code> entra <em>junto</em>, não depois.')),
  ('ship',('Ship order','Ordem de entrega'),('Three stages','Três estágios'),
   ('One task because the three stages share the same three-part scope — not because they are one deploy.',
    'Uma task só porque os três estágios compartilham o mesmo escopo de três partes — não porque sejam um deploy só.')),
 ],
 'lede':(
  '<p>These eight types are <strong>front-driven</strong>: the component calls a backend endpoint directly and bypasses the flow engine (analysis §4.1). They produce output only when a user clicks Run in the builder. <strong>In an API, cron, chatbot, form or MCP run the engine never dispatches them</strong>, so the flow uses whatever the last manual run left behind — or nothing.</p>'
  '<p><code>fileSave</code> is the sharpest case. It is listed in <code>SIDE_EFFECT_TYPES</code> (<code>flux/scheduler.ts</code>), so the scheduler deliberately protects it from being pruned — <strong>yet nothing executes it server-side.</strong> Its <code>uploadToDrive()</code> runs in the browser against a <code>localStorage</code> OAuth token, so it <em>cannot</em> run headless even in principle.</p>',
  '<p>Estes oito tipos são <strong>só-front</strong>: o componente chama um endpoint do backend direto e contorna o engine de fluxo (análise §4.1). Só produzem saída quando um usuário clica em Run no builder. <strong>Num run por API, cron, chatbot, formulário ou MCP o engine nunca os despacha</strong>, então o fluxo usa o que o último run manual deixou — ou nada.</p>'
  '<p>O <code>fileSave</code> é o caso mais agudo. Ele está listado em <code>SIDE_EFFECT_TYPES</code> (<code>flux/scheduler.ts</code>), então o scheduler o protege deliberadamente de ser podado — <strong>e mesmo assim nada o executa no servidor.</strong> O <code>uploadToDrive()</code> dele roda no navegador contra um token OAuth do <code>localStorage</code>, então <em>não pode</em> rodar sem interface nem em princípio.</p>'),
 'blocks':[
  {'k':'label','n':'1','t':('The eight, and what each one actually needs','Os oito, e o que cada um de fato precisa')},
  {'k':'prose','t':(
    '<strong>Partial D3 input, 2026-09-02 — awaiting product confirmation.</strong> <code>documentSummarizer</code> and <code>commandMusicNode</code> are discontinued; <code>webAmazon</code> and <code>secApiNode</code> are broken today; <code>fileSave</code> is under review. If confirmed, Stage 2 loses two of its three and Stage 3 loses one. Record the confirmation in PLAN §7 (D3) before Stage 1 starts, and re-cut the stages then, not now. Eight types, not nine: <code>imageReaderNode</code> is deprecated (<strong>D24</strong>). One card, one PR per stage — each stage is independently deployable behind the flag (PLAN §3.1).',
    '<strong>Entrada parcial da D3, 2026-09-02 — aguardando confirmação de produto.</strong> <code>documentSummarizer</code> e <code>commandMusicNode</code> estão descontinuados; <code>webAmazon</code> e <code>secApiNode</code> estão quebrados hoje; <code>fileSave</code> está em revisão. Se confirmado, o Estágio 2 perde dois dos três e o Estágio 3 perde um. Registre a confirmação no PLAN §7 (D3) antes de o Estágio 1 começar, e recorte os estágios então, não agora. Oito tipos, não nove: o <code>imageReaderNode</code> está depreciado (<strong>D24</strong>). Um card, um PR por estágio — cada estágio sobe de forma independente atrás da flag (PLAN §3.1).')},
  {'k':'table',
   'head':[('Type','Tipo'),('Stage','Estágio'),('What it needs','O que precisa'),('Why','Por quê')],
   'rows':[
    [{'t':'webTrends','mono':True},{'t':('Stage 1','Estágio 1'),'pill':'ok'},
     ('Nothing but the activity and the dispatch','Nada além da activity e do dispatch'),
     ('The SerpApi client is already in the worker, inside <code>web-search</code>.','O cliente do SerpApi já está no worker, dentro do <code>web-search</code>.')],
    [{'t':'webAmazon','mono':True},{'t':('Stage 1','Estágio 1'),'pill':'ok'},
     ('The activity, the dispatch, and <code>S6</code>&#x27;s egress policy','A activity, o dispatch, e a política de egresso da <code>S6</code>'),
     ('The Scraper client is already in the worker, inside <code>web-crawling</code>.','O cliente do Scraper já está no worker, dentro do <code>web-crawling</code>.')],
    [{'t':'fileSave','mono':True},{'t':('Stage 1','Estágio 1'),'pill':'ok'},
     ('A server-side Google token on the run path','Um token do Google no servidor, no caminho do run'),
     ('<code>GoogleDriveService.uploadFile</code> and <code>TokenProviderService</code> already exist in the worker. The refresh condition is the work.',
      '<code>GoogleDriveService.uploadFile</code> e <code>TokenProviderService</code> já existem no worker. A condição de refresh é o trabalho.')],
    [{'t':'secApiNode','mono':True},{'t':('Stage 2','Estágio 2'),'pill':'weak'},
     ('Port a small client from <code>app-api/sec</code>','Portar um cliente pequeno de <code>app-api/sec</code>'),
     ('No credentials beyond an env key.','Sem credenciais além de uma chave de ambiente.')],
    [{'t':'usCensusNode','mono':True},{'t':('Stage 2','Estágio 2'),'pill':'weak'},
     ('Port a small client from <code>app-api/census_data</code>','Portar um cliente pequeno de <code>app-api/census_data</code>'),
     ('No credentials beyond an env key.','Sem credenciais além de uma chave de ambiente.')],
    [{'t':'documentSummarizer','mono':True},{'t':('Stage 2','Estágio 2'),'pill':'weak'},
     ('<code>app-api/summarize</code>, plus billing and model access','<code>app-api/summarize</code>, mais cobrança e acesso a modelo'),
     ('It is LLM-backed, so it uses the existing callbacks rather than new ones.','É baseado em LLM, então usa os callbacks existentes em vez de novos.')],
    [{'t':'commandMusicNode','mono':True},{'t':('Stage 3','Estágio 3'),'pill':'weak'},
     ('Replicate, <code>/worker/generate-file</code>, chosen timeouts','Replicate, <code>/worker/generate-file</code>, timeouts escolhidos'),
     ('It produces an asset and is long-running, so the timeouts are decided, not inherited.','Produz um ativo e é demorado, então os timeouts são decididos, não herdados.')],
    [{'t':'animationNode','mono':True},{'t':('Stage 3','Estágio 3'),'pill':'weak'},
     ('Luma + Runway, <code>/worker/generate-file</code>, chosen timeouts','Luma + Runway, <code>/worker/generate-file</code>, timeouts escolhidos'),
     ('Same shape as the music node, with two providers instead of one.','Mesmo formato do node de música, com dois provedores em vez de um.')],
    [{'t':'imageReaderNode','mono':True},{'t':('Deprecated (D24)','Depreciado (D24)'),'pill':'no'},
     ('Nothing — it leaves the migration','Nada — sai da migração'),
     ('The ninth of the census. Deprecated on 2026-09-02; an OCR node is wanted later and will be specified when it is built, not here.',
      'O nono do censo. Depreciado em 2026-09-02; um node de OCR é desejado depois e será especificado quando for construído, não aqui.')],
   ]},
  {'k':'label','n':'2','t':('The decision this task needs','A decisão que esta task precisa')},
  {'k':'prose','t':(
    'One call gates the whole wave, and it is not an engineering call. It is the difference between a defect we fix quietly and a change customers are told about — '
    'and the honest part is that <strong>flows which produced stale output in silence will start producing fresh output</strong>, with the spend and the side effects that come with it.',
    'Uma decisão trava a onda inteira, e ela não é de engenharia. É a diferença entre um defeito corrigido em silêncio e uma mudança comunicada ao cliente — '
    'e a parte honesta é que <strong>fluxos que produziam saída velha em silêncio passarão a produzir saída fresca</strong>, com o gasto e os efeitos colaterais que vêm junto.')},
  DEC_D3,
  {'k':'label','n':'3','t':('What the task does, in five parts','O que a task faz, em cinco partes')},
  {'k':'part','n':'1',
   'title':('Three things, and the second exists for no other task in this epic','Três coisas, e a segunda não existe em nenhuma outra task deste épico'),
   'loc':('analysis §4.1, §4.3', 'análise §4.1, §4.3'),
   'purpose':('Name the scope precisely, because “migrate these nodes” describes something that cannot happen — nothing executes in the back today.',
              'Nomear o escopo com precisão, porque “migrar estes nodes” descreve algo que não pode acontecer — nada executa no back hoje.'),
   'body':('<p>The scope is <strong>not</strong> “move code from the back”. It is three things:</p>',
           '<p>O escopo <strong>não é</strong> “mover código do back”. São três coisas:</p>'),
   'list':[
    ('<strong>Implement the activity</strong> — the normal seven-layer registration chain.',
     '<strong>Implementar a activity</strong> — a cadeia normal de registro em sete camadas.'),
    ('<strong>Make the engine dispatch the type for the first time</strong>, including declaring its dependency edges to the scheduler so it runs in the right order. No other task in this epic adds a dispatch that never existed.',
     '<strong>Fazer o engine despachar o tipo pela primeira vez</strong>, incluindo declarar as arestas de dependência ao scheduler para que rode na ordem certa. Nenhuma outra task deste épico acrescenta um dispatch que nunca existiu.'),
    ('<strong>Decide what the front&#x27;s Run button does afterwards</strong>: route it through <code>ProcessService.response</code> (<code>POST /process/single-node</code>) like every migrated node, and delete the direct provider call.',
     '<strong>Decidir o que o botão Run do front faz depois</strong>: passar por <code>ProcessService.response</code> (<code>POST /process/single-node</code>) como todo node migrado, e apagar a chamada direta ao provedor.'),
   ],
   'ba':(('A headless run skips the node entirely. Whatever <code>data.text</code> the last manual click left behind is what the rest of the flow consumes.',
          'Um run sem interface pula o node inteiro. O que o último clique manual deixou em <code>data.text</code> é o que o resto do fluxo consome.'),
         ('The engine dispatches the node like any other, in dependency order, and the value the flow consumes was produced by <strong>this</strong> run.',
          'O engine despacha o node como qualquer outro, na ordem de dependência, e o valor que o fluxo consome foi produzido por <strong>este</strong> run.')),
   'callouts':[
    ('mig',('Two paths is how the four lists diverged','Dois caminhos foi como as quatro listas divergiram'),
     ('<p>Keeping the direct provider call “as a preview path” alongside the new dispatch is <strong>exactly</strong> the pattern that produced four uncoordinated dispatch lists in the first place. The Run button routes through the same execution as everything else, and the direct call is <strong>deleted, not merely unused</strong>.</p>',
      '<p>Manter a chamada direta ao provedor “como caminho de preview” ao lado do dispatch novo é <strong>exatamente</strong> o padrão que produziu quatro listas de dispatch descoordenadas. O botão Run passa pela mesma execução que todo o resto, e a chamada direta é <strong>apagada, não apenas deixada sem uso</strong>.</p>'))]},
  {'k':'part','n':'2',
   'title':('Stage 1 — the three that are almost free','Estágio 1 — os três quase de graça'),
   'loc':'flux/scheduler.ts · flux.service.ts',
   'purpose':('Ship the three types whose provider clients are already in the worker, and fix the one that cannot run headless even in principle.',
              'Entregar os três tipos cujos clientes de provedor já estão no worker, e corrigir o único que não pode rodar sem interface nem em princípio.'),
   'body':('<p><code>webTrends</code> and <code>webAmazon</code> need no provider work at all — the SerpApi and Scraper clients are already in the worker, inside <code>web-search</code> and <code>web-crawling</code>.</p>'
           '<p><code>fileSave</code> is the most valuable of the three and the worst offender. The server-side token already exists (<code>user.googleRefreshToken</code>) and the engine already refreshes it — <strong>but only when the flow has <code>pullData</code>/<code>pushData</code> with <code>provider = google</code></strong> (<code>flux.service.ts</code>). <strong>Extend that condition; do not build a second refresh path.</strong></p>',
           '<p><code>webTrends</code> e <code>webAmazon</code> não exigem trabalho de provedor nenhum — os clientes do SerpApi e do Scraper já estão no worker, dentro do <code>web-search</code> e do <code>web-crawling</code>.</p>'
           '<p>O <code>fileSave</code> é o mais valioso dos três e o pior infrator. O token de servidor já existe (<code>user.googleRefreshToken</code>) e o engine já o renova — <strong>mas só quando o fluxo tem <code>pullData</code>/<code>pushData</code> com <code>provider = google</code></strong> (<code>flux.service.ts</code>). <strong>Estenda essa condição; não construa um segundo caminho de refresh.</strong></p>'),
   'ba':(('The scheduler protects <code>fileSave</code> from being pruned as a dead branch, and then nothing runs it. The upload happens in a browser tab, against a token in <code>localStorage</code>.',
          'O scheduler protege o <code>fileSave</code> de ser podado como ramo morto, e depois nada o executa. O upload acontece numa aba do navegador, contra um token no <code>localStorage</code>.'),
         ('A scheduled run uploads to Drive with the server-side token, <strong>with no browser involved</strong> — and the refresh condition that already exists is the one that does it.',
          'Um run agendado envia para o Drive com o token de servidor, <strong>sem navegador nenhum envolvido</strong> — e é a condição de refresh que já existe que faz isso.'))},
  {'k':'part','n':'3',
   'title':('Stage 2 — port a small client','Estágio 2 — portar um cliente pequeno'),
   'loc':'back/src/app-api/{sec,census_data,summarize}/',
   'purpose':('Three types whose backend module is a thin HTTP client, so the port is volume rather than design.',
              'Três tipos cujo módulo no backend é um cliente HTTP fino, então o porte é volume, não desenho.'),
   'body':('<p><code>secApiNode</code> (<code>app-api/sec</code>), <code>usCensusNode</code> (<code>app-api/census_data</code>) and <code>documentSummarizer</code> (<code>app-api/summarize</code>). No credentials beyond an env key — <strong>except <code>documentSummarizer</code>, which is LLM-backed</strong> and therefore uses the existing billing and model-access callbacks rather than anything new.</p>'
           '<p>All three are on <code>S6</code>&#x27;s list of relocated fetchers, so its egress policy applies to them before they ship.</p>',
           '<p><code>secApiNode</code> (<code>app-api/sec</code>), <code>usCensusNode</code> (<code>app-api/census_data</code>) e <code>documentSummarizer</code> (<code>app-api/summarize</code>). Sem credenciais além de uma chave de ambiente — <strong>exceto o <code>documentSummarizer</code>, que é baseado em LLM</strong> e por isso usa os callbacks de cobrança e acesso a modelo já existentes, e não algo novo.</p>'
           '<p>Os três estão na lista de buscadores relocados da <code>S6</code>, então a política de egresso dela se aplica a eles antes de entrarem.</p>'),
   'ba':(('Three backend modules that only a front component ever calls, and only when a person is watching.',
          'Três módulos de backend que só um componente do front chama, e só quando alguém está olhando.'),
         ('Three worker modules the engine dispatches, with the LLM-backed one billing through the same contract as every other LLM node.',
          'Três módulos no worker que o engine despacha, com o baseado em LLM cobrando pelo mesmo contrato de todo outro node de LLM.'))},
  {'k':'part','n':'4',
   'title':('Stage 3 — asset providers, and timeouts that are chosen','Estágio 3 — provedores de ativo, e timeouts escolhidos'),
   'loc':'worker/src/modules/temporal/workflows/configs.ts',
   'purpose':('The two long-running types, where an inherited timeout is a guess that surfaces as a failed run.',
              'Os dois tipos demorados, em que um timeout herdado é um chute que aparece como run falho.'),
   'body':('<p><code>commandMusicNode</code> (Replicate) and <code>animationNode</code> (Luma + Runway). Both produce assets, so both use <code>/worker/generate-file</code>; both are long-running, so both need their <code>startToCloseTimeout</code> <strong>and</strong> <code>heartbeatTimeout</code> chosen deliberately rather than inherited.</p>',
           '<p><code>commandMusicNode</code> (Replicate) e <code>animationNode</code> (Luma + Runway). Os dois produzem ativos, então os dois usam o <code>/worker/generate-file</code>; os dois são demorados, então os dois precisam do <code>startToCloseTimeout</code> <strong>e</strong> do <code>heartbeatTimeout</code> escolhidos deliberadamente, e não herdados.</p>'),
   'ba':(('A video or a track is generated in a browser tab, and a closed tab is a lost generation.',
          'Um vídeo ou uma faixa é gerado numa aba do navegador, e uma aba fechada é uma geração perdida.'),
         ('The generation is an activity with a timeout someone chose and a heartbeat that proves it is still alive.',
          'A geração é uma activity com timeout que alguém escolheu e um heartbeat que prova que ela ainda está viva.')),
   'callouts':[
    ('mig',('The wave&#x27;s latency regression applies to all eight','A regressão de latência da onda vale para os oito'),
     ('<p>Every node this wave migrates is a <strong>blocking round trip</strong> until Wave 5 turns on parallelism (review §4.5, risk <strong>R4</strong>). For these eight the comparison is unusual: the headless path had <em>no</em> latency because it did not run at all. <strong>Measure the builder path before and after</strong>, and state the number in the PR — that is the comparison a customer will actually feel.</p>',
      '<p>Todo node migrado nesta onda é um <strong>round trip bloqueante</strong> até a Onda 5 ligar o paralelismo (review §4.5, risco <strong>R4</strong>). Para estes oito a comparação é atípica: o caminho sem interface não tinha latência <em>nenhuma</em> porque não rodava. <strong>Meça o caminho do builder antes e depois</strong>, e informe o número no PR — é essa a comparação que o cliente vai sentir.</p>'))]},
  {'k':'part','n':'5',
   'title':('The egress policy ships with the move, not after it','A política de egresso entra junto com a mudança, não depois'),
   'loc':'TASK-S6-SSRF-POLICY.md',
   'purpose':('Several of these nodes fetch user-controlled URLs, and this task moves them into the host that holds the database password.',
              'Vários destes nodes buscam URLs controladas pelo usuário, e esta task os move para o host que guarda a senha do banco.'),
   'body':('<p>There is no SSRF protection today (review §3.2), and whether relocating these fetchers improves or worsens the exposure depends on the worker&#x27;s network position — which nobody has written down.</p>'
           '<p><strong><code>S6</code> owns the policy.</strong> This task does not ship a relocated fetcher until S6&#x27;s decision exists <em>and applies to it</em>. The point of S6 is that the decision is made <strong>with</strong> the move, because the move is what changes the risk.</p>',
           '<p>Não existe proteção contra SSRF hoje (review §3.2), e se relocar esses buscadores melhora ou piora a exposição depende da posição de rede do worker — que ninguém registrou.</p>'
           '<p><strong>A <code>S6</code> é dona da política.</strong> Esta task não entrega um buscador relocado enquanto a decisão da S6 não existir <em>e não se aplicar a ele</em>. O ponto da S6 é que a decisão seja tomada <strong>junto</strong> com a mudança, porque é a mudança que altera o risco.</p>'),
   'ba':(('A node can point at an internal hostname or the cloud metadata endpoint, from the backend, with nothing checking the address.',
          'Um node pode apontar para um hostname interno ou para o endpoint de metadados da nuvem, a partir do backend, sem nada checando o endereço.'),
         ('The same fetch runs under one egress policy, from a host whose network position is documented — and the policy ran in report-only mode first.',
          'A mesma busca roda sob uma política de egresso, a partir de um host cuja posição de rede está documentada — e a política rodou antes em modo somente-relatório.')),
   'callouts':[
    ('decide',('The policy is decided in S6, on this page&#x27;s schedule','A política é decidida na S6, no cronograma desta página'),
     ('<p>S6 carries two open calls — the <strong>shape of the policy</strong> and the <strong>worker&#x27;s network position</strong>. Both are answered on the <code>S6</code> page, and both must be answered before Stage 1&#x27;s <code>webAmazon</code> and Stage 2&#x27;s three clients relocate their fetches.</p>',
      '<p>A S6 carrega duas decisões em aberto — o <strong>formato da política</strong> e a <strong>posição de rede do worker</strong>. As duas são respondidas na página da <code>S6</code>, e as duas precisam de resposta antes de o <code>webAmazon</code> do Estágio 1 e os três clientes do Estágio 2 relocarem suas buscas.</p>'))]},
 ],
 'verif':[
  (True,('Negative control, per stage — the one that reproduces production','Controle negativo, por estágio — o que reproduz a produção'),
   ('Remove the engine dispatch for one type and confirm a test fails proving the node did <strong>not</strong> run in a headless flow. That is precisely today&#x27;s production behaviour, so this is <strong>the one test in the epic that reproduces the defect being fixed</strong> — write it first, watch it pass against <code>main</code>, then make it fail.',
    'Remova o dispatch do engine de um tipo e confirme que um teste falha provando que o node <strong>não</strong> rodou num fluxo sem interface. Esse é exatamente o comportamento de produção hoje, então este é <strong>o único teste do épico que reproduz o defeito sendo corrigido</strong> — escreva primeiro, veja passar contra a <code>main</code>, depois faça falhar.')),
  (True,('Headless parity, per type','Paridade sem interface, por tipo'),
   ('For each type: run the same flow via the builder Run button and via an API trigger, and assert <strong>both</strong> produce output. Today only the first does.',
    'Para cada tipo: rode o mesmo fluxo pelo botão Run do builder e por um gatilho de API, e verifique que <strong>os dois</strong> produzem saída. Hoje só o primeiro produz.')),
  (True,('<code>fileSave</code> specifically','<code>fileSave</code> em particular'),
   ('Prove a <strong>scheduled</strong> run uploads to Drive with the server-side token, <strong>with no browser involved</strong>. It is the one type that cannot run headless even in principle today, so a passing test here is the proof the whole stage worked.',
    'Prove que um run <strong>agendado</strong> envia ao Drive com o token de servidor, <strong>sem navegador nenhum</strong>. É o único tipo que hoje não pode rodar sem interface nem em princípio, então um teste verde aqui é a prova de que o estágio inteiro funcionou.')),
  (True,('No double execution','Sem execução dupla'),
   ('Once the front&#x27;s Run button is rerouted, the direct provider call must be <strong>gone, not merely unused</strong>. A dead code path that still compiles is the shape risk <strong>R1</strong> describes.',
    'Depois de redirecionar o botão Run do front, a chamada direta ao provedor precisa estar <strong>removida, não apenas sem uso</strong>. Um caminho morto que ainda compila é o formato que o risco <strong>R1</strong> descreve.')),
  (False,('The affected-flow count is recorded','A contagem de fluxos afetados é registrada'),
   ('D3&#x27;s answer needs a number: <strong>how many stored flows contain one of the eight and have a headless trigger</strong>. Record it — it decides the cohort order, and it is the same query the wave&#x27;s exit gate asks for.',
    'A resposta da D3 precisa de um número: <strong>quantos fluxos guardados contêm um dos oito e têm gatilho sem interface</strong>. Registre — ele decide a ordem das coortes, e é a mesma consulta que o gate de saída da onda pede.')),
 ],
 'done':('All eight satisfy <strong>PLAN §3.4</strong>, <strong>a headless run produces output for each</strong>, and <strong>no front component calls a provider service directly for execution</strong> — with D3 answered and recorded before Stage 1 began.',
         'Os oito satisfazem o <strong>PLAN §3.4</strong>, <strong>um run sem interface produz saída para cada um</strong>, e <strong>nenhum componente do front chama um serviço de provedor direto para executar</strong> — com a D3 respondida e registrada antes de o Estágio 1 começar.'),
 'files':[
  ('front/src/components/nodes/{WebTrends,WebAmazon,SecApiNode,UsCensusNode,AiTextSummarizer,AiMusicGenerator,AiVideoGenerator}.tsx',False),
  ('front/src/components/FileSave/FileSave.tsx',False),
  ('back/src/app-api/{sec,census_data,summarize,scraper,serpApi,repiclate,luma_labs,runwayML}/',False),
  ('back/src/app-api/flux/flux.service.ts (the Google refresh-token condition on pullData/pushData)',False),
  ('back/src/app-api/flux/scheduler.ts (SIDE_EFFECT_TYPES)',False),
  ('new worker modules — 8 types across 3 stages',True),
  ('the A1 dispatch registry',False),
 ],
}
