# -*- coding: utf-8 -*-
# A8 — Move input extraction and OCR off the request path.
# Source: TASK-A8-INPUT-EXTRACTION.md, analysis §11.1, DELIVERY-PLAN wave 3.

TASK = {
 'code':'A8','vnum':'3',
 'title':('Move input extraction and OCR off the request path','Tirar extração de entrada e OCR do caminho da requisição'),
 'goal':('The link extraction, file upload and OCR that <code>varInputNode</code> performs <b>at the start of every run</b> stop blocking the backend.',
         'A extração de links, o upload de arquivos e o OCR que o <code>varInputNode</code> faz <b>no início de todo run</b> param de bloquear o backend.'),
 'glance':[
  ('crit',('Severity','Severidade'),('On the critical path','No caminho crítico'),
   ('Synchronous external I/O before the loop, on every run that has one. The step notes: OCR <em>“é síncrono e cega o backend”</em>.',
    'I/O externo síncrono antes do laço, em todo run que tenha um. As notas de passo: o OCR <em>“é síncrono e cega o backend”</em>.')),
  ('dep',('Depends on','Depende de'),('A1 · source: §11.1','A1 · fonte: §11.1'),
   ('This task exists because the census was wrong — <code>varInputNode</code> was classified inert.',
    'Esta task existe porque o censo estava errado — o <code>varInputNode</code> foi classificado como inerte.')),
  ('wave',('Wave','Onda'),('Wave 3','Onda 3'),
   ('The one migration in the wave that <em>removes</em> blocking work from the backend rather than only relocating it.',
    'A única migração da onda que <em>remove</em> trabalho bloqueante do backend em vez de apenas relocá-lo.')),
  ('ship',('Shape','Formato'),('One activity + three cheap wins','Uma activity + três ganhos baratos'),
   ('An extraction cache, batched writes, and the telemetry that makes the improvement measurable at all.',
    'Um cache de extração, escritas em lote, e a telemetria que torna a melhoria mensurável.')),
 ],
 'lede':(
  '<p>During a run, <strong>before the loop</strong>, the engine iterates every <code>varInputNode</code> (<code>flux.service.ts:2772, 2806</code>) and does real external I/O: <code>extractionService.extractTextFromLink</code> per link and <code>awsService.uploadFile</code> per file (<code>:2834–2990</code>), with an OCR mode chosen per input (<code>typeOCR</code>).</p>'
  '<p>It is <strong>invisible to every dispatch gate</strong>, because it is resolved <em>before</em> <code>nextReady</code> ever runs — so it is not in <code>isTemporalNode</code>, not in the prefetch whitelist, and not in the census. It is nonetheless synchronous, external, and on the critical path of every run that has one.</p>',
  '<p>Durante um run, <strong>antes do laço</strong>, o engine percorre cada <code>varInputNode</code> (<code>flux.service.ts:2772, 2806</code>) e faz I/O externo de verdade: <code>extractionService.extractTextFromLink</code> por link e <code>awsService.uploadFile</code> por arquivo (<code>:2834–2990</code>), com um modo de OCR escolhido por entrada (<code>typeOCR</code>).</p>'
  '<p>É <strong>invisível a todo gate de dispatch</strong>, porque é resolvido <em>antes</em> de o <code>nextReady</code> rodar — então não está no <code>isTemporalNode</code>, não está na whitelist de prefetch, e não estava no censo. Ainda assim é síncrono, externo, e está no caminho crítico de todo run que o contém.</p>'),
 'blocks':[
  {'k':'label','n':'1','t':('Why this was missed, in four places','Por que isto passou batido, em quatro lugares')},
  {'k':'table',
   'head':[('Where it was checked','Onde foi checado'),('What that said','O que aquilo dizia'),('What the run actually does','O que o run de fato faz')],
   'rows':[
    [{'t':('The front component','O componente do front')},
     {'t':('Calls the backend at configuration time only','Chama o backend só na configuração')},
     ('True of the component, <strong>false of the run</strong>. The run path never goes through the component.',
      'Verdade sobre o componente, <strong>mentira sobre o run</strong>. O caminho do run nunca passa pelo componente.')],
    [{'t':('<code>isTemporalNode</code>','<code>isTemporalNode</code>')},
     {'t':('Not in it','Não está lá'),'pill':'no'},
     ('It is resolved <strong>before</strong> <code>nextReady</code> ever runs, so no dispatch gate can see it.',
      'É resolvido <strong>antes</strong> de o <code>nextReady</code> rodar, então nenhum gate de dispatch o enxerga.')],
    [{'t':('The prefetch whitelist','A whitelist de prefetch')},
     {'t':('Not in it','Não está lá'),'pill':'no'},
     ('Same reason. Nothing that gates dispatch can gate work that happens before dispatch exists.',
      'Mesma razão. Nada que controla dispatch controla trabalho que acontece antes de o dispatch existir.')],
    [{'t':('The node census','O censo de nodes')},
     {'t':('Classified inert','Classificado como inerte'),'pill':'no'},
     ('Analysis §11.1 corrects it: the inert group drops from 12 to 11 and the migration backlog rises to 13.',
      'A análise §11.1 corrige: o grupo inerte cai de 12 para 11 e o backlog de migração sobe para 13.')],
   ]},
  {'k':'label','n':'2','t':('What the task does, in three parts','O que a task faz, em três partes')},
  {'k':'part','n':'1',
   'title':('The extraction activity','A activity de extração'),
   'loc':'flux.service.ts:2772–2990',
   'purpose':('Free the backend while OCR runs, which is this task&#x27;s entire justification.',
              'Liberar o backend enquanto o OCR roda, que é a justificativa inteira desta task.'),
   'body':('<p>The step documentation says it in one line — OCR <em>“é síncrono e cega o backend”</em>: it is synchronous, and it blinds the backend. A dedicated activity is a large win for agents with several files, because today the files are processed <strong>in the request</strong>, one after another, before a single node has run.</p>'
           '<p>The activity takes the inputs, does the extraction and the upload, and returns the resolved values. The engine stops waiting on an external service while it holds the run.</p>',
           '<p>A documentação de passo diz numa linha — o OCR <em>“é síncrono e cega o backend”</em>. Uma activity dedicada é um ganho grande para agentes com vários arquivos, porque hoje os arquivos são processados <strong>dentro da requisição</strong>, um depois do outro, antes de um único node rodar.</p>'
           '<p>A activity recebe as entradas, faz a extração e o upload, e devolve os valores resolvidos. O engine deixa de esperar por um serviço externo enquanto segura o run.</p>'),
   'ba':(('Every link and every file is extracted and uploaded inside the backend request, sequentially, before the loop starts. A slow OCR blinds the process.',
          'Cada link e cada arquivo é extraído e enviado dentro da requisição do backend, sequencialmente, antes de o laço começar. Um OCR lento cega o processo.'),
         ('The extraction is an activity. The backend is free while it runs, and a slow provider costs the run time — <strong>not the process</strong>.',
          'A extração é uma activity. O backend fica livre enquanto ela roda, e um provedor lento custa tempo do run — <strong>não do processo</strong>.')),
   'callouts':[
    ('mig',('Measure it, and say the number','Meça, e diga o número'),
     ('<p>The wave carries a latency regression by design — every node migrated here is a <strong>blocking round trip</strong> until Wave 5 (review §4.5, risk <strong>R4</strong>). This task is the one where the trade may go the other way, because the backend stops blocking on OCR.</p>'
      '<p>That is a claim, and DELIVERY-PLAN asks for the number per task. <strong>Measure latency before and after, per input type</strong> — link, file, each OCR mode — and state it in the PR. Without the number, the justification is a hope.</p>',
      '<p>A onda carrega uma regressão de latência por desenho — todo node migrado aqui vira um <strong>round trip bloqueante</strong> até a Onda 5 (review §4.5, risco <strong>R4</strong>). Esta task é aquela em que a troca pode ir para o outro lado, porque o backend deixa de bloquear no OCR.</p>'
      '<p>Isso é uma afirmação, e o DELIVERY-PLAN pede o número por task. <strong>Meça a latência antes e depois, por tipo de entrada</strong> — link, arquivo, cada modo de OCR — e informe no PR. Sem o número, a justificativa é uma esperança.</p>'))]},
  {'k':'part','n':'2',
   'title':('Three improvements that are cheap while the code is open','Três melhorias baratas enquanto o código está aberto'),
   'loc':('persistInputNodeData · extraction telemetry', 'persistInputNodeData · telemetria de extração'),
   'purpose':('Take the three wins the same source flags, because each of them is expensive to come back for.',
              'Pegar os três ganhos que a mesma fonte aponta, porque voltar para cada um depois é caro.'),
   'body':('<p>The source that corrected the census also flags three improvements, each cheap while this code is being rewritten anyway:</p>',
           '<p>A fonte que corrigiu o censo também aponta três melhorias, cada uma barata enquanto este código já está sendo reescrito:</p>'),
   'list':[
    ('<strong>Extraction cache</strong>, keyed by URL or file hash. Sub-flows re-extract the same file today — <strong>pure rework</strong>, paid for on every nesting level.',
     '<strong>Cache de extração</strong>, com chave por URL ou hash do arquivo. Sub-fluxos reextraem o mesmo arquivo hoje — <strong>retrabalho puro</strong>, pago em cada nível de aninhamento.'),
    ('<strong>Batch the writes.</strong> <code>persistInputNodeData</code> runs one <code>UPDATE</code> per input, sequentially — a row-at-a-time write pattern in front of work that is already slow.',
     '<strong>Escritas em lote.</strong> O <code>persistInputNodeData</code> roda um <code>UPDATE</code> por entrada, sequencialmente — um padrão de escrita linha a linha na frente de um trabalho que já é lento.'),
    ('<strong>Telemetry.</strong> Nothing is logged today about OCR duration, file size or provider, which makes Phase-1 latency <strong>undiagnosable</strong>. Add it <em>before</em> changing the shape, so the change can be measured.',
     '<strong>Telemetria.</strong> Nada é registrado hoje sobre duração do OCR, tamanho do arquivo ou provedor, o que torna a latência da Fase 1 <strong>indiagnosticável</strong>. Adicione <em>antes</em> de mudar o formato, para que a mudança possa ser medida.'),
   ],
   'body2':('<p>The order matters: <strong>telemetry first</strong>. A change whose justification is latency, shipped into a system that does not record latency, cannot be defended or reverted on evidence.</p>',
            '<p>A ordem importa: <strong>telemetria primeiro</strong>. Uma mudança cuja justificativa é latência, entregue num sistema que não registra latência, não pode ser defendida nem revertida com evidência.</p>'),
   'ba':(('The same file is extracted again in every sub-flow, each input is written with its own <code>UPDATE</code>, and no log says how long any of it took.',
          'O mesmo arquivo é extraído de novo em cada sub-fluxo, cada entrada é gravada com um <code>UPDATE</code> próprio, e nenhum log diz quanto tempo aquilo levou.'),
         ('Extract once per URL or file hash, write the inputs in one batch, and have the duration, the size and the provider in the log before and after the change.',
          'Extrai uma vez por URL ou hash de arquivo, grava as entradas num lote, e tem duração, tamanho e provedor no log antes e depois da mudança.'))},
  {'k':'part','n':'3',
   'title':('What stays exactly as it is','O que fica exatamente como está'),
   'loc':'extractText · TASK-S6-SSRF-POLICY.md',
   'purpose':('Two things this task deliberately does not touch, and one it must wait for.',
              'Duas coisas que esta task deliberadamente não toca, e uma pela qual precisa esperar.'),
   'body':('<p><strong>Renaming <code>extractText</code> is out of scope.</strong> The field holds URLs when <code>isExtraction</code> is false, which is confusing — but renaming a persisted field is its own migration, with its own risk, and it does not belong inside a latency change.</p>'
           '<p><strong>The egress policy comes first.</strong> Several of these inputs are user-controlled URLs, and this task moves the fetching into the worker, which holds the database password and the integrations key. <code>S6</code> owns the policy, and this task <strong>does not ship a relocated fetcher until S6&#x27;s decision exists and applies to it</strong>.</p>',
           '<p><strong>Renomear o <code>extractText</code> está fora de escopo.</strong> O campo guarda URLs quando <code>isExtraction</code> é falso, o que confunde — mas renomear um campo persistido é uma migração própria, com risco próprio, e não cabe dentro de uma mudança de latência.</p>'
           '<p><strong>A política de egresso vem antes.</strong> Várias dessas entradas são URLs controladas pelo usuário, e esta task move a busca para o worker, que guarda a senha do banco e a chave das integrações. A <code>S6</code> é dona da política, e esta task <strong>não entrega um buscador relocado enquanto a decisão da S6 não existir e não se aplicar a ele</strong>.</p>'),
   'ba':(('A user-controlled link is fetched from the backend with nothing checking the address it resolves to.',
          'Um link controlado pelo usuário é buscado a partir do backend, sem nada checando o endereço para o qual ele resolve.'),
         ('The same link is fetched under one egress policy, from a host whose network position was written down first.',
          'O mesmo link é buscado sob uma política de egresso, a partir de um host cuja posição de rede foi registrada antes.')),
   'callouts':[
    ('decide',('The decision lives in S6, and it is made with this move','A decisão mora na S6, e é tomada junto com esta mudança'),
     ('<p>S6 carries two open calls — the <strong>shape of the policy</strong> and the <strong>worker&#x27;s network position</strong> — and the point of S6 is that they are answered <em>with</em> the relocation, because the relocation is what changes the risk. Nothing here is decided on this page.</p>',
      '<p>A S6 carrega duas decisões em aberto — o <strong>formato da política</strong> e a <strong>posição de rede do worker</strong> — e o ponto da S6 é que sejam respondidas <em>junto</em> com a relocação, porque é a relocação que altera o risco. Nada aqui é decidido nesta página.</p>'))]},
 ],
 'verif':[
  (True,('Negative control — the empty input','Controle negativo — a entrada vazia'),
   ('Break the extraction call and confirm a test fails on the <strong>resolved input being empty</strong>, rather than the run continuing with a blank variable. Today a failed extraction can leave a placeholder resolving to nothing, which reads downstream as <em>a bad prompt</em> rather than <em>a failed upload</em> — that is the failure this test must pin.',
    'Quebre a chamada de extração e confirme que um teste falha na <strong>entrada resolvida estar vazia</strong>, em vez de o run seguir com uma variável em branco. Hoje uma extração que falha pode deixar um placeholder resolvendo para nada, o que a jusante parece <em>prompt ruim</em> e não <em>upload que falhou</em> — é essa falha que o teste precisa fixar.')),
  (True,('Parity on real inputs','Paridade em entradas reais'),
   ('Same link and same file, backend versus worker, <strong>byte-identical extracted text</strong>. Not a similar result — the same bytes.',
    'Mesmo link e mesmo arquivo, backend versus worker, <strong>texto extraído byte a byte idêntico</strong>. Não um resultado parecido — os mesmos bytes.')),
  (True,('Latency, before and after, per input type','Latência, antes e depois, por tipo de entrada'),
   ('This task&#x27;s whole justification is that the backend stops blocking. <strong>State the number</strong> — per input type, with the telemetry added before the change so both sides of the comparison exist.',
    'A justificativa inteira desta task é o backend parar de bloquear. <strong>Informe o número</strong> — por tipo de entrada, com a telemetria adicionada antes da mudança para que os dois lados da comparação existam.')),
  (False,('Cache correctness','Correção do cache'),
   ('The same file in two nodes extracts <strong>once</strong>; a <strong>changed</strong> file does not serve a stale extraction. Both halves matter — a cache that never invalidates turns a fresh document into an old one silently.',
    'O mesmo arquivo em dois nodes extrai <strong>uma vez</strong>; um arquivo <strong>alterado</strong> não recebe extração velha. As duas metades importam — um cache que nunca invalida transforma um documento novo em antigo, em silêncio.')),
 ],
 'done':('Extraction and OCR run <strong>as an activity</strong>, parity is proven on real inputs, <strong>the backend no longer blocks on them</strong>, and the before/after latency is recorded.',
         'Extração e OCR rodam <strong>como activity</strong>, a paridade está provada em entradas reais, <strong>o backend não bloqueia mais nelas</strong>, e a latência antes/depois está registrada.'),
 'files':[
  ('back/src/app-api/flux/flux.service.ts:2772–2990',False),
  ('back/src/app-api/extraction/',False),
  ('back/src/app-api/google_ocr/',False),
  ('back/src/app-api/aws/',False),
  ('new worker extraction module',True),
  ('the A1 dispatch registry',False),
 ],
}
