# -*- coding: utf-8 -*-
# A5 — Migrate imageGenerator.  Source: TASK-A5-IMAGE-FAMILY.md, analysis §3.2/§4.1, DELIVERY-PLAN wave 3, PLAN §7 D24.

TASK = {
 'code':'A5','vnum':'3',
 'title':('Migrate <code>imageGenerator</code>','Migrar o <code>imageGenerator</code>'),
 'goal':('Migrate <b><code>imageGenerator</code></b> into the worker over <b>a provider layer written so the next image node can share it</b>.',
         'Migrar o <b><code>imageGenerator</code></b> para o worker sobre <b>uma camada de provedor escrita para que o próximo node de imagem a compartilhe</b>.'),
 'glance':[
  ('crit',('Cost','Custo'),('Breadth, not architecture','Amplitude, não arquitetura'),
   ('<code>imageGenerator</code> is architecturally identical to <code>commandTextNode</code>, in the worker in production the longest. Six provider paths is the real bill.',
    'O <code>imageGenerator</code> é arquiteturalmente idêntico ao <code>commandTextNode</code>, o mais antigo em produção no worker. Seis caminhos de provedor são a conta de verdade.')),
  ('dep',('Depends on','Depende de'),('A1 · A4','A1 · A4'),
   ('A4 must have validated the template first. Nothing else blocks it: <code>imageReaderNode</code>, which waited on D3, left the task — <strong>deprecated, D24</strong>.',
    'A A4 precisa ter validado o template antes. Nada mais a bloqueia: o <code>imageReaderNode</code>, que esperava a D3, saiu da task — <strong>depreciado, D24</strong>.')),
  ('wave',('Wave','Onda'),('Wave 3','Onda 3'),
   ('Second migration of the wave — the first one with a provider surface and real billing to keep identical.',
    'Segunda migração da onda — a primeira com superfície de provedor e cobrança real a manter idêntica.')),
  ('ship',('Shape','Formato'),('One layer, one node — built to be shared','Uma camada, um node — feita para ser compartilhada'),
   ('A module is <strong>already in progress on the dev line</strong> (2026-09-02). Start from it; the parts below are what it has to satisfy before it ships.',
    'Um módulo <strong>já está em andamento na linha de dev</strong> (2026-09-02). Comece por ele; as partes abaixo são o que ele precisa satisfazer antes de subir.')),
 ],
 'lede':(
  '<p><code>imageGenerator</code> resolves a prompt from up to seven fields, interpolates placeholders against the resolved run schema, then dispatches to <strong>one of six provider paths</strong> — <code>openAiService.createImageWithBilling</code>, <code>geminiService.generateImage</code>, <code>replicateService.kandinsky</code> and <code>imageService.{imageCore,sd,textToImage}</code>. Every contract it needs already exists.</p>'
  '<p><strong>Corrected 2026-09-02.</strong> The first draft paired it with <code>imageReaderNode</code> so their overlapping provider paths would be written once. <code>imageReaderNode</code> is <strong>deprecated (D24)</strong>: it leaves this task and <code>A6</code>. An OCR node is wanted in its place and is specified when it is built — not in this epic. What survives from the pairing is the <em>shape</em>: the provider layer is still built to be shared, because an image node that copies provider calls into itself is the drift this epic keeps finding.</p>',
  '<p>O <code>imageGenerator</code> resolve um prompt a partir de até sete campos, interpola placeholders contra o schema resolvido do run e então despacha para <strong>um de seis caminhos de provedor</strong> — <code>openAiService.createImageWithBilling</code>, <code>geminiService.generateImage</code>, <code>replicateService.kandinsky</code> e <code>imageService.{imageCore,sd,textToImage}</code>. Todo contrato de que precisa já existe.</p>'
  '<p><strong>Corrigido em 2026-09-02.</strong> A primeira versão o emparelhava com o <code>imageReaderNode</code> para que os caminhos de provedor sobrepostos fossem escritos uma vez. O <code>imageReaderNode</code> está <strong>depreciado (D24)</strong>: sai desta task e da <code>A6</code>. Um node de OCR é desejado no lugar dele e será especificado quando for construído — não neste épico. O que sobrevive do par é o <em>formato</em>: a camada de provedor continua sendo feita para ser compartilhada, porque um node de imagem que copia chamadas de provedor para dentro de si é a deriva que este épico não para de encontrar.</p>'),
 'blocks':[
  {'k':'label','n':'1','t':('What is in, what left, and why the layer is still shared','O que entra, o que saiu, e por que a camada continua compartilhada')},
  {'k':'table',
   'head':[('','') ,('<code>imageGenerator</code>','<code>imageGenerator</code>'),('<code>imageReaderNode</code> — deprecated (D24)','<code>imageReaderNode</code> — depreciado (D24)')],
   'rows':[
    [{'t':('Where it runs today','Onde roda hoje')},
     {'t':('Inline in the engine','Inline no engine')},
     {'t':('Only in the browser','Só no navegador'),'pill':'no'}],
    [{'t':('Entry points in the code','Pontos de entrada no código')},
     {'t':('Handler <code>imageGeneratorNode()</code> + dispatch case','Handler <code>imageGeneratorNode()</code> + dispatch case')},
     {'t':('<code>ImageReader.tsx</code> calls the providers directly','O <code>ImageReader.tsx</code> chama os provedores direto')}],
    [{'t':('What this task does to it','O que esta task faz com ele')},
     {'t':('Moves execution','Move a execução'),'pill':'ok'},
     {'t':('Nothing — it leaves the migration','Nada — sai da migração'),'pill':'no'}],
    [{'t':('Provider surface','Superfície de provedor')},
     ('Six paths: <code>openAiService.createImageWithBilling</code>, <code>geminiService.generateImage</code>, <code>replicateService.kandinsky</code>, <code>imageService.{imageCore,sd,textToImage}</code>',
      'Seis caminhos: <code>openAiService.createImageWithBilling</code>, <code>geminiService.generateImage</code>, <code>replicateService.kandinsky</code>, <code>imageService.{imageCore,sd,textToImage}</code>'),
     ('OpenAI, Anthropic, Replicate, Ideogram, plus file and upload — the overlap that made the layer shared, and the reason it stays shared for the OCR node that comes later',
      'OpenAI, Anthropic, Replicate, Ideogram, mais arquivo e upload — a sobreposição que fez a camada ser compartilhada, e o motivo de ela continuar assim para o node de OCR que vem depois')],
    [{'t':('Contracts it needs','Contratos de que precisa')},
     ('All three already exist: <code>/worker/charge-tokens</code>, <code>/worker/validate-model-access</code>, <code>/worker/generate-file</code>',
      'Os três já existem: <code>/worker/charge-tokens</code>, <code>/worker/validate-model-access</code>, <code>/worker/generate-file</code>'),
     ('—','—')],
    [{'t':('Blocked on','Bloqueado por')},
     {'t':('Nothing beyond A1 and A4','Nada além da A1 e da A4'),'pill':'ok'},
     {'t':('Out of the epic','Fora do épico'),'pill':'no'}],
   ]},
  {'k':'prose','t':(
    'The spec leaves <strong>no open call of its own</strong> here: providers, models, prompt fields and the billing formula are explicitly out of scope, and provider selection is a behaviour port with no redesign. '
    'The one decision that touched this task is <strong>D24</strong>, and it is settled: <code>imageReaderNode</code> is deprecated and out. Whether Temporal or the provider layer offers a primitive for the OCR node that replaces it is decided by that node&#x27;s developer, when it is built.',
    'A spec <strong>não deixa nenhuma decisão própria em aberto</strong> aqui: provedores, modelos, campos de prompt e a fórmula de cobrança estão explicitamente fora de escopo, e a seleção de provedor é porte de comportamento sem redesenho. '
    'A única decisão que tocou esta task é a <strong>D24</strong>, e está resolvida: o <code>imageReaderNode</code> está depreciado e fora. Se o Temporal ou a camada de provedor oferece uma primitiva para o node de OCR que o substitui é decisão de quem construir esse node, quando for construído.')},
  {'k':'label','n':'2','t':('What the task does, in three parts','O que a task faz, em três partes')},
  {'k':'part','n':'1',
   'title':('The provider layer, built to be shared','A camada de provedor, feita para ser compartilhada'),
   'loc':'worker/src/modules/ai-provider/image/',
   'purpose':('Write each provider path once, outside the node, so the next image node consumes it instead of copying it.',
              'Escrever cada caminho de provedor uma vez, fora do node, para que o próximo node de imagem o consuma em vez de copiá-lo.'),
   'body':('<p>One entry per path, ported from the back&#x27;s services. <strong>Behaviour port only — no redesign of provider selection.</strong> Nothing node-specific lives in the layer: prompt fields, billing and the registry entry belong to the module in Part 2. That boundary is the reason the layer was worth building even after <code>imageReaderNode</code> left — the OCR node that replaces it, and any other image node, starts from this layer rather than from the engine handler.</p>',
           '<p>Uma entrada por caminho, portada dos serviços do back. <strong>Só porte de comportamento — sem redesenhar a seleção de provedor.</strong> Nada específico do node mora na camada: campos de prompt, cobrança e a entrada no registro pertencem ao módulo da Parte 2. Essa fronteira é o motivo de a camada valer a pena mesmo depois de o <code>imageReaderNode</code> sair — o node de OCR que o substitui, e qualquer outro node de imagem, parte desta camada e não do handler do engine.</p>'),
   'ba':(('Six provider paths live inside the engine handler, and a second node reaching the same providers would copy them.',
          'Seis caminhos de provedor vivem dentro do handler do engine, e um segundo node que alcance os mesmos provedores os copiaria.'),
         ('One layer in the worker, consumed by the node, with one place to fix when a provider changes — and one place for the next node to start from.',
          'Uma camada no worker, consumida pelo node, com um único lugar para corrigir quando um provedor mudar — e um único lugar de onde o próximo node parte.'))},
  {'k':'part','n':'2',
   'title':('<code>imageGenerator</code>: prove, flip, delete the twin','<code>imageGenerator</code>: provar, virar, apagar o gêmeo'),
   'loc':'flux.service.ts · worker/src/modules/nodes/image-generator/',
   'purpose':('Move an execution that already works, without changing a single thing a customer can observe.',
              'Mover uma execução que já funciona, sem mudar nada que um cliente possa observar.'),
   'body':('<p>The module — <strong>already in progress on the dev line</strong>; start from it — the registry entry behind the flag, the proof, the flip, then the deletion of the <code>imageGeneratorNode()</code> handler and its dispatch case.</p>'
           '<p><strong>Prompt resolution is the detail that carries the behaviour.</strong> Seven prompt fields — <code>prompt</code>, <code>subject</code>, <code>environment</code>, <code>tone</code>, <code>view</code>, <code>style</code>, <code>negativePrompt</code> — with placeholder interpolation against the resolved run schema. That is the same pattern every migrated node with variable inputs already uses; it is established, not new.</p>',
           '<p>O módulo — <strong>já em andamento na linha de dev</strong>; comece por ele —, a entrada no registro atrás da flag, a prova, a virada, e então a deleção do handler <code>imageGeneratorNode()</code> e do seu caso de dispatch.</p>'
           '<p><strong>A resolução de prompt é o detalhe que carrega o comportamento.</strong> Sete campos de prompt — <code>prompt</code>, <code>subject</code>, <code>environment</code>, <code>tone</code>, <code>view</code>, <code>style</code>, <code>negativePrompt</code> — com interpolação de placeholders contra o schema resolvido do run. É o mesmo padrão que todo node migrado com entradas variáveis já usa; é estabelecido, não novo.</p>'),
   'ba':(('One handler chooses among six providers inside the engine process, and its billing is written from there.',
          'Um handler escolhe entre seis provedores dentro do processo do engine, e a cobrança dele é escrita de lá.'),
         ('An activity chooses among the same six through the shared layer, and bills through <code>/worker/charge-tokens</code> — <strong>with the rows proven to match</strong>.',
          'Uma activity escolhe entre os mesmos seis pela camada compartilhada, e cobra via <code>/worker/charge-tokens</code> — <strong>com as linhas provadas iguais</strong>.'))},
  {'k':'part','n':'3',
   'title':('Timeouts chosen, not inherited','Timeouts escolhidos, não herdados'),
   'loc':'worker/src/modules/temporal/workflows/configs.ts',
   'purpose':('Set each provider&#x27;s timeout deliberately, because image generation is slow enough that the default is a guess.',
              'Definir o timeout de cada provedor deliberadamente, porque geração de imagem é lenta o bastante para o padrão ser um chute.'),
   'body':('<p>The spec is direct about it: image generation is slow enough that the default <code>startToCloseTimeout</code> is <strong>a guess, not a decision</strong>. Set it per provider path, in <code>configs.ts</code>, with the slowest real generation as the input rather than a round number.</p>',
           '<p>A spec é direta: geração de imagem é lenta o bastante para o <code>startToCloseTimeout</code> padrão ser <strong>um chute, não uma decisão</strong>. Defina-o por caminho de provedor, no <code>configs.ts</code>, tendo a geração real mais lenta como entrada, e não um número redondo.</p>'),
   'ba':(('The inline handler waits as long as the provider takes, inside the request, with no stated bound.',
          'O handler inline espera o quanto o provedor levar, dentro da requisição, sem limite declarado.'),
         ('Each provider path has a timeout someone chose, so a slow provider fails as a timeout instead of hanging the run.',
          'Cada caminho de provedor tem um timeout que alguém escolheu, então um provedor lento falha como timeout em vez de travar o run.')),
   'callouts':[
    ('mig',('And the wave&#x27;s latency regression applies here too','E a regressão de latência da onda também vale aqui'),
     ('<p>The node becomes a <strong>blocking round trip</strong> until Wave 5 turns on parallelism (review §4.5, risk <strong>R4</strong>). On an image node the provider call dominates the wall clock, so the added hop is a smaller share of the total than it is for <code>A4</code>&#x27;s <code>reportBuilder</code> — <strong>but measure it and state the number in the PR anyway</strong>, per DELIVERY-PLAN.</p>',
      '<p>O node vira um <strong>round trip bloqueante</strong> até a Onda 5 ligar o paralelismo (review §4.5, risco <strong>R4</strong>). Num node de imagem a chamada ao provedor domina o relógio, então o salto adicional é uma fatia menor do total do que no <code>reportBuilder</code> da <code>A4</code> — <strong>mas meça e informe o número no PR mesmo assim</strong>, conforme o DELIVERY-PLAN.</p>'))]},
 ],
 'verif':[
  (True,('Negative control — one per provider path','Controle negativo — um por caminho de provedor'),
   ('For <strong>each</strong> provider path, break the selection so it falls through to the wrong provider, and confirm a test catches it. <strong>Six paths means six ways to silently call the wrong API</strong>; a suite that only exercises the default path is not protection.',
    'Para <strong>cada</strong> caminho de provedor, quebre a seleção para cair no provedor errado, e confirme que um teste pega. <strong>Seis caminhos significam seis formas de chamar a API errada em silêncio</strong>; uma suíte que só exercita o caminho padrão não é proteção.')),
  (True,('Billing parity against real runs','Paridade de cobrança contra runs reais'),
   ('For the same prompt and model, the <code>token_transactions</code> rows written by the worker must match what the inline path wrote. <strong>Compare against real stored runs</strong>, not synthetic ones.',
    'Para o mesmo prompt e modelo, as linhas de <code>token_transactions</code> escritas pelo worker precisam bater com o que o caminho inline escreveu. <strong>Compare contra runs reais guardados</strong>, não sintéticos.')),
  (True,('Model-access refusal, measured first','Recusa por acesso a modelo, medida antes'),
   ('A model the user is not entitled to must produce the same refusal through <code>/worker/validate-model-access</code> as it does inline. <strong>PLAN §3.3.2</strong> applies: run the check against real entitlements and <strong>drive false refusals to zero</strong> — a user refused a model they own is worse than the defect.',
    'Um modelo a que o usuário não tem direito precisa produzir a mesma recusa via <code>/worker/validate-model-access</code> que produz inline. Vale o <strong>PLAN §3.3.2</strong>: rode a checagem contra direitos reais e <strong>leve as recusas falsas a zero</strong> — um usuário recusado num modelo que ele tem é pior que o defeito.')),
  (False,('One layer, not a copy','Uma camada, não uma cópia'),
   ('Confirm the module carries no provider call of its own — every path goes through <code>ai-provider/image/</code>. The layer is the part of this task the next image node inherits; if it ends up bypassed, that part did not happen.',
    'Confirme que o módulo não carrega chamada própria a provedor — todo caminho passa por <code>ai-provider/image/</code>. A camada é a parte desta task que o próximo node de imagem herda; se ela acabar contornada, essa parte não aconteceu.')),
  (False,('State the latency number','Diga o número da latência'),
   ('<strong>DELIVERY-PLAN, wave 3.</strong> The node becomes a blocking round trip until Wave 5. Measure per provider path and state the numbers in the PR.',
    '<strong>DELIVERY-PLAN, onda 3.</strong> O node vira um round trip bloqueante até a Onda 5. Meça por caminho de provedor e informe os números no PR.')),
 ],
 'done':('<code>imageGenerator</code> satisfies <strong>PLAN §3.4</strong>, its module <strong>consumes the shared provider layer and carries no provider call of its own</strong>, billing matches the inline path on real runs, timeouts were chosen per provider, and <strong><code>imageGeneratorNode()</code> and its dispatch case are deleted</strong>.',
         'O <code>imageGenerator</code> satisfaz o <strong>PLAN §3.4</strong>, o módulo dele <strong>consome a camada de provedor compartilhada e não carrega chamada própria a provedor</strong>, a cobrança bate com o caminho inline em runs reais, os timeouts foram escolhidos por provedor, e <strong>o <code>imageGeneratorNode()</code> e o seu caso de dispatch foram apagados</strong>.'),
 'files':[
  ('worker/src/modules/ai-provider/image/**',True),
  ('worker/src/modules/nodes/image-generator/ (in progress on the dev line)',True),
  ('worker/src/modules/temporal/workflows/configs.ts',False),
  ('back/src/app-api/flux/flux.service.ts (imageGeneratorNode() + its dispatch case)',False),
  ('the A1 dispatch registry',False),
 ],
}
