# -*- coding: utf-8 -*-
# D1 — Developer documentation.
# Source: TASK-D1-DEVELOPER-DOCS.md, PLAN §3.4 point 7, DELIVERY-PLAN wave 3 + §12 re-validation.
# NOTE: task D1 (this page) is not PLAN decision D1 (shared package vs copy-port), which belongs to B2 in wave 4.

TASK = {
 'code':'D1','vnum':'3',
 'title':('Developer documentation','Documentação para desenvolvedor'),
 'goal':('A developer who has never touched the worker can <b>add a node type correctly</b>, and a developer debugging a run can <b>find where it went wrong</b>.',
         'Um desenvolvedor que nunca tocou no worker consegue <b>adicionar um tipo de node corretamente</b>, e um que está depurando um run consegue <b>achar onde deu errado</b>.'),
 'glance':[
  ('crit',('Failure mode','Modo de falha'),('Invisible in review','Invisível na revisão'),
   ('Seven load-bearing layers. Miss one and you get a node that appears to run and does nothing — obvious only at runtime.',
    'Sete camadas estruturais. Esqueça uma e você tem um node que parece rodar e não faz nada — óbvio só em execução.')),
  ('dep',('Depends on','Depende de'),('Nothing','Nada'),
   ('It runs alongside the whole epic: each A-task updates it, this task builds the frame and keeps it honest.',
    'Roda junto com o épico inteiro: cada task do trilho A a atualiza, esta task monta a estrutura e a mantém honesta.')),
  ('wave',('Wave','Onda'),('Wave 3 · continuous','Onda 3 · contínua'),
   ('Each node&#x27;s page is part of <em>its own</em> done — PLAN §3.4 point 7. This task does not backfill them at the end.',
    'A página de cada node faz parte do done <em>dele</em> — PLAN §3.4 ponto 7. Esta task não preenche isso no fim.')),
  ('ship',('Starting point','Ponto de partida'),('An audit, not a blank page','Uma auditoria, não uma página em branco'),
   ('<code>docs/worker/</code> is already populated — and it describes a system <strong>more migrated than the one that runs</strong>.',
    'O <code>docs/worker/</code> já está povoado — e descreve um sistema <strong>mais migrado do que o que roda</strong>.')),
 ],
 'lede':(
  '<p>The registration chain is <strong>seven layers and all of them are load-bearing</strong>: module, enum entry, <code>temporal.module.ts</code>, <code>activities.service.ts</code>, the <code>worker.service.ts</code> binding, the <code>workflows/configs.ts</code> proxy, and the <code>process-single-node.workflow.ts</code> case.</p>'
  '<p>Miss one and you get <strong>a node that appears to run and does nothing</strong>, or a workflow that throws <code>"Node type X not supported"</code> from the default branch. That failure is <em>invisible in review</em> and obvious only at runtime — which is exactly why this is a task and not a README line.</p>',
  '<p>A cadeia de registro tem <strong>sete camadas e todas são estruturais</strong>: módulo, entrada no enum, <code>temporal.module.ts</code>, <code>activities.service.ts</code>, o binding em <code>worker.service.ts</code>, o proxy em <code>workflows/configs.ts</code>, e o case em <code>process-single-node.workflow.ts</code>.</p>'
  '<p>Esqueça uma e você tem <strong>um node que parece rodar e não faz nada</strong>, ou um workflow que lança <code>"Node type X not supported"</code> pelo ramo default. Essa falha é <em>invisível na revisão</em> e óbvia só em execução — que é exatamente o motivo de isto ser uma task, e não uma linha de README.</p>'),
 'blocks':[
  {'k':'label','n':'1','t':('What already exists — and why the first job is an audit','O que já existe — e por que o primeiro trabalho é uma auditoria')},
  {'k':'table',
   'head':[('Where','Onde'),('Pages that exist today','Páginas que existem hoje'),('What the audit has to answer','O que a auditoria precisa responder')],
   'rows':[
    [{'t':('Top level','Nível raiz')},
     ('<code>overview.mdx</code>, <code>development.mdx</code>, <code>environment-variables.mdx</code>',
      '<code>overview.mdx</code>, <code>development.mdx</code>, <code>environment-variables.mdx</code>'),
     ('Does each page describe <strong>production</strong>, a <strong>branch</strong>, or an <strong>intention</strong>?',
      'Cada página descreve a <strong>produção</strong>, um <strong>branch</strong>, ou uma <strong>intenção</strong>?')],
    [{'t':('<code>activities/</code>','<code>activities/</code>')},
     ('<code>charge-tokens</code>, <code>generate-file</code>, <code>validate-model-access</code>, <code>notify-status</code>, <code>generate-execution-logs</code>, <code>get-info-database</code>, <code>node-execution-error</code>',
      '<code>charge-tokens</code>, <code>generate-file</code>, <code>validate-model-access</code>, <code>notify-status</code>, <code>generate-execution-logs</code>, <code>get-info-database</code>, <code>node-execution-error</code>'),
     ('Same question — and note that <code>store-payload</code> and <code>get-payload</code>, the claim check, have <strong>no page at all</strong>.',
      'Mesma pergunta — e note que <code>store-payload</code> e <code>get-payload</code>, o claim check, <strong>não têm página nenhuma</strong>.')],
    [{'t':('<code>node/</code>','<code>node/</code>')},
     ('<code>api-caller</code>, <code>audio-transcriber</code>, <code>counter</code>, <code>display-box</code>, <code>large-memory-dynamic-pod</code>, <code>math-function</code>, <code>mcp</code>, <code>scripting</code>, <code>sql-querier</code>, <code>text-generator</code>',
      '<code>api-caller</code>, <code>audio-transcriber</code>, <code>counter</code>, <code>display-box</code>, <code>large-memory-dynamic-pod</code>, <code>math-function</code>, <code>mcp</code>, <code>scripting</code>, <code>sql-querier</code>, <code>text-generator</code>'),
     {'t':('Documents types the back does not route','Documenta tipos que o back não roteia'),'pill':'no'}],
    [{'t':('<code>workflows/</code>','<code>workflows/</code>')},
     ('<code>process-agent</code>, <code>process-single-node</code>, <code>worker-service</code>','<code>process-agent</code>, <code>process-single-node</code>, <code>worker-service</code>'),
     {'t':('They describe the loop as it runs today; B4 changes that','Descrevem o laço como roda hoje; a B4 muda isso'),'pill':'weak'}],
    [{'t':('<code>worker/pt-br/</code>','<code>worker/pt-br/</code>')},
     ('Only <code>environment-variables.mdx</code>','Só <code>environment-variables.mdx</code>'),
     {'t':('The pt-br side is a stub','O lado pt-br é um esboço'),'pill':'no'}],
   ]},
  {'k':'prose','t':(
    'The spec leaves <strong>no open decision</strong> here — the six subjects, the two languages and the Mintlify convention are all settled. '
    'What it leaves is an <em>obligation</em>: the audit comes first, because a page that confidently describes a system we do not run is worse than a missing page.',
    'A spec <strong>não deixa decisão em aberto</strong> aqui — os seis assuntos, os dois idiomas e a convenção Mintlify estão todos definidos. '
    'O que ela deixa é uma <em>obrigação</em>: a auditoria vem primeiro, porque uma página que descreve com segurança um sistema que não rodamos é pior que uma página ausente.')},
  {'k':'label','n':'2','t':('What the task does: the audit, then six subjects','O que a task faz: a auditoria, e depois seis assuntos')},
  {'k':'part','n':'1',
   'title':('The audit — production, branch, or intention','A auditoria — produção, branch, ou intenção'),
   'loc':'docs/worker/**',
   'purpose':('Establish, page by page, which system each existing page is actually describing.',
              'Estabelecer, página a página, qual sistema cada página existente de fato descreve.'),
   'body':('<p>This is not greenfield. <code>docs/worker/</code> is populated and must be <strong>audited and extended, not recreated</strong>. Two gaps are visible from the listing alone: the <code>node/</code> pages document types the back does not route — <code>sql-querier</code> and <code>audio-transcriber</code> are <code>A3</code>&#x27;s <strong>stranded modules</strong> — and <code>pt-br/</code> contains only <code>environment-variables.mdx</code>.</p>'
           '<p><strong>So the docs already describe a system more migrated than the one that runs.</strong> The spec also lists <code>mcp</code> among them; the re-validation of 2026-08-24 records that <code>mcpNode</code> shipped completely, which moved that page from <em>intention</em> to <em>production</em> without anyone editing it. That is exactly the drift the audit exists to catch — in both directions.</p>',
           '<p>Isto não é terreno vazio. O <code>docs/worker/</code> está povoado e precisa ser <strong>auditado e estendido, não recriado</strong>. Duas lacunas aparecem só na listagem: as páginas de <code>node/</code> documentam tipos que o back não roteia — <code>sql-querier</code> e <code>audio-transcriber</code> são os <strong>módulos encalhados</strong> da <code>A3</code> — e o <code>pt-br/</code> tem só o <code>environment-variables.mdx</code>.</p>'
           '<p><strong>Ou seja: a documentação já descreve um sistema mais migrado do que o que roda.</strong> A spec também lista o <code>mcp</code> entre eles; a re-validação de 2026-08-24 registra que o <code>mcpNode</code> foi entregue por completo, o que moveu aquela página de <em>intenção</em> para <em>produção</em> sem ninguém editá-la. É exatamente esse desvio que a auditoria existe para pegar — nos dois sentidos.</p>'),
   'ba':(('A reader cannot tell whether a page describes production, a branch or a plan — and two of the documented node types are not routed by the back at all.',
          'Um leitor não sabe dizer se uma página descreve produção, um branch ou um plano — e dois dos tipos documentados não são roteados pelo back.'),
         ('Every page states which of the three it describes, and the audit result is <strong>recorded</strong> — that record is part of the definition of done.',
          'Cada página declara qual das três descreve, e o resultado da auditoria fica <strong>registrado</strong> — esse registro faz parte da definição de pronto.')),
   'callouts':[
    ('mig',('Not to be confused with decision D1','Não confundir com a decisão D1'),
     ('<p>This page is <strong>task <code>D1</code></strong> — developer documentation. <strong>Decision <code>D1</code></strong> in <code>PLAN.md</code> §7 is a different thing entirely: shared package versus copy-port for the scheduler and the substitution service. It belongs to <code>B2</code> and it gates <strong>Wave 4</strong>.</p>'
      '<p>Same letter, unrelated subjects. Anyone writing about either should say which one they mean.</p>',
      '<p>Esta página é a <strong>task <code>D1</code></strong> — documentação para desenvolvedor. A <strong>decisão <code>D1</code></strong> no <code>PLAN.md</code> §7 é outra coisa: pacote compartilhado versus porte-cópia para o scheduler e o serviço de substituição. Ela pertence à <code>B2</code> e trava a <strong>Onda 4</strong>.</p>'
      '<p>Mesma letra, assuntos sem relação. Quem escrever sobre qualquer uma delas deve dizer de qual está falando.</p>'))]},
  {'k':'part','n':'2',
   'title':('Node execution lifecycle','Ciclo de vida da execução de um node'),
   'loc':('the published pipeline artifacts', 'os artefatos publicados do pipeline'),
   'purpose':('Give the person debugging a run one page that names every stop along the path.',
              'Dar a quem depura um run uma página que nomeia cada parada do caminho.'),
   'body':('<p>The path a run takes: entry endpoint, <code>node_executions</code>, the Temporal dispatch, <code>fetchNodeRow</code>, execute, <code>persistNodeSuccess</code>, Redis, socket.</p>'
           '<p><strong>This is already drawn.</strong> Reuse the published pipeline diagrams as the diagram source rather than describing them again in prose — a prose copy of a diagram is a second thing to keep in sync.</p>',
           '<p>O caminho que um run percorre: endpoint de entrada, <code>node_executions</code>, o dispatch do Temporal, <code>fetchNodeRow</code>, execução, <code>persistNodeSuccess</code>, Redis, socket.</p>'
           '<p><strong>Isso já está desenhado.</strong> Reaproveite os diagramas publicados do pipeline como fonte, em vez de descrevê-los de novo em prosa — uma cópia em prosa de um diagrama é mais uma coisa para manter sincronizada.</p>'),
   'ba':(('The listing above has no lifecycle page, so the order of the stops is reconstructed from code by whoever needs it, each time.',
          'A listagem acima não tem página de ciclo de vida, então a ordem das paradas é reconstruída a partir do código por quem precisa, toda vez.'),
         ('One page, reusing the published diagrams, <strong>with the commit SHA stated on it</strong> so a reader knows what it was true of.',
          'Uma página, reaproveitando os diagramas publicados, <strong>com o SHA do commit declarado nela</strong>, para o leitor saber de quando aquilo era verdade.'))},
  {'k':'part','n':'3',
   'title':('How to add a node type — the seven layers','Como adicionar um tipo de node — as sete camadas'),
   'loc':('the registration chain', 'a cadeia de registro'),
   'purpose':('Turn the chain into something a person follows while working, with the failure each omission produces.',
              'Transformar a cadeia em algo que a pessoa segue enquanto trabalha, com a falha que cada omissão produz.'),
   'body':('<p>The seven layers, <strong>in order</strong>, each with the failure its omission produces. Written as a <strong>checklist someone can follow while working</strong>, not as an essay — the reader is mid-task with an editor open, not reading for background.</p>'
           '<p>The two failures to name explicitly are the ones the chain actually produces: a node that <em>appears to run and does nothing</em>, and <code>"Node type X not supported"</code> thrown from the default branch of the workflow.</p>',
           '<p>As sete camadas, <strong>em ordem</strong>, cada uma com a falha que sua omissão produz. Escrita como <strong>checklist que alguém segue enquanto trabalha</strong>, não como ensaio — o leitor está no meio da task com o editor aberto, não lendo para se informar.</p>'
           '<p>As duas falhas a nomear explicitamente são as que a cadeia de fato produz: um node que <em>parece rodar e não faz nada</em>, e o <code>"Node type X not supported"</code> lançado pelo ramo default do workflow.</p>'),
   'ba':(('Seven load-bearing steps live in the heads of the people who have done it, and the omission is invisible until runtime.',
          'Sete passos estruturais vivem na cabeça de quem já fez, e a omissão é invisível até a execução.'),
         ('A checklist with the failure attached to each step, tested by someone who had never done it before.',
          'Um checklist com a falha ligada a cada passo, testado por alguém que nunca tinha feito aquilo.'))},
  {'k':'part','n':'4',
   'title':('Callback reference and error taxonomy','Referência de callbacks e taxonomia de erros'),
   'loc':('/worker/* callbacks · NodeError subclasses', 'callbacks /worker/* · subclasses de NodeError'),
   'purpose':('Document the two contracts a node author gets wrong most expensively.',
              'Documentar os dois contratos que o autor de um node erra do jeito mais caro.'),
   'body':('<p><strong>Callbacks:</strong> <code>/worker/store-payload</code>, <code>/worker/get-payload</code>, <code>/worker/validate-model-access</code>, <code>/worker/charge-tokens</code>, <code>/worker/generate-file</code>, plus whatever <code>A7</code> adds. Request, response, <strong>when to use, and when not to</strong>. The first two — the claim check — have no page in the listing above at all.</p>'
           '<p><strong>Errors:</strong> <code>UserConfigError</code>, <code>IntegrationError</code>, <code>ProviderError</code>, <code>TimeoutError</code>, <code>SystemError</code> — which to throw when, and <strong>what each does to retries</strong>. Getting this wrong makes <em>a user&#x27;s typo retry for thirty minutes</em>, which is the sort of defect that looks like an outage and bills like one.</p>',
           '<p><strong>Callbacks:</strong> <code>/worker/store-payload</code>, <code>/worker/get-payload</code>, <code>/worker/validate-model-access</code>, <code>/worker/charge-tokens</code>, <code>/worker/generate-file</code>, mais o que a <code>A7</code> acrescentar. Requisição, resposta, <strong>quando usar e quando não usar</strong>. Os dois primeiros — o claim check — não têm página nenhuma na listagem acima.</p>'
           '<p><strong>Erros:</strong> <code>UserConfigError</code>, <code>IntegrationError</code>, <code>ProviderError</code>, <code>TimeoutError</code>, <code>SystemError</code> — qual lançar quando, e <strong>o que cada um faz com os retries</strong>. Errar isso faz <em>o erro de digitação de um usuário ser retentado por trinta minutos</em>, que é o tipo de defeito que parece queda e cobra como tal.</p>'),
   'ba':(('The claim-check callbacks are undocumented, and the retry consequence of each error class is folklore.',
          'Os callbacks do claim check não estão documentados, e a consequência de retry de cada classe de erro é folclore.'),
         ('Both are reference pages: every callback with its request and response, every error class with what it does to retries.',
          'Os dois viram páginas de referência: cada callback com requisição e resposta, cada classe de erro com o que faz com os retries.'))},
  {'k':'part','n':'5',
   'title':('Persistence contract — and why parallelism is safe','Contrato de persistência — e por que o paralelismo é seguro'),
   'loc':('own-row writes · JSONB merge · claim check above 256 KB', 'escrita na própria linha · merge JSONB · claim check acima de 256 KB'),
   'purpose':('Write down the property the whole parallel plan rests on, before Wave 5 depends on it being understood.',
              'Registrar a propriedade em que todo o plano paralelo se apoia, antes de a Onda 5 depender de ela ser entendida.'),
   'body':('<p>Own-row writes only, the JSONB merge, and the claim check above 256 KB — <strong>and why this is what makes parallelism safe</strong>. A node author who writes into another node&#x27;s row breaks a guarantee they never knew they had, and the failure appears much later, in a parallel run, as a lost update.</p>',
           '<p>Escritas apenas na própria linha, o merge de JSONB, e o claim check acima de 256 KB — <strong>e por que é isso que torna o paralelismo seguro</strong>. Um autor de node que escreve na linha de outro node quebra uma garantia que nem sabia ter, e a falha aparece bem depois, num run paralelo, como uma atualização perdida.</p>'),
   'ba':(('The rule exists in the code and in the review, and a new node module can violate it without anyone noticing until a parallel run.',
          'A regra existe no código e na review, e um módulo de node novo pode violá-la sem ninguém notar até um run paralelo.'),
         ('The rule is stated with its reason, so the person about to break it reads why the shortcut is not one.',
          'A regra está declarada com o motivo, para que quem vai quebrá-la leia por que o atalho não é atalho.'))},
  {'k':'part','n':'6',
   'title':('Running and debugging locally','Rodar e depurar localmente'),
   'loc':'docker-compose.devdb.yaml · Temporal · node_executions',
   'purpose':('Get a developer from “it did not work” to the actual failure without asking someone who already knows.',
              'Levar um desenvolvedor de “não funcionou” até a falha real sem perguntar a quem já sabe.'),
   'body':('<p>The <code>docker-compose.devdb.yaml</code> stack, finding a run in Temporal, reading <code>node_executions</code>, and the worker&#x27;s log surface. <code>development.mdx</code> exists; the listing carries no page for the other three, which are exactly the steps someone needs at the moment a node silently does nothing.</p>',
           '<p>A stack do <code>docker-compose.devdb.yaml</code>, achar um run no Temporal, ler o <code>node_executions</code>, e a superfície de log do worker. O <code>development.mdx</code> existe; a listagem não tem página para os outros três, que são justamente os passos necessários no momento em que um node não faz nada em silêncio.</p>'),
   'ba':(('Debugging a local run is passed on verbally, so the newest person is the slowest at exactly the failure that is hardest to see.',
          'Depurar um run local é passado boca a boca, então a pessoa mais nova é a mais lenta justamente na falha mais difícil de ver.'),
         ('One page: bring the stack up, find the run, read the row, read the log. In <strong>en and pt-br</strong>, like every other page here.',
          'Uma página: subir a stack, achar o run, ler a linha, ler o log. Em <strong>en e pt-br</strong>, como toda página daqui.'))},
 ],
 'verif':[
  (True,('Negative control — and it is a real one here','Controle negativo — e aqui ele é de verdade'),
   ('Have someone who has <strong>not</strong> done it add a trivial node type following <strong>only the page</strong>. If they produce a node that <em>silently does nothing</em>, the page is wrong — that is the failure to look for, because it is the one the seven-layer chain actually produces. <strong>Record what they hit.</strong>',
    'Peça a alguém que <strong>nunca</strong> fez para adicionar um tipo de node trivial seguindo <strong>só a página</strong>. Se essa pessoa produzir um node que <em>não faz nada em silêncio</em>, a página está errada — é essa a falha a procurar, porque é a que a cadeia de sete camadas de fato produz. <strong>Registre onde a pessoa travou.</strong>')),
  (True,('Every reference resolves, and the SHA is stated','Toda referência resolve, e o SHA está declarado'),
   ('Every file path and line reference is checked against the current code at the time of writing, and the <strong>commit SHA is stated on the lifecycle page</strong>. A stale line number in documentation is <strong>worse than none</strong>: it sends the reader to confidently wrong code.',
    'Todo caminho de arquivo e referência de linha é conferido contra o código atual no momento da escrita, e o <strong>SHA do commit é declarado na página de ciclo de vida</strong>. Um número de linha desatualizado na documentação é <strong>pior que nenhum</strong>: manda o leitor para um código errado com confiança.')),
  (False,('The audit is recorded, not just performed','A auditoria fica registrada, não só feita'),
   ('Which existing page described <strong>production</strong> and which did not — written down. The <code>node/</code> pages for the stranded modules are the ones to state explicitly, in both directions.',
    'Qual página existente descrevia a <strong>produção</strong> e qual não descrevia — por escrito. As páginas de <code>node/</code> dos módulos encalhados são as que precisam ser declaradas explicitamente, nos dois sentidos.')),
  (False,('<code>env-vars-sync</code> if any page documents an env var','<code>env-vars-sync</code> se alguma página documentar variável de ambiente'),
   ('The skill keeps <code>.env.example</code>, the audit README and the Mintlify environment pages in step. A documented variable that exists in only one of the three is the next stale page.',
    'A skill mantém <code>.env.example</code>, o README da auditoria e as páginas de ambiente do Mintlify em sincronia. Uma variável documentada que existe em só um dos três é a próxima página desatualizada.')),
 ],
 'done':('The audit is <strong>recorded</strong> (which existing page described production and which did not), the six subjects are covered in <strong>en and pt-br</strong>, <strong>someone unfamiliar has added a node type using only them</strong>, and every reference resolves. Each A-track task adds its own node&#x27;s page as part of PLAN §3.4 point 7 — <strong>this task does not backfill them at the end</strong>.',
         'A auditoria está <strong>registrada</strong> (qual página existente descrevia a produção e qual não), os seis assuntos estão cobertos em <strong>en e pt-br</strong>, <strong>alguém sem familiaridade adicionou um tipo de node usando só eles</strong>, e toda referência resolve. Cada task do trilho A adiciona a página do próprio node como parte do PLAN §3.4 ponto 7 — <strong>esta task não preenche isso no fim</strong>.'),
 'files':[
  ('docs/worker/**',False),
  ('docs/worker/pt-br/**',True),
  ('docs/docs.json (navigation)',False),
  ('the published pipeline artifacts as diagram sources',False),
  ('mintlify-docs-writer agent',False),
  ('env-vars-sync skill',False),
 ],
}
