# -*- coding: utf-8 -*-
# S6 — An egress policy for user-controlled URLs.
# Source: TASK-S6-SSRF-POLICY.md, ARCHITECTURE-REVIEW §3.2, review action #6, PLAN §3.3.2, DELIVERY-PLAN wave 3.

DEC_SHAPE = {
 'k':'decision','id':'S6-a','status':'open','open':True,
 'q':('What shape does the egress policy take — and what does each shape actually refuse?',
      'Que formato tem a política de egresso — e o que cada formato de fato recusa?'),
 'intro':(
  'The spec fixes three properties and one escape hatch: <strong>check the resolved address, not the string</strong>; block loopback, link-local (including '
  '<code>169.254.169.254</code>), private ranges and unique-local by default; <strong>re-check on redirect</strong>; and keep a per-organisation allowlist so a policy '
  'with no exception path does not get disabled wholesale. It does <em>not</em> fix the shape. That is this decision, and it is the one that decides what stops working — '
  'so <strong>PLAN §3.3.2 applies with full force</strong>: this rule refuses network traffic, which is the most disruptive kind of refusal in the product.',
  'A spec fixa três propriedades e uma válvula de escape: <strong>checar o endereço resolvido, não a string</strong>; bloquear loopback, link-local (incluindo '
  '<code>169.254.169.254</code>), faixas privadas e unique-local por padrão; <strong>rechecar no redirect</strong>; e manter uma allowlist por organização, para que uma política '
  'sem caminho de exceção não seja desligada por inteiro. Ela <em>não</em> fixa o formato. É esta a decisão, e é ela que define o que deixa de funcionar — '
  'então <strong>o PLAN §3.3.2 vale com força total</strong>: esta regra recusa tráfego de rede, o tipo de recusa mais disruptivo do produto.'),
 'opts':[
  {'ltr':'A','pick':True,'name':('Deny-list on the resolved address','Deny-list sobre o endereço resolvido'),
   'tag':('the policy','a política'),
   'how':('Resolve the hostname, check <strong>every</strong> resolved address against the blocked ranges, refuse if any matches, and repeat on each redirect hop. An organisation can allow a specific internal host.',
          'Resolver o hostname, checar <strong>todos</strong> os endereços resolvidos contra as faixas bloqueadas, recusar se algum casar, e repetir a cada salto de redirect. Uma organização pode liberar um host interno específico.'),
   'pros':[('Refuses the textbook case and almost nothing else — the smallest refusal surface, which is what PLAN §3.3.2 asks for',
            'Recusa o caso clássico e quase nada mais — a menor superfície de recusa, que é o que o PLAN §3.3.2 pede'),
           ('One rule at the fetch layer both repos share, rather than a check per node that the next node forgets',
            'Uma regra na camada de fetch que os dois repos compartilham, em vez de uma checagem por node que o próximo node esquece'),
           ('The escape hatch exists, so the first legitimate internal endpoint does not become a reason to turn the policy off',
            'A válvula de escape existe, então o primeiro endpoint interno legítimo não vira motivo para desligar a política')],
   'cons':[('It is check-then-connect: between the check and the socket the name can resolve to something else — see option D',
            'É checar-depois-conectar: entre a checagem e o socket o nome pode resolver para outra coisa — veja a opção D'),
           ('A customer&#x27;s genuinely internal endpoint is refused until someone adds it to the allowlist',
            'Um endpoint realmente interno de um cliente é recusado até alguém adicioná-lo à allowlist')],
   'cost':[('lo',('Client effort: <b>none, unless they fetch an internal host</b>','Esforço do cliente: <b>nenhum, salvo se buscar host interno</b>')),
           ('',('Ours: <b>one fetch layer, in two repos</b>','Nosso: <b>uma camada de fetch, em dois repos</b>'))]},
  {'ltr':'B','no':True,'name':('Allowlist per tenant — deny everything else','Allowlist por tenant — negar todo o resto'),
   'tag':('not viable as a default','inviável como padrão'),
   'how':('Each organisation declares the hosts its nodes may fetch. Anything not declared is refused, private or public.',
          'Cada organização declara os hosts que seus nodes podem buscar. Qualquer coisa não declarada é recusada, privada ou pública.'),
   'pros':[('Strongest containment — an unknown host is unreachable even if the range check has a hole',
            'Contenção mais forte — um host desconhecido é inalcançável mesmo se a checagem de faixas tiver falha'),
           ('Makes the blast radius of a tampered node configuration very small','Torna muito pequeno o raio de impacto de uma configuração de node adulterada')],
   'cons':[('It refuses the product&#x27;s normal use: a crawler, an api-caller and a summariser exist to fetch a URL the user just typed',
            'Recusa o uso normal do produto: um crawler, um api-caller e um sumarizador existem para buscar a URL que o usuário acabou de digitar'),
           ('The false-refusal count starts near 100%, and PLAN §3.3.2 says drive it to zero','A contagem de recusas falsas começa perto de 100%, e o PLAN §3.3.2 manda levá-la a zero'),
           ('Every new URL becomes a support request','Cada URL nova vira um chamado de suporte')],
   'cost':[('hi',('Client effort: <b>declare every host first</b>','Esforço do cliente: <b>declarar cada host antes</b>')),
           ('hi',('Ours: <b>a registration UI, and the tickets</b>','Nosso: <b>uma UI de cadastro, e os chamados</b>'))]},
  {'ltr':'C','name':('A central egress proxy that enforces the policy','Um proxy de egresso central que aplica a política'),
   'tag':('infra option','opção de infra'),
   'how':('Both repos fetch through a proxy that owns the rule. The application stops deciding; the network position enforces it.',
          'Os dois repos buscam através de um proxy que é dono da regra. A aplicação deixa de decidir; a posição de rede aplica.'),
   'pros':[('One enforcement point for back, worker and anything added later — a new fetcher cannot bypass it by picking a different HTTP client',
            'Um ponto de aplicação para back, worker e o que vier depois — um buscador novo não escapa escolhendo outro cliente HTTP'),
           ('The report-only cycle produces a single log, in one place, instead of two repos&#x27; worth',
            'O ciclo somente-relatório produz um log único, num lugar só, em vez de dois repos')],
   'cons':[('Infra work with a deploy per environment, and it becomes a hard dependency on the run path — if the proxy is down, every fetch is',
            'Trabalho de infra com deploy por ambiente, e vira dependência dura no caminho do run — se o proxy cair, toda busca cai'),
           ('It does not by itself answer the rebinding question, which still lives in whoever resolves the name',
            'Não responde sozinho à questão de rebinding, que continua em quem resolve o nome')],
   'cost':[('lo',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('hi',('Ours: <b>infra, per environment, on the run path</b>','Nosso: <b>infra, por ambiente, no caminho do run</b>'))]},
  {'ltr':'D','pick':True,'name':('Resolve, pin, connect — rebinding-safe by construction','Resolver, fixar, conectar — à prova de rebinding por construção'),
   'tag':('the mechanism','o mecanismo'),
   'how':('The resolver returns the addresses, the policy checks them, and the connection is made to <strong>the address that was checked</strong> rather than re-resolving the name. Every redirect hop repeats it.',
          'O resolvedor devolve os endereços, a política os checa, e a conexão é feita <strong>ao endereço que foi checado</strong>, sem reresolver o nome. Cada salto de redirect repete isso.'),
   'pros':[('Closes the gap A leaves open: the string, the DNS answer and the socket cannot disagree',
            'Fecha a brecha que a A deixa aberta: a string, a resposta de DNS e o socket não podem discordar'),
           ('It is what makes “check the resolved address” actually true rather than nearly true',
            'É o que torna “checar o endereço resolvido” de fato verdadeiro, e não quase verdadeiro')],
   'cons':[('An HTTP-client-level change in both repos — a custom agent or resolver, which some clients make awkward',
            'Mudança em nível de cliente HTTP nos dois repos — um agent ou resolvedor próprio, o que alguns clientes dificultam'),
           ('On its own it is not a policy: it is the mechanism a policy needs','Sozinho não é uma política: é o mecanismo de que uma política precisa')],
   'cost':[('lo',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('',('Ours: <b>a resolver in two HTTP layers</b>','Nosso: <b>um resolvedor em duas camadas HTTP</b>'))]},
 ],
 'rec':(
  '<p><strong>A as the policy, D as its mechanism.</strong> They are not competing options — A decides what is refused and D decides that the refusal cannot be walked around between the check and the connection. Shipping A without D produces a control that reads correct and is defeated by a DNS record the attacker owns.</p>'
  '<p><strong>C only if the network-position decision below puts the worker behind a proxy anyway.</strong> As a standalone project it buys one enforcement point at the price of a new single point of failure on the run path; as a by-product of a restricted subnet it is nearly free.</p>'
  '<p><strong>B is not viable as a default</strong> and is listed so the option is refused on the record rather than in a corridor: fetching a URL the user just typed is the product. Keep its shape for the per-organisation allowlist, where it belongs — as an <em>exception</em> path, not the rule.</p>'
  '<p>Whatever is chosen, the measurement is the same and it is not optional: <strong>sample the real URLs stored in node configurations</strong>, classify each as <em>would still work</em> or <em>would now be blocked</em>, drive the second to zero, and treat anything unresolvable as <strong>unverifiable, not blocked</strong>. Then run report-only for a full cycle before enforcing.</p>',
  '<p><strong>A como política, D como mecanismo.</strong> Não são opções concorrentes — a A decide o que é recusado e a D garante que a recusa não seja contornada entre a checagem e a conexão. Entregar A sem D produz um controle que parece correto e é derrotado por um registro de DNS que o atacante controla.</p>'
  '<p><strong>C só se a decisão de posição de rede abaixo já colocar o worker atrás de um proxy.</strong> Como projeto isolado, compra um ponto de aplicação ao preço de um novo ponto único de falha no caminho do run; como subproduto de uma subnet restrita, é quase de graça.</p>'
  '<p><strong>B não é viável como padrão</strong> e está listada para ser recusada no registro, e não no corredor: buscar a URL que o usuário acabou de digitar é o produto. Guarde o formato dela para a allowlist por organização, onde ele cabe — como caminho de <em>exceção</em>, não como regra.</p>'
  '<p>Qualquer que seja a escolha, a medição é a mesma e não é opcional: <strong>amostre as URLs reais guardadas nas configurações dos nodes</strong>, classifique cada uma como <em>continuaria funcionando</em> ou <em>passaria a ser bloqueada</em>, leve a segunda a zero, e trate o que não for resolvível como <strong>não verificável, não como bloqueado</strong>. Depois rode em modo somente-relatório por um ciclo inteiro antes de impor.</p>'),
 'who':[('Engineering','Engenharia'),('Infra owns C','Infra decide a C'),('Security signs off','Segurança aprova')],
}

DEC_POSITION = {
 'k':'decision','id':'S6-b','status':'open',
 'q':('Where does the worker sit, and what is it allowed to reach?',
      'Onde o worker fica, e o que ele pode alcançar?'),
 'intro':(
  'The spec makes this an explicit deliverable, not a background assumption: <strong>“a decision on the worker&#x27;s network position, written down: which subnet, which instance role, what it can reach.”</strong> '
  'It is what decides whether relocating the fetchers is an improvement or a regression. The worker holds the <strong>database password and the integrations encryption key</strong>, and review §3.2 says whether the move is better or worse '
  '<em>depends entirely</em> on its subnet and its instance role. The three options below are not preferences — <strong>they are the three possible answers</strong>, and the first job is to find out which one is true today.',
  'A spec faz disto uma entrega explícita, não uma suposição de fundo: <strong>“uma decisão sobre a posição de rede do worker, registrada: qual subnet, qual role de instância, o que ele alcança.”</strong> '
  'É o que decide se relocar os buscadores é melhora ou regressão. O worker guarda a <strong>senha do banco e a chave de criptografia das integrações</strong>, e a review §3.2 diz que se a mudança é melhor ou pior '
  '<em>depende inteiramente</em> da subnet e do role de instância dele. As três opções abaixo não são preferências — <strong>são as três respostas possíveis</strong>, e o primeiro trabalho é descobrir qual é a verdadeira hoje.'),
 'opts':[
  {'ltr':'A','pick':True,'name':('The worker reaches <em>less</em> than the API','O worker alcança <em>menos</em> que a API'),
   'tag':('aim for this','mirar nisto'),
   'how':('A subnet whose egress is limited to what the activities actually need, and an instance role scoped to the worker&#x27;s own resources. The relocation is then a documented security improvement — and the spec says to state it as one.',
          'Uma subnet cujo egresso se limita ao que as activities de fato precisam, e um role de instância restrito aos próprios recursos do worker. A relocação vira, então, uma melhoria de segurança documentada — e a spec manda declará-la como tal.'),
   'pros':[('Turns an unknown into a stated improvement: a compromised fetcher reaches less than it does today',
            'Transforma um desconhecido em melhoria declarada: um buscador comprometido alcança menos do que hoje'),
           ('Writes the sentence review §3.2 says the tasks currently lack','Escreve a frase que a review §3.2 diz faltar nas tasks'),
           ('Defence in depth: a bug in the code-level policy is no longer a full SSRF from a privileged host',
            'Defesa em profundidade: um bug na política em código deixa de ser um SSRF completo a partir de um host privilegiado')],
   'cons':[('Someone has to enumerate what the activities legitimately reach — providers, Temporal, the API, storage — and keep the list current',
            'Alguém precisa enumerar o que as activities legitimamente alcançam — provedores, Temporal, a API, storage — e manter a lista atual'),
           ('A missing entry looks like a node failure rather than a network refusal, unless the error says which it is',
            'Uma entrada faltando parece falha de node em vez de recusa de rede, a menos que o erro diga qual é')],
   'cost':[('lo',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('hi',('Ours: <b>enumerate egress, and keep it current</b>','Nosso: <b>enumerar o egresso, e mantê-lo atual</b>'))]},
  {'ltr':'B','name':('The worker reaches the same as the API','O worker alcança o mesmo que a API'),
   'how':('No network change. The code-level policy from S6-a is the only control, and the relocation is risk-neutral by construction.',
          'Sem mudança de rede. A política em código da S6-a é o único controle, e a relocação é neutra em risco por construção.'),
   'pros':[('Nothing to deploy — the move genuinely changes nothing about the exposure',
            'Nada a implantar — a mudança de fato não altera a exposição'),
           ('Honest and quick to write down, which is most of what this decision is for',
            'Honesto e rápido de registrar, que é a maior parte do propósito desta decisão')],
   'cons':[('The worker still holds the database password and the integrations key with unrestricted egress, so a policy bug is a privileged SSRF',
            'O worker continua guardando a senha do banco e a chave das integrações com egresso irrestrito, então um bug na política é um SSRF privilegiado'),
           ('One control, no depth: the code-level policy has to be right the first time','Um controle, sem profundidade: a política em código precisa estar certa de primeira')],
   'cost':[('lo',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('hi',('Ours: <b>a policy bug becomes a privileged SSRF</b>','Nosso: <b>um bug na política vira SSRF privilegiado</b>'))]},
  {'ltr':'C','name':('The worker reaches <em>more</em> than the API','O worker alcança <em>mais</em> que a API'),
   'tag':('compensate first','compensar antes'),
   'how':('The spec&#x27;s own branch: the move needs <strong>compensating controls before it ships</strong> — scope the instance role, restrict the subnet, or hold the relocated fetchers until the network position changes.',
          'O ramo previsto pela própria spec: a mudança precisa de <strong>controles compensatórios antes de entrar</strong> — restringir o role de instância, restringir a subnet, ou segurar os buscadores relocados até a posição de rede mudar.'),
   'pros':[('The one branch where relocating without changes would be a regression, caught before it ships rather than after',
            'O único ramo em que relocar sem mudanças seria regressão, pego antes de entrar e não depois'),
           ('It gives A6 and A8 a concrete precondition instead of a vague worry','Dá à A6 e à A8 uma precondição concreta em vez de uma preocupação vaga')],
   'cons':[('The nine front-driven types and the extraction activity wait on infra work',
            'Os nove tipos só-front e a activity de extração ficam esperando trabalho de infra'),
           ('The waiting is invisible unless someone states it as a dependency on the wave plan',
            'A espera é invisível a menos que alguém a declare como dependência no plano da onda')],
   'cost':[('hi',('Client impact: <b>headless execution waits</b>','Impacto no cliente: <b>execução sem interface espera</b>')),
           ('hi',('Ours: <b>infra work before A6 and A8 ship</b>','Nosso: <b>trabalho de infra antes de A6 e A8 entrarem</b>'))]},
 ],
 'rec':(
  '<p><strong>Look it up before the first relocated fetcher ships, and write the answer into the task.</strong> This is the rare decision whose first half is a fact, not a preference: compare what the API can reach with what the worker can reach, today, in each environment.</p>'
  '<p><strong>Aim for A.</strong> It is the only branch where the move makes things better rather than merely not worse, and it is the branch that lets the epic say out loud that migrating a URL fetcher into the worker was a security improvement.</p>'
  '<p>If the answer is <strong>B</strong>, say so plainly and accept that S6-a is the only control. If it is <strong>C</strong>, then <code>A6</code> and <code>A8</code> do not ship their fetchers until the controls exist — which is exactly what both tasks already say, and this is where that sentence gets its meaning.</p>',
  '<p><strong>Descubra antes de o primeiro buscador relocado entrar, e escreva a resposta na task.</strong> Esta é a rara decisão cuja primeira metade é um fato, não uma preferência: compare o que a API alcança com o que o worker alcança, hoje, em cada ambiente.</p>'
  '<p><strong>Mire na A.</strong> É o único ramo em que a mudança torna as coisas melhores em vez de apenas não piores, e é o ramo que permite ao épico dizer em voz alta que mover um buscador de URL para o worker foi uma melhoria de segurança.</p>'
  '<p>Se a resposta for <strong>B</strong>, diga isso com todas as letras e aceite que a S6-a é o único controle. Se for <strong>C</strong>, então a <code>A6</code> e a <code>A8</code> não entregam seus buscadores até os controles existirem — que é exatamente o que as duas tasks já dizem, e é aqui que essa frase ganha sentido.</p>'),
 'who':[('Infra — owns the subnet and the instance role','Infra — dona da subnet e do role de instância'),
        ('Engineering','Engenharia'),('Security signs off','Segurança aprova')],
}

TASK = {
 'code':'S6','vnum':'4',
 'title':('An egress policy for user-controlled URLs','Uma política de egresso para URLs controladas pelo usuário'),
 'goal':('Decide what a node is allowed to fetch <b>before</b> moving the code that fetches it into a host with more privileges.',
         'Decidir o que um node pode buscar <b>antes</b> de mover o código que busca para um host com mais privilégios.'),
 'glance':[
  ('crit',('Severity','Severidade'),('High','Alta'),
   ('Review §3.2. A node pointing at the cloud metadata endpoint or an internal hostname is the textbook case, and nothing checks it.',
    'Review §3.2. Um node apontando para o endpoint de metadados da nuvem ou um hostname interno é o caso clássico, e nada checa isso.')),
  ('dep',('Depends on','Depende de'),('Nothing — but it is not standalone','Nada — mas não é isolada'),
   ('It must be decided <strong>as part of</strong> <code>A6</code> and <code>A8</code>, not after them.',
    'Precisa ser decidida <strong>como parte</strong> da <code>A6</code> e da <code>A8</code>, não depois delas.')),
  ('wave',('Wave','Onda'),('Wave 3','Onda 3'),
   ('The timing is the finding: the decision is made <em>with</em> the move, because the move is what changes the risk.',
    'O timing é o achado: a decisão é tomada <em>junto</em> com a mudança, porque é a mudança que altera o risco.')),
  ('ship',('Watch-out','Cuidado'),('It refuses network traffic','Recusa tráfego de rede'),
   ('The most disruptive kind of refusal there is. <strong>PLAN §3.3.2</strong> is not a formality here — it is the gate.',
    'O tipo de recusa mais disruptivo que existe. O <strong>PLAN §3.3.2</strong> não é formalidade aqui — é o gate.')),
 ],
 'lede':(
  '<p><code>/downloader?url=</code> takes a user URL (<code>downloader.controller.ts:34</code>), and the scraper, api-caller and crawling paths take user URLs too. Searching those modules for private-range or metadata blocking — <code>127.0.0.1</code>, <code>169.254</code>, <code>localhost</code>, <code>isPrivate</code> — returns <strong>nothing</strong>.</p>'
  '<p>This is <strong>pre-existing; the epic did not create it</strong>. But the epic <em>moves these callers into the worker</em>, which sits in a different network position while holding the database password and the integrations encryption key — and today the tasks that do the moving say nothing about it.</p>',
  '<p>O <code>/downloader?url=</code> recebe uma URL do usuário (<code>downloader.controller.ts:34</code>), e os caminhos de scraper, api-caller e crawling também recebem URLs do usuário. Buscar nesses módulos por bloqueio de faixa privada ou de metadados — <code>127.0.0.1</code>, <code>169.254</code>, <code>localhost</code>, <code>isPrivate</code> — não retorna <strong>nada</strong>.</p>'
  '<p>Isto é <strong>pré-existente; o épico não criou</strong>. Mas o épico <em>move esses chamadores para o worker</em>, que fica em outra posição de rede enquanto guarda a senha do banco e a chave de criptografia das integrações — e hoje as tasks que fazem a mudança não dizem nada sobre isso.</p>'),
 'blocks':[
  {'k':'label','n':'1','t':('Four things a policy has to get right','Quatro coisas que uma política precisa acertar')},
  {'k':'table',
   'head':[('What the policy must do','O que a política precisa fazer'),('The bypass it closes','O desvio que fecha'),('If it is skipped','Se for pulado')],
   'rows':[
    [{'t':('Check the <strong>resolved address</strong>, not the string','Checar o <strong>endereço resolvido</strong>, não a string')},
     ('A hostname the attacker controls that resolves to a private address','Um hostname controlado pelo atacante que resolve para um endereço privado'),
     {'t':('Defeated by one DNS record','Derrotada por um registro de DNS'),'pill':'no'}],
    [{'t':('Block loopback, link-local, private and unique-local by default','Bloquear loopback, link-local, privadas e unique-local por padrão')},
     ('<code>169.254.169.254</code> — the cloud metadata endpoint — and internal hostnames','<code>169.254.169.254</code> — o endpoint de metadados da nuvem — e hostnames internos'),
     {'t':('The textbook SSRF','O SSRF clássico'),'pill':'no'}],
    [{'t':('Re-check on <strong>every redirect hop</strong>','Rechecar em <strong>cada salto de redirect</strong>')},
     ('A permitted host that <code>302</code>s to a blocked address','Um host permitido que faz <code>302</code> para um endereço bloqueado'),
     {'t':('The standard bypass','O desvio padrão'),'pill':'no'}],
    [{'t':('Keep a per-organisation allowlist','Manter uma allowlist por organização')},
     ('Not an attack — the failure here is ours','Não é ataque — a falha aqui é nossa'),
     {'t':('The policy gets disabled wholesale','A política é desligada por inteiro'),'pill':'weak'}],
   ]},
  {'k':'prose','t':(
    'The list above is what the spec settles. What it deliberately leaves open is the <strong>shape</strong> of the policy and the <strong>worker&#x27;s network position</strong> — '
    'and the second one decides whether this whole epic is moving URL fetchers into a safer place or a more dangerous one. Both are below, with what each option refuses and what it lets through.',
    'A lista acima é o que a spec resolve. O que ela deixa em aberto de propósito é o <strong>formato</strong> da política e a <strong>posição de rede do worker</strong> — '
    'e a segunda decide se este épico inteiro está movendo buscadores de URL para um lugar mais seguro ou mais perigoso. As duas estão abaixo, com o que cada opção recusa e o que deixa passar.')},
  {'k':'label','n':'2','t':('The decisions this task needs','As decisões que esta task precisa')},
  DEC_SHAPE, DEC_POSITION,
  {'k':'label','n':'3','t':('What the task does, in three parts','O que a task faz, em três partes')},
  {'k':'part','n':'1',
   'title':('One policy, at the fetch layer both repos share','Uma política, na camada de fetch que os dois repos compartilham'),
   'loc':('downloader.controller.ts:34 · app-api/{scraper,api_call}/ · worker HTTP layer', 'downloader.controller.ts:34 · app-api/{scraper,api_call}/ · camada HTTP do worker'),
   'purpose':('Put the rule where every fetch passes, so a node cannot opt out of it by being written later.',
              'Colocar a regra onde toda busca passa, para que um node não escape dela por ter sido escrito depois.'),
   'body':('<p>Not per node — <strong>per fetch layer</strong>. The fetchers this epic relocates are <code>webCrawling</code>, <code>webAmazon</code>, <code>secApiNode</code>, <code>usCensusNode</code>, <code>documentSummarizer</code> and <code>fileSave</code> (via <code>/downloader</code>), plus <code>apiCaller</code>, which is already in the worker. A per-node check would have to be added seven times and remembered an eighth.</p>',
           '<p>Não por node — <strong>por camada de fetch</strong>. Os buscadores que este épico reloca são <code>webCrawling</code>, <code>webAmazon</code>, <code>secApiNode</code>, <code>usCensusNode</code>, <code>documentSummarizer</code> e <code>fileSave</code> (via <code>/downloader</code>), mais o <code>apiCaller</code>, que já está no worker. Uma checagem por node teria de ser adicionada sete vezes e lembrada na oitava.</p>'),
   'ba':(('Every one of those paths accepts a user URL and connects to it. Nothing resolves it, nothing classifies the address, nothing looks at the redirect.',
          'Cada um desses caminhos aceita uma URL do usuário e se conecta a ela. Nada resolve, nada classifica o endereço, nada olha o redirect.'),
         ('One policy object, consulted by the shared fetch layer in both repos, on the first request and on every redirect hop.',
          'Um objeto de política, consultado pela camada de fetch compartilhada nos dois repos, na primeira requisição e em cada salto de redirect.'))},
  {'k':'part','n':'2',
   'title':('Measure, then report-only, then enforce','Medir, depois somente-relatório, depois impor'),
   'loc':'PLAN §3.3.2',
   'purpose':('Make sure the rule refuses only what it is supposed to refuse, before it is allowed to refuse anything.',
              'Garantir que a regra recuse só o que deve recusar, antes de ela poder recusar qualquer coisa.'),
   'body':('<p>This rule rejects <strong>network traffic</strong>, which is the most disruptive kind of refusal in the product: the customer does not see “blocked”, they see a node that stopped working. So the sequence is fixed:</p>',
           '<p>Esta regra rejeita <strong>tráfego de rede</strong>, o tipo de recusa mais disruptivo do produto: o cliente não vê “bloqueado”, vê um node que parou de funcionar. Então a sequência é fixa:</p>'),
   'list':[
    ('<strong>Sample the real URLs stored in node configurations</strong>, and classify each as <em>would still work</em> or <em>would now be blocked</em>.',
     '<strong>Amostrar as URLs reais guardadas nas configurações dos nodes</strong>, e classificar cada uma como <em>continuaria funcionando</em> ou <em>passaria a ser bloqueada</em>.'),
    ('<strong>Drive the second count to zero</strong> before enabling anything. A legitimate URL refused is worse than the defect being fixed.',
     '<strong>Levar a segunda contagem a zero</strong> antes de habilitar qualquer coisa. Uma URL legítima recusada é pior que o defeito sendo corrigido.'),
    ('Anything unresolvable is <strong>unverifiable, not blocked</strong> — report it as unknown rather than counting it as a pass.',
     'O que não for resolvível é <strong>não verificável, não bloqueado</strong> — reporte como desconhecido em vez de contar como aprovado.'),
    ('<strong>Report-only for a full cycle</strong>: log what would be blocked, and only then enforce.',
     '<strong>Somente-relatório por um ciclo inteiro</strong>: registre o que seria bloqueado, e só então imponha.'),
   ],
   'body2':('<p>Auditing every existing customer URL is explicitly <strong>out of scope</strong>. This is the measurement, not a remediation project.</p>',
            '<p>Auditar todas as URLs existentes de clientes está explicitamente <strong>fora de escopo</strong>. Isto é a medição, não um projeto de remediação.</p>'),
   'ba':(('No rule, so no false refusals — and no true ones either. Every internal address is reachable from a node configuration.',
          'Sem regra, então sem recusas falsas — e sem verdadeiras também. Todo endereço interno é alcançável a partir da configuração de um node.'),
         ('A rule that ran for a full cycle in report-only mode with a <strong>known</strong> false-refusal count of zero before it started refusing anything.',
          'Uma regra que rodou um ciclo inteiro em modo somente-relatório com contagem <strong>conhecida</strong> de recusas falsas igual a zero antes de começar a recusar qualquer coisa.'))},
  {'k':'part','n':'3',
   'title':('The worker&#x27;s network position, written down','A posição de rede do worker, registrada'),
   'loc':('infra network/subnet definitions', 'definições de rede/subnet na infra'),
   'purpose':('Answer the question the review says the moving tasks currently do not even ask.',
              'Responder a pergunta que a review diz que as tasks que fazem a mudança hoje nem fazem.'),
   'body':('<p>Which subnet, which instance role, what it can reach. <strong>If the worker can reach less than the API, moving these fetchers is a security improvement and should be stated as one.</strong> If it can reach more, the move needs compensating controls before it ships.</p>'
           '<p>That is decision <strong>S6-b</strong> above. Its first half is a lookup, not an opinion — and it has to happen before <code>A6</code> and <code>A8</code> relocate a fetcher.</p>',
           '<p>Qual subnet, qual role de instância, o que ele alcança. <strong>Se o worker alcança menos que a API, mover esses buscadores é melhoria de segurança e deve ser declarado como tal.</strong> Se alcança mais, a mudança precisa de controles compensatórios antes de entrar.</p>'
           '<p>Essa é a decisão <strong>S6-b</strong> acima. A primeira metade dela é uma consulta, não uma opinião — e precisa acontecer antes de a <code>A6</code> e a <code>A8</code> relocarem um buscador.</p>'),
   'ba':(('Nobody can say whether the worker reaches more or less than the API, so nobody can say whether the migration improves or worsens this exposure.',
          'Ninguém sabe dizer se o worker alcança mais ou menos que a API, então ninguém sabe dizer se a migração melhora ou piora esta exposição.'),
         ('The position is documented per environment, and the epic can state which of the two it did — <strong>with the answer, not with a hope</strong>.',
          'A posição está documentada por ambiente, e o épico pode dizer qual das duas fez — <strong>com a resposta, não com uma esperança</strong>.')),
   'callouts':[
    ('mig',('An allowlist with no exception path is a policy that gets turned off','Uma allowlist sem caminho de exceção é uma política que acaba desligada'),
     ('<p>The per-organisation escape hatch is not a weakening of the policy — it is what keeps the policy alive. <strong>Some customer will have a legitimate internal endpoint</strong>, and a control with no way to say yes to it gets disabled wholesale the first time it costs someone a run.</p>',
      '<p>A válvula de escape por organização não enfraquece a política — é o que a mantém viva. <strong>Algum cliente terá um endpoint interno legítimo</strong>, e um controle sem como dizer sim a ele é desligado por inteiro na primeira vez que custar um run a alguém.</p>'))]},
 ],
 'verif':[
  (True,('Negative control — demonstrate the finding first','Controle negativo — demonstrar o achado primeiro'),
   ('Point an <code>apiCaller</code> node at <code>169.254.169.254</code> and confirm <strong>it currently returns metadata</strong>. That is the finding: demonstrate it in a controlled environment before fixing it, and <strong>keep the test</strong>.',
    'Aponte um node <code>apiCaller</code> para <code>169.254.169.254</code> e confirme que <strong>hoje ele retorna metadados</strong>. Esse é o achado: demonstre num ambiente controlado antes de corrigir, e <strong>mantenha o teste</strong>.')),
  (True,('Redirect bypass','Desvio por redirect'),
   ('A permitted host that <code>302</code>s to a blocked address must be <strong>refused at the redirect</strong>, not followed because the first hop looked clean.',
    'Um host permitido que faz <code>302</code> para um endereço bloqueado precisa ser <strong>recusado no redirect</strong>, e não seguido porque o primeiro salto parecia limpo.')),
  (True,('Measure before refusing','Medir antes de recusar'),
   ('<strong>PLAN §3.3.2.</strong> Sample the real URLs stored in node configurations, classify each as <em>would still work</em> or <em>would now be blocked</em>, and <strong>drive the second to zero</strong> before enabling. Anything unresolvable is <strong>unverifiable, not blocked</strong>.',
    '<strong>PLAN §3.3.2.</strong> Amostre as URLs reais guardadas nas configurações dos nodes, classifique cada uma como <em>continuaria funcionando</em> ou <em>passaria a ser bloqueada</em>, e <strong>leve a segunda a zero</strong> antes de habilitar. O que não for resolvível é <strong>não verificável, não bloqueado</strong>.')),
  (True,('Report-only for a full cycle','Somente-relatório por um ciclo inteiro'),
   ('Enable in report-only mode first and log what <em>would</em> be blocked, for a full cycle, before enforcing. The wave&#x27;s exit gate names this explicitly.',
    'Habilite primeiro em modo somente-relatório e registre o que <em>seria</em> bloqueado, por um ciclo inteiro, antes de impor. O gate de saída da onda nomeia isso explicitamente.')),
  (False,('The rebinding case, if D is taken','O caso de rebinding, se a D for adotada'),
   ('A name that passes the check and then resolves to a private address on the second lookup must not connect. If the implementation cannot fail this test, it is <strong>not</strong> checking the resolved address — it is checking a string that happened to resolve once.',
    'Um nome que passa na checagem e depois resolve para um endereço privado na segunda consulta não pode conectar. Se a implementação não consegue falhar neste teste, ela <strong>não</strong> está checando o endereço resolvido — está checando uma string que por acaso resolveu uma vez.')),
 ],
 'done':('Egress is <strong>policy-controlled at the shared fetch layer</strong>, redirects are re-checked, <strong>the worker&#x27;s network position is documented</strong>, <strong>no legitimate stored URL is blocked</strong>, and the policy ran in report-only mode before enforcement.',
         'O egresso é <strong>controlado por política na camada de fetch compartilhada</strong>, redirects são rechecados, <strong>a posição de rede do worker está documentada</strong>, <strong>nenhuma URL legítima guardada é bloqueada</strong>, e a política rodou em modo somente-relatório antes da imposição.'),
 'files':[
  ('back/src/app-api/downloader/downloader.controller.ts:34',False),
  ('back/src/app-api/scraper/',False),
  ('back/src/app-api/api_call/',False),
  ("the worker's HTTP layer",False),
  ('infra network/subnet definitions',False),
  ('per-organisation allowlist storage',True),
 ],
}
