# -*- coding: utf-8 -*-

B1 = dict(
 TITLE=('One reference per execution, not per node','Uma referência por execução, não por node'),
 GOAL=('Make the identifier that travels between nodes name <b>one execution of a node</b>, not &#x27;a node within a run&#x27;.',
       'Fazer o identificador que viaja entre nodes nomear <b>uma execução de um node</b>, não &#x27;um node dentro de um run&#x27;.'),
 GLANCE=[
  ('crit',('Severity','Severidade'),('High','Alta'),
   ('Risk R3 — <code>(execId, nodeId)</code> is about to become the transport in B3. Analysis §8.4.',
    'Risco R3 — o par <code>(execId, nodeId)</code> está prestes a virar o transporte na B3. Análise §8.4.')),
  ('dep',('Depends on','Depende de'),('Nothing','Nada'),
   ('Blocks B3, and therefore B4 and B5 — and also A7.',
    'Bloqueia a B3, e portanto B4 e B5 — e também a A7.')),
  ('wave',('Wave','Onda'),('Wave 4','Onda 4'),
   ('First in the wave: the identity has to be settled before anything passes data by reference.',
    'Primeira da onda: a identidade precisa estar resolvida antes que algo passe dado por referência.')),
  ('ship',('Ship order','Ordem de entrega'),('First, on its own','Primeira, sozinha'),
   ('Nothing depends on it. Fixing it after B3 means changing the transport under running code.',
    'Nada depende dela. Corrigir depois da B3 significa trocar o transporte com código rodando.')),
 ],
 LEDE=('<p><strong>Corrected 2026-08-24.</strong> An earlier version of this task claimed that <code>(execId, nodeId)</code> names &#x27;a node within a run&#x27; and that loops break it in general. That is only half true, and the real situation is more interesting: <strong><code>execId</code> means two different things depending on which path ran the node.</strong></p>'
       '<p>On the Temporal path <code>processNodeViaTemporal</code> mints a fresh id <em>per node dispatch</em> (<code>flux.service.ts</code>), so the pair is already unique. On the legacy path <code>recordLegacyNodeStart</code> is called with <code>execId: runLogProcessId</code> (<code>flux.service.ts</code>) — <strong>the same value for every node in the run</strong>. One column, two incompatible meanings, and this epic is about to merge the two paths into one.</p>',
       '<p><strong>Corrigido em 2026-08-24.</strong> Uma versão anterior desta task afirmava que <code>(execId, nodeId)</code> nomeia &#x27;um node dentro de um run&#x27; e que laços quebram isso em geral. Isso é só meia verdade, e a situação real é mais interessante: <strong><code>execId</code> significa duas coisas diferentes dependendo de qual caminho executou o node.</strong></p>'
       '<p>No caminho Temporal, o <code>processNodeViaTemporal</code> gera um id novo <em>por dispatch de node</em> (<code>flux.service.ts</code>), então o par já é único. No caminho legado, o <code>recordLegacyNodeStart</code> é chamado com <code>execId: runLogProcessId</code> (<code>flux.service.ts</code>) — <strong>o mesmo valor para todos os nodes do run</strong>. Uma coluna, dois significados incompatíveis, e este épico está prestes a fundir os dois caminhos em um.</p>'),
 L1=('The same column, two meanings','A mesma coluna, dois significados'),
 TABLES=[
  dict(head=[('Path','Caminho'),('What mints <code>execId</code>','O que gera o <code>execId</code>'),
             ('Unique per execution?','Único por execução?'),
             ('What the pair names there','O que o par nomeia ali')],
   rows=[
    [{'t':('Temporal path','Caminho Temporal')},
     ('<code>const execId = uuid()</code> per node dispatch, in <code>processNodeViaTemporal</code> (<code>flux.service.ts</code>)',
      '<code>const execId = uuid()</code> por dispatch de node, no <code>processNodeViaTemporal</code> (<code>flux.service.ts</code>)'),
     {'t':('Yes','Sim'),'pill':'ok'},
     ('One execution — including one loop iteration. The stricter of the two meanings.',
      'Uma execução — inclusive uma iteração de laço. O mais estrito dos dois significados.')],
    [{'t':('Legacy path','Caminho legado')},
     ('<code>recordLegacyNodeStart</code> receives <code>execId: runLogProcessId</code> (<code>flux.service.ts</code>) — one value for the whole run',
      'O <code>recordLegacyNodeStart</code> recebe <code>execId: runLogProcessId</code> (<code>flux.service.ts</code>) — um valor para o run inteiro'),
     {'t':('No — one per run','Não — um por run'),'pill':'no'},
     ('A node within a run. Every loop iteration collides with the previous one.',
      'Um node dentro de um run. Cada iteração do laço colide com a anterior.')],
   ]),
  dict(head=[('Where','Onde'),('What it does today','O que faz hoje'),('What that produces','O que isso produz')],
   rows=[
    [{'t':'node_executions (migration)','mono':True},
     ('No unique constraint on <code>(execId, nodeId)</code> — only a plain index (<code>1776400000000-AlterNodeExecutionsForRunScopedIpc.ts</code>)',
      'Nenhuma constraint de unicidade em <code>(execId, nodeId)</code> — apenas um índice comum (<code>1776400000000-AlterNodeExecutionsForRunScopedIpc.ts</code>)'),
     {'t':('Duplicates are legal','Duplicatas são legais'),'pill':'no'}],
    [{'t':'openNodeExecution','mono':True},
     ('A plain <code>INSERT</code>, no <code>ON CONFLICT</code> (<code>node-execution-store.ts</code>)',
      'Um <code>INSERT</code> simples, sem <code>ON CONFLICT</code> (<code>node-execution-store.ts</code>)'),
     {'t':('Repeated executions add rows','Execuções repetidas somam linhas'),'pill':'no'}],
    [{'t':'persistNodeSuccess','mono':True},
     ('Updates <code>WHERE &quot;execId&quot; AND &quot;nodeId&quot;</code> (<code>persist-node-success.ts</code>)',
      'Atualiza <code>WHERE &quot;execId&quot; AND &quot;nodeId&quot;</code> (<code>persist-node-success.ts</code>)'),
     {'t':('Every matching row is written','Toda linha que casa é escrita'),'pill':'no'}],
    [{'t':'fetchNodeRow','mono':True},
     ('Takes <code>rows[0]</code> with no <code>ORDER BY</code> (<code>fetch-node-row.ts</code>)',
      'Pega <code>rows[0]</code> sem <code>ORDER BY</code> (<code>fetch-node-row.ts</code>)'),
     {'t':('Postgres picks the execution','O Postgres escolhe a execução'),'pill':'no'}],
   ]),
 ],
 PROSE1=('This is contained today, and only by accident: the single-node path mints a fresh <code>execId</code> per click, so the duplicates never appear. It stops being contained the moment a consumer reads an upstream&#x27;s output by that pair — which is exactly what <strong>B3</strong> introduces. Fixing it afterwards means changing the transport under running code.',
         'Isso está contido hoje, e só por acidente: o caminho de node único gera um <code>execId</code> novo a cada clique, então as duplicatas nunca aparecem. Deixa de estar contido no instante em que um consumidor lê a saída de um upstream por esse par — que é exatamente o que a <strong>B3</strong> introduz. Corrigir depois significa trocar o transporte com código rodando.'),
 DECINTRO=('One call has to be made before any code is written, and it constrains B3 and B6. The spec is explicit that it must be chosen deliberately and written down — because the merge of the two paths will otherwise pick a meaning by accident.',
           'Uma decisão precisa ser tomada antes de escrever código, e ela restringe a B3 e a B6. A spec é explícita: precisa ser escolhida deliberadamente e registrada — senão a fusão dos dois caminhos escolhe um significado por acidente.'),
 LPARTS=('What the task does, in three parts','O que a task faz, em três partes'),
 PARTS=[
  {'n':'1','title':('Make one row mean one execution','Fazer uma linha significar uma execução'),
   'loc':('node-execution-store.ts · new migration', 'node-execution-store.ts · nova migração'),
   'purpose':('Whatever the transport becomes, the write side has to stop producing rows that cannot be told apart.',
              'Seja qual for o transporte, o lado da escrita precisa parar de produzir linhas indistinguíveis entre si.'),
   'body':('<p><code>openNodeExecution</code> is a plain <code>INSERT</code> with no <code>ON CONFLICT</code>, and the table carries no unique constraint on <code>(execId, nodeId)</code> — only a plain index. On the legacy path, where <code>execId</code> is the run, that is enough to produce several indistinguishable rows for the same node.</p>',
           '<p>O <code>openNodeExecution</code> é um <code>INSERT</code> simples, sem <code>ON CONFLICT</code>, e a tabela não tem constraint de unicidade em <code>(execId, nodeId)</code> — apenas um índice comum. No caminho legado, onde o <code>execId</code> é o run, isso basta para produzir várias linhas indistinguíveis do mesmo node.</p>'),
   'list':[('A <strong>unique constraint</strong>, or an explicit documented reason there is none. Silence is what got us here.',
            'Uma <strong>constraint de unicidade</strong>, ou uma razão documentada explícita para não haver. O silêncio foi o que nos trouxe aqui.'),
           ('The legacy call site stops reusing <code>runLogProcessId</code> and mints an id per execution, so both paths mean the same thing.',
            'O ponto de chamada legado para de reusar o <code>runLogProcessId</code> e passa a gerar um id por execução, para que os dois caminhos signifiquem a mesma coisa.'),
           ('<code>persistNodeSuccess</code> becomes targeted — it writes the execution it owns, not every row that matches a pair.',
            'O <code>persistNodeSuccess</code> passa a ser direcionado — escreve a execução que ele possui, não toda linha que casa com um par.')],
   'ba':(('The same node executed twice under one <code>execId</code> produces two rows nothing can tell apart, and the writer updates both.',
          'O mesmo node executado duas vezes sob um <code>execId</code> produz duas linhas que nada distingue, e o escritor atualiza as duas.'),
         ('One row is one execution. The writer addresses exactly the execution it produced, and a second execution cannot overwrite the first.',
          'Uma linha é uma execução. O escritor endereça exatamente a execução que produziu, e uma segunda execução não pode sobrescrever a primeira.')),
   'callouts':[('mig',('Backfill is part of the change','O backfill faz parte da mudança'),
     ('<p>Existing <code>node_executions</code> rows must remain readable. A migration that orphans historical rows breaks <strong>run history</strong> and the <strong>MCP run-status surface</strong> — both read this table, and neither is in this epic&#x27;s blast radius by choice.</p>',
      '<p>As linhas existentes de <code>node_executions</code> precisam continuar legíveis. Uma migração que órfã linhas históricas quebra o <strong>histórico de runs</strong> e a <strong>superfície de status de run do MCP</strong> — as duas leem esta tabela, e nenhuma está no raio de impacto deste épico por escolha.</p>'))]},
  {'n':'2','title':('Every read that can match more than one row gets an order','Toda leitura que pode casar mais de uma linha ganha ordem'),
   'loc':'fetch-node-row.ts · persist-node-success.ts',
   'purpose':('A read that relies on Postgres ordering is a coin flip that usually lands the same way — until it does not.',
              'Uma leitura que depende da ordenação do Postgres é uma moeda que quase sempre cai do mesmo lado — até não cair.'),
   'body':('<p><code>fetchNodeRow</code> takes <code>rows[0]</code> with no <code>ORDER BY</code>. Postgres does not promise an order without one, so which execution a consumer reads is decided by the storage engine, not by the code. On the legacy path today that means a loop&#x27;s consumer can read any iteration.</p>'
           '<p>The rule is narrow and mechanical: <strong>no read that can match multiple rows relies on Postgres ordering</strong>. Where a single execution is meant, address it; where the latest is meant, say so.</p>',
           '<p>O <code>fetchNodeRow</code> pega <code>rows[0]</code> sem <code>ORDER BY</code>. O Postgres não promete ordem sem isso, então qual execução um consumidor lê é decidido pelo motor de armazenamento, não pelo código. No caminho legado, hoje, isso significa que o consumidor de um laço pode ler qualquer iteração.</p>'
           '<p>A regra é estreita e mecânica: <strong>nenhuma leitura que possa casar várias linhas depende da ordenação do Postgres</strong>. Onde se quer uma execução específica, endereça-se ela; onde se quer a última, diz-se isso.</p>'),
   'ba':(('<code>rows[0]</code> with no <code>ORDER BY</code> — the consumer reads whichever row the engine returns first.',
          '<code>rows[0]</code> sem <code>ORDER BY</code> — o consumidor lê a linha que o motor devolver primeiro.'),
         ('Either the read addresses one execution directly, or it states an order. Nothing is left to the storage engine.',
          'Ou a leitura endereça uma execução diretamente, ou declara uma ordem. Nada fica a cargo do motor de armazenamento.'))},
  {'n':'3','title':('Billing is the one place where &#x27;every matching row&#x27; may have been intended','Cobrança é o único lugar onde &#x27;toda linha que casa&#x27; pode ter sido intencional'),
   'loc':'flux.service.ts',
   'purpose':('<code>sumChargesByExecution(execId, nodeId)</code> aggregates by the same pair — and for a loop, summing every row is arguably the right answer.',
              'O <code>sumChargesByExecution(execId, nodeId)</code> agrega pelo mesmo par — e para um laço, somar todas as linhas é possivelmente a resposta certa.'),
   'body':('<p>Everywhere else in this task, matching several rows is the defect. Here it is plausibly the feature: a loop&#x27;s cost <em>is</em> the sum across its iterations. Changing the identity without checking this is how a correct refactor produces a wrong invoice.</p>'
           '<p>So the aggregate is re-expressed against whatever identity wins, and <strong>loop totals are proven unchanged</strong> before and after — not assumed unchanged because the code looks equivalent.</p>',
           '<p>Em todo o resto desta task, casar várias linhas é o defeito. Aqui é plausivelmente a funcionalidade: o custo de um laço <em>é</em> a soma das iterações. Mudar a identidade sem checar isso é como um refactor correto produz uma fatura errada.</p>'
           '<p>Então a agregação é reexpressa contra a identidade vencedora, e <strong>os totais de laço são provados inalterados</strong> antes e depois — não presumidos inalterados porque o código parece equivalente.</p>'),
   'ba':(('Loop billing happens to work because the aggregate sums every row matching the pair — a behaviour nobody wrote down as intended.',
          'A cobrança de laço funciona por acaso porque a agregação soma toda linha que casa com o par — um comportamento que ninguém registrou como intencional.'),
         ('The aggregate is expressed against the chosen identity, and the loop total is the same number before and after the change.',
          'A agregação é expressa contra a identidade escolhida, e o total do laço é o mesmo número antes e depois da mudança.')),
   'callouts':[('mig',('Out of scope','Fora de escopo'),
     ('<p>Changing loop semantics. <strong>B6</strong> owns those; B1 only makes them addressable. And sub-flows do not share the parent&#x27;s execution identity — a sub-flow is a different graph with its own scheduler state, so it gets its own run identity <strong>chained to the parent</strong>. <code>TASK-S1</code> owns that chain.</p>',
      '<p>Mudar a semântica de laço. A <strong>B6</strong> é dona disso; a B1 apenas as torna endereçáveis. E sub-fluxos não compartilham a identidade de execução do pai — um sub-fluxo é outro grafo, com estado de scheduler próprio, então ganha identidade de run própria <strong>encadeada ao pai</strong>. A <code>TASK-S1</code> é dona dessa cadeia.</p>'))]},
 ],
 VERIF=[
  (True,('Negative control','Controle negativo'),
   ('Run one node <strong>twice under the same <code>execId</code></strong> and assert the second read returns the second execution. Run it against <code>main</code> first and watch it fail — <strong>or pass by luck, which is the more likely and the more alarming outcome</strong>. If it passes on <code>main</code>, force the row order by inserting them out of order until it fails, then fix and re-run.',
    'Execute um node <strong>duas vezes sob o mesmo <code>execId</code></strong> e afirme que a segunda leitura devolve a segunda execução. Rode primeiro contra a <code>main</code> e veja falhar — <strong>ou passar por sorte, que é o resultado mais provável e mais alarmante</strong>. Se passar na <code>main</code>, force a ordem inserindo as linhas fora de ordem até falhar, então corrija e rode de novo.')),
  (False,('Backfill check','Checagem de backfill'),
   ('Existing <code>node_executions</code> rows must remain readable. A migration that orphans historical rows breaks <strong>run history</strong> and the <strong>MCP run-status surface</strong>.',
    'As linhas existentes de <code>node_executions</code> precisam continuar legíveis. Uma migração que órfã linhas históricas quebra o <strong>histórico de runs</strong> e a <strong>superfície de status de run do MCP</strong>.')),
  (False,('Loop billing is unchanged','A cobrança de laço não muda'),
   ('<code>sumChargesByExecution(execId, nodeId)</code> (<code>flux.service.ts</code>) aggregates by the same pair. Confirm billing totals are unchanged for loops — <strong>this is the one place where &#x27;every matching row&#x27; was arguably the intended behaviour</strong>.',
    'O <code>sumChargesByExecution(execId, nodeId)</code> (<code>flux.service.ts</code>) agrega pelo mesmo par. Confirme que os totais de cobrança não mudam para laços — <strong>este é o único lugar onde &#x27;toda linha que casa&#x27; era possivelmente o comportamento pretendido</strong>.')),
 ],
 DONE=('No read that can match multiple rows relies on Postgres ordering; <strong>the transport identifies one execution</strong>; and loop billing is <strong>provably</strong> unchanged.',
       'Nenhuma leitura que possa casar várias linhas depende da ordenação do Postgres; <strong>o transporte identifica uma execução</strong>; e a cobrança de laço é <strong>comprovadamente</strong> a mesma.'),
 FILES=[('back/src/entities/node_execution.entity.ts',False),
        ('back/src/temporal/single-node-legacy/node-execution-store.ts',False),
        ('back/src/app-api/flux/flux.service.ts',False),
        ('worker/src/modules/nodes/shared/fetch-node-row.ts',False),
        ('worker/src/modules/nodes/shared/persist-node-success.ts',False),
        ('back/src/app-api/token_transaction/token_transaction.service.ts',False),
        ('back/src/database/migrations/ (new)',True)],
)

B1_DEC = {
 'k':'decision','id':'B1-a','status':'rec','open':True,
 'q':('Which meaning survives the merge, and what actually travels between nodes?',
      'Qual significado sobrevive à fusão, e o que de fato viaja entre os nodes?'),
 'intro':('The two paths disagree today and the epic is about to merge them. The spec names <strong>two candidates</strong> for the identity and asks for one to be picked and the reason written down here, because the choice constrains <strong>B3</strong> (which makes this the transport) and <strong>B6</strong> (which makes loop position meaningful).',
          'Os dois caminhos discordam hoje e o épico está prestes a fundi-los. A spec nomeia <strong>dois candidatos</strong> para a identidade e pede que um seja escolhido e a razão registrada aqui, porque a escolha restringe a <strong>B3</strong> (que faz disto o transporte) e a <strong>B6</strong> (que dá significado à posição no laço).'),
 'opts':[
  {'ltr':'A','pick':True,'name':('<code>node_executions.id</code> is the reference','O <code>node_executions.id</code> é a referência'),
   'tag':('recommended','recomendada'),
   'how':('The existing primary key becomes the value that travels between nodes. <code>(execId, nodeId)</code> stays a lookup key and is <strong>never</strong> a transport.',
          'A chave primária existente passa a ser o valor que viaja entre nodes. O par <code>(execId, nodeId)</code> continua sendo chave de busca e <strong>nunca</strong> é transporte.'),
   'pros':[('Cheapest — the column already exists and is already unique','Mais barata — a coluna já existe e já é única'),
           ('Keeps the <strong>Temporal meaning</strong>, which is already the stricter of the two and is what <code>node_executions</code> was documented to be: one row per node run','Mantém o <strong>significado do Temporal</strong>, que já é o mais estrito dos dois e é o que <code>node_executions</code> foi documentado a ser: uma linha por execução de node'),
           ('The only candidate that survives loops <em>and</em> parallelism with no discriminator at all','O único candidato que sobrevive a laços <em>e</em> a paralelismo sem nenhum discriminador')],
   'cons':[('The reference is opaque in a log — you cannot read the loop position off it','A referência é opaca num log — não dá para ler a posição do laço nela'),
           ('The legacy call site still has to stop reusing <code>runLogProcessId</code>; the primary key does not fix the writer by itself','O ponto de chamada legado ainda precisa parar de reusar o <code>runLogProcessId</code>; a chave primária não conserta o escritor sozinha')],
   'cost':[('lo',('Client effort: <b>none — run history keeps its rows</b>','Esforço do cliente: <b>nenhum — o histórico mantém suas linhas</b>')),
           ('lo',('Ours: <b>the column is already there</b>','Nosso: <b>a coluna já existe</b>'))]},
  {'ltr':'B','name':('An iteration discriminator in the key','Um discriminador de iteração na chave'),
   'how':('A third field is added so <code>(execId, nodeId, iteration)</code> is unique, and that triple is what travels.',
          'Um terceiro campo é adicionado para que <code>(execId, nodeId, iteration)</code> seja único, e essa tripla é o que viaja.'),
   'pros':[('The reference stays <strong>human-readable in logs</strong> — you can see which iteration you are looking at','A referência continua <strong>legível por humanos nos logs</strong> — dá para ver de qual iteração se trata'),
           ('Makes loop position explicit, which <strong>B6 will want anyway</strong>','Torna a posição no laço explícita, o que a <strong>B6 vai querer de qualquer forma</strong>'),
           ('The unique constraint can be declared on the triple, so the database enforces the meaning','A constraint de unicidade pode ser declarada sobre a tripla, então o banco impõe o significado')],
   'cons':[('More invasive — every writer and every reader learns a third field','Mais invasiva — todo escritor e todo leitor aprende um terceiro campo'),
           ('It does not avoid the legacy work: that path must stop reusing <code>runLogProcessId</code> either way','Não evita o trabalho no legado: aquele caminho precisa parar de reusar o <code>runLogProcessId</code> de qualquer jeito'),
           ('A node that runs twice for a reason that is <em>not</em> a loop — a retry, a re-run — needs <code>iteration</code> defined for it too','Um node que roda duas vezes por um motivo que <em>não</em> é laço — retry, re-execução — também precisa de <code>iteration</code> definido')],
   'cost':[('',('Client effort: <b>none, but a migration touches every row</b>','Esforço do cliente: <b>nenhum, mas a migração toca toda linha</b>')),
           ('hi',('Ours: <b>a third field in every writer and reader</b>','Nosso: <b>um terceiro campo em todo escritor e leitor</b>'))]},
  {'ltr':'C','no':True,'name':('Let the merge decide','Deixar a fusão decidir'),
   'tag':('not viable','inviável'),
   'how':('Keep both meanings and let whichever path wins the merge define what the column means.',
          'Manter os dois significados e deixar que o caminho vencedor da fusão defina o que a coluna significa.'),
   'pros':[('No work now','Nenhum trabalho agora')],
   'cons':[('It is the spec&#x27;s own warning: the merge will pick a meaning <strong>by accident</strong>','É o próprio alerta da spec: a fusão escolhe um significado <strong>por acidente</strong>'),
           ('If the legacy meaning wins, B3&#x27;s transport collides on <strong>every loop iteration</strong>','Se o significado legado vencer, o transporte da B3 colide em <strong>toda iteração de laço</strong>'),
           ('the <code>rows[0]</code> inside <code>fetchNodeRow</code> then decides which execution a consumer reads, and Postgres promises nothing about that','O <code>rows[0]</code> do <code>fetchNodeRow</code> então decide qual execução o consumidor lê, e o Postgres não promete nada quanto a isso')],
   'cost':[('lo',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('hi',('Ours: <b>a transport that is wrong on loops</b>','Nosso: <b>um transporte errado em laços</b>'))]},
 ],
 'rec':('<p><strong>A — keep the Temporal meaning: one id per node execution, and make the legacy path conform.</strong> It is already the stricter of the two, it is what <code>node_executions</code> was documented to be, and it is the only one of the two that survives loops and parallelism without a discriminator.</p>'
        '<p>B is not wrong, and it buys something real for B6 — but it buys it at the price of a third field in every writer and reader, and it does not remove the legacy work. If loop position turns out to be needed in logs, it can be added as a <em>column</em> later without being the <em>identity</em>.</p>'
        '<p>Whichever wins, three things ship with it: a <strong>unique constraint</strong> or an explicit documented reason there is none, <strong><code>ORDER BY</code> on every read</strong> that can match more than one row, and a <strong>targeted <code>persistNodeSuccess</code></strong>.</p>',
        '<p><strong>A — manter o significado do Temporal: um id por execução de node, e fazer o caminho legado se conformar.</strong> Ele já é o mais estrito dos dois, é o que <code>node_executions</code> foi documentado a ser, e é o único dos dois que sobrevive a laços e paralelismo sem discriminador.</p>'
        '<p>B não é errada, e compra algo real para a B6 — mas compra ao preço de um terceiro campo em todo escritor e leitor, e não elimina o trabalho no legado. Se a posição no laço se mostrar necessária nos logs, ela pode virar uma <em>coluna</em> depois, sem ser a <em>identidade</em>.</p>'
        '<p>Vencendo qualquer uma, três coisas vão junto: uma <strong>constraint de unicidade</strong> ou uma razão documentada explícita para não haver, <strong><code>ORDER BY</code> em toda leitura</strong> que possa casar mais de uma linha, e um <strong><code>persistNodeSuccess</code> direcionado</strong>.</p>'),
 'who':[('Engineering','Engenharia'),('B3 and B6 read the answer','B3 e B6 leem a resposta')],
}

B2 = dict(
 TITLE=('Decide code sharing, then extract the scheduler','Decidir compartilhamento de código, e extrair o scheduler'),
 GOAL=('Get the two pure modules the worker needs out of <code>back</code> — under a decision made <b>once, deliberately</b>, rather than by whoever writes B3 first.',
       'Tirar do <code>back</code> os dois módulos puros de que o worker precisa — sob uma decisão tomada <b>uma vez, deliberadamente</b>, e não por quem escrever a B3 primeiro.'),
 GLANCE=[
  ('crit',('Severity','Severidade'),('Medium','Média'),
   ('Risk R6 — a second copy of the scheduler is the most expensive possible place for silent drift.',
    'Risco R6 — uma segunda cópia do scheduler é o lugar mais caro possível para uma divergência silenciosa.')),
  ('dep',('Depends on','Depende de'),('Nothing','Nada'),
   ('Blocks B3 and B4. Blocked on decision <strong>D1</strong>.',
    'Bloqueia a B3 e a B4. Bloqueada pela decisão <strong>D1</strong>.')),
  ('wave',('Wave','Onda'),('Wave 4','Onda 4'),
   ('Ahead of B3 and B4, which both consume what it extracts.',
    'À frente da B3 e da B4, que consomem o que ela extrai.')),
  ('ship',('Shape','Formato'),('Two pure modules','Dois módulos puros'),
   ('No injection, no database, no I/O — the case where sharing is cheapest and copying is most tempting.',
    'Sem injeção, sem banco, sem I/O — o caso em que compartilhar é mais barato e copiar é mais tentador.')),
 ],
 LEDE=('<p>Two modules have to be reachable from the worker: <code>flux/scheduler.ts</code> — already the single source of ordering truth — and the node-reference substitution service. Both are <strong>pure</strong>: no NestJS injection, no database, no I/O.</p>'
       '<p>That purity is what makes sharing cheap and copying tempting. It is also what makes copying dangerous: a second scheduler means the back and the worker can disagree about <strong>what runs next</strong>, and nothing would say so. The project rule is explicit — <em>import the product&#x27;s rule; never restate it</em>.</p>',
       '<p>Dois módulos precisam ser alcançáveis a partir do worker: o <code>flux/scheduler.ts</code> — já a única fonte de verdade sobre ordenação — e o serviço de substituição de referências de node. Os dois são <strong>puros</strong>: sem injeção do NestJS, sem banco, sem I/O.</p>'
       '<p>Essa pureza é o que torna compartilhar barato e copiar tentador. É também o que torna copiar perigoso: um segundo scheduler significa que o back e o worker podem discordar sobre <strong>o que roda em seguida</strong>, e nada avisaria. A regra do projeto é explícita — <em>importe a regra do produto; nunca a repita</em>.</p>'),
 L1=('The two modules, and what makes them portable','Os dois módulos, e o que os torna portáveis'),
 TABLES=[
  dict(head=[('Module','Módulo'),('What it is','O que é'),('Injected dependencies','Dependências injetadas'),('Who consumes it today','Quem consome hoje')],
   rows=[
    [{'t':'flux/scheduler.ts','mono':True},
     ('<code>buildSchedulerState</code>, <code>classifyEdge</code>, <code>isDependencyEdge</code>, <code>nextReady</code>, <code>markCompleted</code>, <code>markDead</code>, <code>completeCondition</code>, <code>computeLoopBody</code>, <code>planOrder</code>',
      '<code>buildSchedulerState</code>, <code>classifyEdge</code>, <code>isDependencyEdge</code>, <code>nextReady</code>, <code>markCompleted</code>, <code>markDead</code>, <code>completeCondition</code>, <code>computeLoopBody</code>, <code>planOrder</code>'),
     {'t':('None','Nenhuma'),'pill':'ok'},
     ('<code>flux.service.ts</code> and <code>app-mcp/mcp-write.service.ts</code>',
      '<code>flux.service.ts</code> e <code>app-mcp/mcp-write.service.ts</code>')],
    [{'t':'node-reference-substitution.service.ts','mono':True},
     ('268 lines: <code>replacePlaceholders</code>, <code>generateSchemaFromNodes</code>, <code>applySubstitutionToObject</code>, <code>updateSchemaWithNodeOutput</code>, <code>resolveTextDataFromSchema</code>, <code>processFlowWithSubstitution</code>',
      '268 linhas: <code>replacePlaceholders</code>, <code>generateSchemaFromNodes</code>, <code>applySubstitutionToObject</code>, <code>updateSchemaWithNodeOutput</code>, <code>resolveTextDataFromSchema</code>, <code>processFlowWithSubstitution</code>'),
     {'t':('None','Nenhuma'),'pill':'ok'},
     ('The API&#x27;s input resolution — the step <strong>B3</strong> moves to the consumer',
      'A resolução de entrada da API — o passo que a <strong>B3</strong> move para o consumidor')],
   ]),
 ],
 PROSE1=('Against sharing: <code>back</code> and <code>worker</code> are separate git repos wired as submodules, with <strong>no shared build graph and no root workspace</strong>. The <code>thirdPartyIntegration</code> migration weighed the same question and chose copy-port, for reasons recorded in <code>worker-thirdparty-integration-migration/PLAN.md</code> — but that was for <em>adapter</em> code that dragged heavy dependencies. These two drag nothing.',
         'Contra compartilhar: <code>back</code> e <code>worker</code> são repositórios git separados ligados como submódulos, <strong>sem grafo de build comum e sem workspace raiz</strong>. A migração do <code>thirdPartyIntegration</code> pesou a mesma pergunta e escolheu copy-port, por razões registradas em <code>worker-thirdparty-integration-migration/PLAN.md</code> — mas aquilo era código <em>adaptador</em>, que arrastava dependências pesadas. Estes dois não arrastam nada.'),
 DECINTRO=('One decision, and it is the reason this task exists as a task rather than as a line inside B3. It is genuinely open: both answers are defensible, and the epic explicitly refuses to let it be decided by whoever writes the consuming code first.',
           'Uma decisão, e ela é a razão desta task existir como task em vez de ser uma linha dentro da B3. Está genuinamente em aberto: os dois lados se defendem, e o épico explicitamente recusa que ela seja decidida por quem escrever o código consumidor primeiro.'),
 LPARTS=('What the task does, in three parts','O que a task faz, em três partes'),
 PARTS=[
  {'n':'1','title':('Extract, without changing behaviour','Extrair, sem mudar comportamento'),
   'loc':'flux/scheduler.ts · node-reference-substitution.service.ts',
   'purpose':('Extraction is behaviour-neutral. The only thing that changes is where the file lives and who can import it. Before B4 writes <code>allReady()</code>, check whether the Temporal SDK already offers a ready-set primitive; decide during development — <code>D16</code> is unchanged either way.',
              'A extração é neutra em comportamento. A única coisa que muda é onde o arquivo mora e quem pode importá-lo. Antes de a B4 escrever o <code>allReady()</code>, verifique se o SDK do Temporal já oferece uma primitiva de conjunto pronto; decida durante o desenvolvimento — a <code>D16</code> não muda de nenhum jeito.'),
   'body':('<p>Both modules move as they are. Nothing about ordering, edge classification or placeholder resolution changes in this task — if a behaviour needs fixing, it is <strong>C3</strong>&#x27;s, and it is fixed <em>before</em> the copy exists, because after duplication each fix costs twice.</p>'
           '<p>The batch sibling of <code>nextReady</code> — <code>allReady</code> — belongs to <strong>B4</strong>, not here. And <code>nextReady</code> itself stays: <code>mcp-write.service.ts</code> consumes the scheduler and is <strong>not part of this epic</strong>.</p>',
           '<p>Os dois módulos vão como estão. Nada de ordenação, classificação de arestas ou resolução de placeholders muda nesta task — se algum comportamento precisa de correção, ele é da <strong>C3</strong>, e é corrigido <em>antes</em> de a cópia existir, porque depois da duplicação cada correção custa em dobro.</p>'
           '<p>O irmão em lote do <code>nextReady</code> — o <code>allReady</code> — é da <strong>B4</strong>, não daqui. E o próprio <code>nextReady</code> fica: o <code>mcp-write.service.ts</code> consome o scheduler e <strong>não faz parte deste épico</strong>.</p>'),
   'ba':(('The scheduler and the substitution service are reachable only from inside the NestJS app. The worker cannot ask what runs next without asking the API.',
          'O scheduler e o serviço de substituição só são alcançáveis de dentro da app NestJS. O worker não consegue perguntar o que roda em seguida sem perguntar à API.'),
         ('Both modules are consumable from the worker, with identical behaviour and the same consumers on the back side still working.',
          'Os dois módulos são consumíveis a partir do worker, com comportamento idêntico e os mesmos consumidores do lado do back ainda funcionando.'))},
  {'n':'2','title':('The drift test, if copy-port wins','O teste de divergência, se o copy-port vencer'),
   'loc':('PLAN §3.5 — the backend has no CI test run', 'PLAN §3.5 — o backend não tem execução de teste em CI'),
   'purpose':('A comment asking people to be careful is not a mechanism. The test has to fail when the copies diverge.',
              'Um comentário pedindo cuidado não é um mecanismo. O teste precisa falhar quando as cópias divergem.'),
   'body':('<p>If copy-port is chosen, two artefacts ship with it: a <code>PORTED_FROM.md</code> per module carrying the <strong>source SHA</strong>, and a drift test that goes red when the two copies stop agreeing.</p>'
           '<p>The uncomfortable part is where that test runs. <strong>No workflow runs jest in <code>back</code></strong> (PLAN §3.5), so &#x27;it is covered by a test&#x27; is not, by itself, a guarantee anybody will see. The runner has to be named — a repository, a pipeline, a schedule — not assumed.</p>',
           '<p>Se o copy-port for escolhido, dois artefatos vão junto: um <code>PORTED_FROM.md</code> por módulo carregando o <strong>SHA de origem</strong>, e um teste de divergência que fica vermelho quando as duas cópias param de concordar.</p>'
           '<p>A parte incômoda é onde esse teste roda. <strong>Nenhum workflow roda jest no <code>back</code></strong> (PLAN §3.5), então &#x27;está coberto por teste&#x27; não é, por si só, uma garantia que alguém vá ver. O executor precisa ser nomeado — um repositório, um pipeline, um agendamento — não presumido.</p>'),
   'ba':(('One implementation, in the back. Anyone editing it edits the only copy, and the worker cannot use it at all.',
          'Uma implementação, no back. Quem edita, edita a única cópia, e o worker não consegue usá-la de forma nenhuma.'),
         ('Either one shared implementation, or two copies with a test that <strong>fails</strong> when they diverge and a named place where that test actually runs.',
          'Ou uma implementação compartilhada, ou duas cópias com um teste que <strong>falha</strong> quando elas divergem e um lugar nomeado onde esse teste de fato roda.')),
   'callouts':[('decide',('The verification can veto the decision','A verificação pode vetar a decisão'),
     ('<p>The spec is blunt about this: if copy-port was chosen and the drift test <strong>cannot be made to fail automatically</strong>, copy-port is not viable — say so and revisit <strong>D1</strong>. That makes the negative control a gate on the decision itself, not just on the code.</p>',
      '<p>A spec é direta: se o copy-port foi escolhido e o teste de divergência <strong>não puder ser feito falhar automaticamente</strong>, o copy-port não é viável — diga isso e reabra a <strong>D1</strong>. Isso faz do controle negativo um portão sobre a própria decisão, não só sobre o código.</p>'))]},
  {'n':'3','title':('Equivalence over every stored flow','Equivalência sobre todo fluxo guardado'),
   'loc':'buildSchedulerState · planOrder',
   'purpose':('This is a pure function over data that already exists, so <strong>full</strong> coverage is achievable — take it.',
              'Isto é uma função pura sobre dados que já existem, então a cobertura <strong>total</strong> é alcançável — pegue-a.'),
   'body':('<p>Run both implementations over every stored flow&#x27;s node and edge set and assert identical <code>SchedulerState</code> and identical <code>planOrder</code>. Not a sample: every flow. There is no cost to running a pure function over data at rest, and this is the last moment where a divergence is cheap to find.</p>',
           '<p>Rode as duas implementações sobre o conjunto de nodes e arestas de todo fluxo guardado e afirme <code>SchedulerState</code> idêntico e <code>planOrder</code> idêntico. Não uma amostra: todos os fluxos. Não há custo em rodar uma função pura sobre dado parado, e este é o último momento em que uma divergência é barata de achar.</p>'),
   'ba':(('Equivalence between the two implementations would be assumed. Nothing compares them, because until now there is only one.',
          'A equivalência entre as duas implementações seria presumida. Nada as compara, porque até agora só existe uma.'),
         ('Every stored flow is replayed through both and asserted identical — <code>SchedulerState</code> and <code>planOrder</code>, node for node.',
          'Todo fluxo guardado é reproduzido pelas duas e afirmado idêntico — <code>SchedulerState</code> e <code>planOrder</code>, node a node.'))},
 ],
 VERIF=[
  (True,('Negative control','Controle negativo'),
   ('Change one branch of <code>classifyEdge</code> in the extracted copy and confirm the drift test — or the package&#x27;s own suite — <strong>goes red</strong>. If copy-port was chosen and this cannot be made to fail automatically, <strong>copy-port is not viable</strong>: say so and revisit D1.',
    'Altere um ramo do <code>classifyEdge</code> na cópia extraída e confirme que o teste de divergência — ou a suíte do próprio pacote — <strong>fica vermelho</strong>. Se o copy-port foi escolhido e isso não puder falhar automaticamente, <strong>o copy-port não é viável</strong>: diga isso e reabra a D1.')),
  (False,('Behaviour equivalence over real flows','Equivalência de comportamento sobre fluxos reais'),
   ('Run both implementations over <strong>every</strong> stored flow&#x27;s node and edge set and assert identical <code>SchedulerState</code> and identical <code>planOrder</code>. Pure function, data at rest — full coverage is achievable, so take it.',
    'Rode as duas implementações sobre o conjunto de nodes e arestas de <strong>todo</strong> fluxo guardado e afirme <code>SchedulerState</code> e <code>planOrder</code> idênticos. Função pura, dado parado — cobertura total é alcançável, então pegue-a.')),
  (False,('The other consumer still works','O outro consumidor continua funcionando'),
   ('<code>app-mcp/mcp-write.service.ts</code> consumes the scheduler and is <strong>not part of this epic</strong>. Confirm it behaves identically after the extraction — this is the consumer most likely to be forgotten.',
    'O <code>app-mcp/mcp-write.service.ts</code> consome o scheduler e <strong>não faz parte deste épico</strong>. Confirme que ele se comporta de forma idêntica depois da extração — é o consumidor com mais chance de ser esquecido.')),
 ],
 DONE=('<strong>D1 is answered in writing</strong>; both modules are consumable from the worker; equivalence is proven over real flows; and drift is detected <strong>by a test, not by convention</strong>.',
       '<strong>A D1 está respondida por escrito</strong>; os dois módulos são consumíveis a partir do worker; a equivalência está provada sobre fluxos reais; e a divergência é detectada <strong>por um teste, não por convenção</strong>.'),
 FILES=[('back/src/app-api/flux/scheduler.ts',False),
        ('back/src/app-api/node-reference-substitution/node-reference-substitution.service.ts',False),
        ('back/src/app-mcp/mcp-write.service.ts (consumer)',False),
        ('worker/src/** (new consumption point)',True),
        ('PORTED_FROM.md per module, if copy-port wins',True),
        ('worker-thirdparty-integration-migration/PLAN.md (prior art)',False)],
)

B2_DEC = {
 'k':'decision','id':'B2-a','plan':'D1','status':'open','open':True,
 'q':('Shared package between <code>back</code> and <code>worker</code>, or copy-port with a drift test?',
      'Pacote compartilhado entre <code>back</code> e <code>worker</code>, ou copy-port com teste de divergência?'),
 'intro':('<strong>D1 in <code>DELIVERY-PLAN.md</code>, and the only one of the fifteen recorded as &#x27;genuinely open&#x27;.</strong> '
          'The repos are separate submodules with no shared build graph and no root workspace, and the <code>thirdPartyIntegration</code> migration already chose copy-port once — for adapter code that dragged heavy dependencies. '
          'These two modules drag nothing, which is exactly the case where sharing is cheapest. Against that sits a fact worth stating plainly: <strong>no workflow runs jest in <code>back</code></strong> (PLAN §3.5), so a drift test is only a guarantee if someone names where it runs.',
          '<strong>A D1 do <code>DELIVERY-PLAN.md</code>, e a única das quinze registrada como &#x27;genuinamente em aberto&#x27;.</strong> '
          'Os repos são submódulos separados, sem grafo de build comum e sem workspace raiz, e a migração do <code>thirdPartyIntegration</code> já escolheu copy-port uma vez — para código adaptador que arrastava dependências pesadas. '
          'Estes dois módulos não arrastam nada, que é justamente o caso em que compartilhar sai mais barato. Contra isso pesa um fato que vale dizer claramente: <strong>nenhum workflow roda jest no <code>back</code></strong> (PLAN §3.5), então um teste de divergência só é garantia se alguém nomear onde ele roda.'),
 'opts':[
  {'ltr':'A','pick':True,'name':('A shared npm package','Um pacote npm compartilhado'),
   'tag':('recommended','recomendada'),
   'how':('One privately published package holding both modules, consumed by <code>back</code> and <code>worker</code> as a normal dependency. Version bumps are explicit; the submodule-bump ordering is unchanged — submodule pushed before the superproject, always.',
          'Um pacote publicado de forma privada com os dois módulos, consumido por <code>back</code> e <code>worker</code> como dependência normal. Bumps de versão são explícitos; a ordem de bump de submódulo não muda — submódulo empurrado antes do superprojeto, sempre.'),
   'pros':[('<strong>One implementation</strong>, so the back and the worker cannot disagree about what runs next','<strong>Uma implementação</strong>, então back e worker não podem discordar sobre o que roda em seguida'),
           ('Version pinning makes an upgrade a deliberate act, and a regression is bisectable by version','O pin de versão faz do upgrade um ato deliberado, e uma regressão fica bissectável por versão'),
           ('The modules are pure, so the package has <strong>no runtime dependencies to reconcile</strong> between the two repos','Os módulos são puros, então o pacote <strong>não tem dependências de runtime a reconciliar</strong> entre os dois repos')],
   'cons':[('A release process for two files: publish, bump, install — in two repos, on every change','Um processo de release para dois arquivos: publicar, subir versão, instalar — em dois repos, a cada mudança'),
           ('A one-line fix becomes two PRs and a publish before it can ship anywhere','Uma correção de uma linha vira dois PRs e uma publicação antes de poder ir para qualquer lugar'),
           ('Needs a registry and credentials in both deploy paths — infra work that has no other reason to exist yet','Exige um registry e credenciais nos dois caminhos de deploy — trabalho de infra que ainda não tem outra razão para existir')],
   'cost':[('lo',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('hi',('Ours: <b>a release step on every scheduler change</b>','Nosso: <b>um passo de release a cada mudança no scheduler</b>'))]},
  {'ltr':'B','name':('Copy-port with a drift test','Copy-port com teste de divergência'),
   'tag':('prior art','precedente'),
   'how':('Each module is copied into the worker with a <code>PORTED_FROM.md</code> carrying the source SHA, plus a test that fails when the two copies diverge. This is what the <code>thirdPartyIntegration</code> migration did.',
          'Cada módulo é copiado para o worker com um <code>PORTED_FROM.md</code> carregando o SHA de origem, mais um teste que falha quando as duas cópias divergem. Foi o que a migração do <code>thirdPartyIntegration</code> fez.'),
   'pros':[('No build-graph change, no registry, no release step — it matches how the workspace already ships','Sem mudança de grafo de build, sem registry, sem passo de release — combina com como o workspace já entrega'),
           ('A fix lands in one PR per repo, on the same branch name, in the same deploy','Uma correção entra em um PR por repo, no mesmo nome de branch, no mesmo deploy'),
           ('The drift test is genuinely cheap for a pure function: run both, compare the output','O teste de divergência é realmente barato para função pura: rode as duas, compare a saída')],
   'cons':[('<strong>The drift test is the whole guarantee</strong>, and the back has no CI test run — where it runs must be stated, not assumed','<strong>O teste de divergência é a garantia inteira</strong>, e o back não tem execução de teste no CI — onde ele roda precisa ser declarado, não presumido'),
           ('A copy edited under time pressure drifts first and is discovered last','Uma cópia editada sob pressão diverge primeiro e é descoberta por último'),
           ('It is the <strong>most expensive possible place</strong> for that to happen: the two repos would disagree about execution order','É o <strong>lugar mais caro possível</strong> para isso acontecer: os dois repos discordariam sobre a ordem de execução')],
   'cost':[('lo',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('',('Ours: <b>a drift test that must actually run</b>','Nosso: <b>um teste de divergência que precisa mesmo rodar</b>'))]},
  {'ltr':'C','name':('A shared submodule or subtree','Um submódulo ou subtree compartilhado'),
   'how':('A third repository holds both modules and is pulled into <code>back</code> and <code>worker</code> as a git submodule or subtree.',
          'Um terceiro repositório guarda os dois módulos e é puxado para <code>back</code> e <code>worker</code> como submódulo ou subtree git.'),
   'pros':[('One source of truth with no registry and no publish step','Uma fonte de verdade sem registry e sem passo de publicação'),
           ('The workspace already runs on submodules, so the tooling is familiar','O workspace já roda sobre submódulos, então a ferramenta é conhecida')],
   'cons':[('A third pointer to bump on every change, and a fourth repo in a workspace that just collapsed to one root','Um terceiro ponteiro para atualizar a cada mudança, e um quarto repo num workspace que acabou de ser colapsado num único root'),
           ('A stale pointer looks exactly like a fixed bug that never shipped — the workspace&#x27;s most familiar failure','Um ponteiro desatualizado parece exatamente um bug corrigido que nunca subiu — a falha mais conhecida do workspace'),
           ('It keeps the sharing benefit but pays it in the currency the team already loses to','Mantém o benefício do compartilhamento, mas paga na moeda em que o time já perde')],
   'cost':[('lo',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('hi',('Ours: <b>a third submodule pointer to keep honest</b>','Nosso: <b>um terceiro ponteiro de submódulo para manter honesto</b>'))]},
  {'ltr':'D','name':('A monorepo','Um monorepo'),
   'how':('<code>back</code>, <code>worker</code> (and <code>front</code>) collapse into one repository with one build graph, and the two modules become a workspace package.',
          '<code>back</code>, <code>worker</code> (e <code>front</code>) colapsam em um repositório com um grafo de build, e os dois módulos viram um pacote de workspace.'),
   'pros':[('The question disappears permanently — one build graph, one test run, atomic cross-repo changes','A pergunta desaparece de vez — um grafo de build, uma execução de testes, mudanças atômicas entre repos'),
           ('Every later shared module is free, and this epic will want more of them','Todo módulo compartilhado futuro sai de graça, e este épico vai querer mais deles')],
   'cons':[('It is not this task: it changes CI, deploys, and the branching model of three repos at once','Não é esta task: muda CI, deploys e o modelo de branches de três repos de uma vez'),
           ('Every agent, skill and runbook that assumes the current layout has to be rewritten','Todo agente, skill e runbook que presume o layout atual precisa ser reescrito'),
           ('Nothing in this epic is blocked by the layout, so the cost lands entirely outside the benefit','Nada neste épico está bloqueado pelo layout, então o custo cai inteiramente fora do benefício')],
   'cost':[('',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('hi',('Ours: <b>CI, deploys and branching, for three repos</b>','Nosso: <b>CI, deploys e branches, de três repos</b>'))]},
 ],
 'rec':('<p><strong>A, the shared package — and B only if the release step is judged unaffordable.</strong> The two modules are pure and dependency-free, which is precisely the case the package tax is smallest for; and the thing being protected is not a helper, it is <em>the answer to what runs next</em>. A disagreement there is not a bug report, it is two systems executing different graphs.</p>'
        '<p>The <code>thirdPartyIntegration</code> precedent does not carry: it chose copy-port for adapter code that dragged heavy dependencies, and the spec says so explicitly. Reusing its conclusion without its reason is exactly the drift this decision is about.</p>'
        '<p>If B wins, it wins on one condition — <strong>name where the drift test runs</strong>. The back has no CI test run (PLAN §3.5), and a test nobody executes is a comment with extra steps. And if the drift test cannot be made to fail automatically at all, the spec already settles it: copy-port is not viable, and the answer is A.</p>'
        '<p>One answer for both modules is simpler to explain. If they must diverge, the <strong>scheduler</strong> is the one that may not drift.</p>',
        '<p><strong>A, o pacote compartilhado — e B apenas se o passo de release for considerado caro demais.</strong> Os dois módulos são puros e sem dependências, que é exatamente o caso em que o imposto do pacote é menor; e o que está sendo protegido não é um helper, é <em>a resposta sobre o que roda em seguida</em>. Uma discordância ali não é um relatório de bug, são dois sistemas executando grafos diferentes.</p>'
        '<p>O precedente do <code>thirdPartyIntegration</code> não se transfere: ele escolheu copy-port para código adaptador que arrastava dependências pesadas, e a spec diz isso explicitamente. Reaproveitar a conclusão sem a razão é justamente a divergência de que esta decisão trata.</p>'
        '<p>Se a B vencer, vence sob uma condição — <strong>nomear onde o teste de divergência roda</strong>. O back não tem execução de teste no CI (PLAN §3.5), e um teste que ninguém executa é um comentário com passos extras. E se o teste de divergência não puder falhar automaticamente, a spec já resolve: copy-port não é viável, e a resposta é A.</p>'
        '<p>Uma resposta para os dois módulos é mais simples de explicar. Se precisarem divergir, o <strong>scheduler</strong> é o que não pode divergir.</p>'),
 'who':[('Engineering','Engenharia'),('Infra owns the registry and the runner','Infra decide registry e executor')],
}
