# -*- coding: utf-8 -*-

B3 = dict(
 TITLE=('The consumer resolves its own input','O consumidor resolve a própria entrada'),
 GOAL=('Stop the API from pre-chewing every node&#x27;s input. The worker resolves each node&#x27;s <b>placeholders</b> by reference — <b>fetch, then substitute</b>: a <code>node_executions</code> row, a claim-check payload in S3, or the run&#x27;s snapshot. No transformation, no extraction, no OCR (confirmed 2026-09-02, refined 2026-10-09).',
       'Parar de a API pré-mastigar a entrada de cada node. O worker resolve os <b>placeholders</b> de cada node por referência — <b>buscar e substituir</b>: uma linha de <code>node_executions</code>, um payload do claim check no S3, ou o snapshot do run. Sem transformação, sem extração, sem OCR (confirmado em 2026-09-02, refinado em 2026-10-09).'),
 GLANCE=[
  ('crit',('Risk','Risco'),('A placeholder that stops resolving','Um placeholder que para de resolver'),
   ('Every placeholder that resolves today must resolve to the same value after the move. One that fails because the worker could not fetch it must fail loudly, never as an empty string.',
    'Todo placeholder que resolve hoje precisa resolver para o mesmo valor depois da mudança. Um que falhe porque o worker não conseguiu buscá-lo precisa falhar alto, nunca como string vazia.')),
  ('dep',('Depends on','Depende de'),('B1, B2','B1, B2'),
   ('Blocks B4. Decision <strong>D2</strong> answered 2026-10-09: the prefetch executor is a stopgap.',
    'Bloqueia a B4. Decisão <strong>D2</strong> respondida em 2026-10-09: o executor de prefetch é paliativo.')),
  ('wave',('Wave','Onda'),('Wave 4','Onda 4'),
   ('While the API owns input resolution, the worker cannot own the graph — every node needs a round trip through the back to become runnable.',
    'Enquanto a API for dona da resolução de entrada, o worker não pode ser dono do grafo — todo node precisa de uma ida e volta ao back para ficar executável.')),
  ('ship',('Measured','Medido'),('78 of 15,984 flows · ~73 min of traffic','78 de 15.984 fluxos · ~73 min de tráfego'),
   ('Prefetch-eligible flows in production (A1), and how long <code>FLUX_EXEC_MEMORY_MODE_PROD</code> was ever <code>prefetch</code> (SSM parameter history, 2026-08-20).',
    'Fluxos elegíveis ao prefetch em produção (A1), e quanto tempo o <code>FLUX_EXEC_MEMORY_MODE_PROD</code> esteve em <code>prefetch</code> (histórico do parâmetro no SSM, 20/08/2026).')),
 ],
 LEDE=('<p>Today the API resolves a node&#x27;s input and pre-saves it before dispatch: on apiV2, <code>processNodeViaTemporal</code> writes <code>node_executions.input</code> through <code>createNodeExecution</code>, and the worker only reads it — <code>fetch-node-row.ts</code> selects <code>input</code> when <code>execId</code> is present.</p>'
       '<p><strong>Corrected 2026-10-09.</strong> This page used to say the prefetch executor was the part already built. It is not: it resolves in the back and dispatches through the back&#x27;s own handlers, so it was never a consumer-side resolver. And resolving an input turned out to be <strong>two different actions</strong>, only one of which is fetch.</p>',
       '<p>Hoje a API resolve a entrada de um node e a pré-salva antes do dispatch: no apiV2, o <code>processNodeViaTemporal</code> grava <code>node_executions.input</code> pelo <code>createNodeExecution</code>, e o worker apenas lê — o <code>fetch-node-row.ts</code> seleciona <code>input</code> quando há <code>execId</code>.</p>'
       '<p><strong>Corrigido em 09/10/2026.</strong> Esta página dizia que o executor de prefetch era a parte já construída. Não é: ele resolve no back e despacha pelos handlers do próprio back, então nunca foi um resolvedor do lado do consumidor. E resolver uma entrada se mostrou <strong>duas ações diferentes</strong>, e só uma delas é busca.</p>'),
 L1=('What resolving an input does today','O que resolver uma entrada faz hoje'),
 TABLES=[
  dict(head=[('Operation','Operação'),('What it does','O que faz'),('After B3','Depois da B3')],
   rows=[
    [{'t':'applySubstitutionToObject','mono':True},
     ('Walks the whole node <code>data</code> — strings inside the <code>*Data</code> arrays included — and replaces <code>{{...}}</code>','Percorre todo o <code>data</code> do node — inclusive as strings dentro dos arrays <code>*Data</code> — e troca os <code>{{...}}</code>'),
     ('<strong>Worker.</strong> Fetch, then substitute','<strong>Worker.</strong> Buscar e substituir')],
    [{'t':'resolveTextDataFromSchema','mono':True},
     ('Fills the <code>text</code> of each <code>{id}</code> entry in <code>REF_ARRAY_FIELDS</code> from the upstream with that id','Preenche o <code>text</code> de cada entrada <code>{id}</code> dos <code>REF_ARRAY_FIELDS</code> a partir do upstream com aquele id'),
     ('<strong>Worker.</strong> A lookup by reference','<strong>Worker.</strong> Uma busca por referência')],
    [{'t':'syncPassthroughsFromNodes','mono':True},
     ('Lets passthrough nodes carry their upstream&#x27;s value','Faz os nodes passthrough carregarem o valor do upstream'),
     ('<strong>Worker.</strong> Part of building the schema','<strong>Worker.</strong> Parte de montar o schema')],
    [{'t':'getOutputByType','mono':True},
     ('When an upstream completes, writes an entry into the downstream&#x27;s <code>*Data</code>, choosing which field of the upstream each handle stands for — a pure selection over data already in <code>node_executions.outputData</code>','Quando um upstream completa, grava uma entrada nos <code>*Data</code> do downstream, escolhendo qual campo do upstream cada handle representa — uma seleção pura sobre dados que já estão em <code>node_executions.outputData</code>'),
     ('<strong>Worker, in B3b.</strong> Field selection by handle','<strong>Worker, na B3b.</strong> Seleção de campo por handle')],
   ]),
 ],
 PROSE1=('Nothing fails loudly today. An unknown key stays as the literal <code>{{x.y}}</code>, and because every output is blanked at run start, a reference to an upstream that has not run in this run resolves to <code>&#x27;&#x27;</code>. <strong>That empty string is relied-on behaviour</strong> — a branch that did not run — so it has to survive the move, and only the failure the move can introduce becomes an error.',
         'Nada falha alto hoje. Uma chave desconhecida fica como o literal <code>{{x.y}}</code>, e como toda saída é zerada no início do run, uma referência a um upstream que não rodou neste run resolve para <code>&#x27;&#x27;</code>. <strong>Essa string vazia é comportamento de que se depende</strong> — um ramo que não rodou — então ela precisa sobreviver à mudança, e só a falha que a mudança pode introduzir vira erro.'),
 DECINTRO=('One decision, and it is now answered with both halves of the measurement in hand.',
           'Uma decisão, e agora ela está respondida com as duas metades da medição em mãos.'),
 LPARTS=('What the task does, in four parts','O que a task faz, em quatro partes'),
 PARTS=[
  {'n':'1','title':('Placeholders resolve in the worker','Os placeholders resolvem no worker'),
   'loc':'flux.service.ts · fetch-node-row.ts · worker/src/ported/back',
   'purpose':('The back writes the node&#x27;s data with its placeholders <strong>unresolved</strong>; the worker fetches what they point at and substitutes.',
              'O back grava o data do node com os placeholders <strong>sem resolver</strong>; o worker busca o que eles apontam e substitui.'),
   'body':('<p>The worker runs the three fetch operations on B2&#x27;s ported <code>NodeReferenceSubstitutionService</code>, including on placeholders that arrive inside the <code>*Data</code> arrays. <code>node_executions.input</code> stops being a precondition for running and becomes a record of what the node ran with: the worker writes the resolved input back, because run history and the front read it.</p>'
           '<p>Every placeholder that resolves today must resolve to the same value. If one stops resolving because the worker cannot fetch what it points at, that is a defect of this task, not an accepted loss.</p>',
           '<p>O worker roda as três operações de busca sobre o <code>NodeReferenceSubstitutionService</code> portado na B2, inclusive nos placeholders que chegam dentro dos arrays <code>*Data</code>. O <code>node_executions.input</code> deixa de ser pré-condição para rodar e passa a ser registro do que o node rodou: o worker grava de volta a entrada resolvida, porque o histórico de runs e o front a leem.</p>'
           '<p>Todo placeholder que resolve hoje precisa resolver para o mesmo valor. Se um parar de resolver porque o worker não consegue buscar o que ele aponta, isso é defeito desta task, não perda aceita.</p>'),
   'ba':(('The back substitutes every placeholder and writes the resolved input; the worker reads it.',
          'O back substitui todo placeholder e grava a entrada resolvida; o worker a lê.'),
         ('Behind a flag defaulting off, the worker substitutes from references and records what it ran with. The back&#x27;s path stays selectable.',
          'Atrás de uma flag desligada por padrão, o worker substitui a partir de referências e registra com o que rodou. O caminho do back continua selecionável.')),
   'callouts':[('decide',('Fetch, and only fetch','Fetch, e só fetch'),
     ('<p>Confirmed with the requester on 2026-09-02 and refined on 2026-10-09: the consumer loads what it needs through a reference — a <code>node_executions</code> row, or a claim-check payload through <code>get-payload</code> (the boundary S5 authorises) — and <strong>fetch-then-substitute is fetch</strong>. Selecting the field a handle stands for is fetch too, and moves in B3b. Extraction and OCR stay out (A8, D24).</p>',
      '<p>Confirmado com quem pediu em 2026-09-02 e refinado em 2026-10-09: o consumidor carrega o que precisa por uma referência — uma linha de <code>node_executions</code>, ou um payload do claim check pelo <code>get-payload</code> (a fronteira que a S5 autoriza) — e <strong>buscar e substituir é busca</strong>. Selecionar o campo que um handle representa também é busca, e vai na B3b. Extração e OCR ficam de fora (A8, D24).</p>')),
    ('mig',('The edge projection moves in B3b','A projeção das arestas vai na B3b'),
     ('<p>In B3 the back keeps building the <code>*Data</code> entries (<code>getOutputByType</code>) and writes them with their placeholders unresolved. <strong>B3b</strong> moves that step to the worker on the same flag, so B4 needs no back callback per node.</p>',
      '<p>Na B3 o back continua montando as entradas <code>*Data</code> (<code>getOutputByType</code>) e as grava com os placeholders sem resolver. A <strong>B3b</strong> move esse passo para o worker na mesma flag, então a B4 não precisa de callback ao back por node.</p>'))]},
  {'n':'2','title':('A minimal snapshot per run','Um snapshot mínimo por run'),
   'loc':('generateSchemaFromNodes · the run snapshot (new)', 'generateSchemaFromNodes · o snapshot do run (novo)'),
   'purpose':('A placeholder can point at a node that does not execute in this run, and today it resolves from that node&#x27;s content.',
              'Um placeholder pode apontar para um node que não executa neste run, e hoje ele resolve pelo conteúdo daquele node.'),
   'body':('<p>The substitution schema is built at run start from every node in the flow. Reading the same values from the live <code>flows_nodes</code> row later would pick up whatever a concurrent run wrote. The back records the run-start base once per run and hands the worker a reference to it.</p>'
           '<p>The snapshot holds only what substitution reads. Chat history and starter files reach the node through the input the back still writes.</p>',
           '<p>O schema de substituição é montado no início do run a partir de todos os nodes do fluxo. Ler os mesmos valores da linha viva do <code>flows_nodes</code> mais tarde pegaria o que um run concorrente gravou. O back registra a base do início uma vez por run e passa ao worker uma referência para ela.</p>'
           '<p>O snapshot guarda só o que a substituição lê. Histórico de chat e arquivos do starter chegam ao node pela entrada que o back continua gravando.</p>'),
   'ba':(('The base lives in the back&#x27;s memory for the life of the run.','A base vive na memória do back durante o run.'),
         ('The base is recorded once per run and read by reference, so two concurrent runs never see each other&#x27;s values.','A base é registrada uma vez por run e lida por referência, então dois runs concorrentes nunca veem os valores um do outro.'))},
  {'n':'3','title':('Finding the run&#x27;s upstreams','Achar os upstreams do run'),
   'loc':('the dispatch arguments', 'os argumentos do dispatch'),
   'purpose':('<code>node_executions</code> has no indexed run key, and B1 adds none.',
              'O <code>node_executions</code> não tem chave de run indexada, e a B1 não cria nenhuma.'),
   'body':('<p>The dispatch carries the run&#x27;s completed <code>{ nodeId: execId }</code> map — ids only. That is the shape B4&#x27;s workflow will hold in its state, so B4 inherits it instead of replacing it. The worker applies the upstream outputs <strong>in completion order</strong>, because label aliases are last-write-wins and the order decides which node a shared label names.</p>',
           '<p>O dispatch leva o mapa <code>{ nodeId: execId }</code> dos nodes já completados no run — só ids. É o formato que o workflow da B4 vai guardar no estado, então a B4 o herda em vez de substituí-lo. O worker aplica as saídas dos upstreams <strong>na ordem em que completaram</strong>, porque os aliases de label são last-write-wins e a ordem decide qual node um label repetido nomeia.</p>'),
   'ba':(('Upstream values come from the back&#x27;s in-memory schema.','Os valores dos upstreams vêm do schema em memória do back.'),
         ('Upstream values come from their own rows, found by id.','Os valores dos upstreams vêm das próprias linhas, achadas por id.'))},
  {'n':'4','title':('Equivalence, on every key shape','Equivalência, em toda forma de chave'),
   'loc':('the substitution module from B2', 'o módulo de substituição, vindo da B2'),
   'purpose':('Both paths are run over stored runs and the full <code>data</code> is diffed — or the task is not done.',
              'Os dois caminhos rodam sobre runs guardados e o <code>data</code> inteiro é comparado — ou a task não está pronta.'),
   'body':('<p>Cover the three key shapes (<code>nodeId</code>, normalised ref-key, lowercased label alias), passthrough nodes, a placeholder inside a <code>*Data</code> entry, and two nodes sharing a label. The service and the prefetch <code>alias-index</code> resolve that collision differently; the worker must match the service, because that is what production runs.</p>',
           '<p>Cubra as três formas de chave (<code>nodeId</code>, ref-key normalizada, alias de label em minúsculas), nodes passthrough, um placeholder dentro de uma entrada <code>*Data</code>, e dois nodes com o mesmo label. O serviço e o <code>alias-index</code> do prefetch resolvem essa colisão de jeitos diferentes; o worker precisa bater com o serviço, porque é ele que roda em produção.</p>'),
   'ba':(('One implementation resolves placeholders, so nothing compares them.','Uma implementação resolve placeholders, então nada as compara.'),
         ('Both are diffed over stored runs, collision and <code>*Data</code> included.','As duas são comparadas sobre runs guardados, colisão e <code>*Data</code> incluídos.'))},
 ],
 VERIF=[
  (True,('Negative control','Controle negativo'),
   ('On the new path, withhold the <code>node_executions</code> row of an upstream that <strong>did</strong> complete in this run, and confirm the node fails loudly instead of resolving to <code>&#x27;&#x27;</code> or to the literal placeholder. <strong>This is the failure the move can introduce, and it must never look like a prompt bug.</strong>',
    'No caminho novo, retenha a linha de <code>node_executions</code> de um upstream que <strong>completou</strong> neste run, e confirme que o node falha alto em vez de resolver para <code>&#x27;&#x27;</code> ou para o placeholder literal. <strong>Esta é a falha que a mudança pode introduzir, e ela nunca pode parecer um bug de prompt.</strong>')),
  (False,('Today&#x27;s empty results stay empty','Os vazios de hoje continuam vazios'),
   ('A reference to an upstream that did not run in this run resolves to <code>&#x27;&#x27;</code> today and must still do so. Measure how many stored flows rely on it before turning anything into an error.',
    'Uma referência a um upstream que não rodou neste run resolve para <code>&#x27;&#x27;</code> hoje e precisa continuar assim. Meça quantos fluxos guardados dependem disso antes de transformar qualquer coisa em erro.')),
  (False,('Output equivalence over real flows','Equivalência de saída sobre fluxos reais'),
   ('Resolve each node&#x27;s input <strong>both ways and diff the full <code>data</code></strong> — the three key shapes, passthroughs, placeholders inside <code>*Data</code>, and the alias collision.',
    'Resolva a entrada de cada node <strong>pelos dois caminhos e compare o <code>data</code> inteiro</strong> — as três formas de chave, passthroughs, placeholders dentro de <code>*Data</code>, e a colisão de alias.')),
  (False,('Concurrency','Concorrência'),
   ('Two runs of the same flow with different starter inputs: each node resolves its own run&#x27;s values.',
    'Dois runs do mesmo fluxo com entradas de starter diferentes: cada node resolve os valores do próprio run.')),
  (False,('Measure before refusing','Medir antes de recusar'),
   ('<strong>PLAN §3.3.2.</strong> Whatever gate decides &#x27;this flow can resolve worker-side&#x27; is a refusing rule. Classify every refusal against real stored flows and drive <em>refused-although-it-works</em> to <strong>zero</strong>.',
    '<strong>PLAN §3.3.2.</strong> O portão que decide &#x27;este fluxo pode resolver no worker&#x27; é uma regra que recusa. Classifique toda recusa contra fluxos reais guardados e leve <em>recusada-embora-funcione</em> a <strong>zero</strong>.')),
 ],
 DONE=('Behind a flag defaulting off, the worker resolves <strong>every placeholder</strong> of a node&#x27;s input from references, with no substitution in the back; equivalence is proven over stored runs; the back&#x27;s path is still present and selectable; and the <code>*Data</code> entries are still built by the back until B3b lands.',
       'Atrás de uma flag desligada por padrão, o worker resolve <strong>todo placeholder</strong> da entrada de um node a partir de referências, sem substituição no back; a equivalência está provada sobre runs guardados; o caminho do back continua presente e selecionável; e as entradas <code>*Data</code> continuam sendo montadas pelo back até a B3b entrar.'),
 FILES=[('back/src/app-api/flux/flux.service.ts',False),
        ('back/src/app-api/flux/ref-array-fields.ts',False),
        ('worker/src/modules/nodes/shared/fetch-node-row.ts',False),
        ('worker/src/ported/back/ (B2)',False),
        ('worker-side resolution (new)',True),
        ('the run snapshot (new)',True)],
)

B3_DEC = {
 'k':'decision','id':'B3-a','plan':'D2','status':'set','open':True,
 'q':('Is the prefetch executor the destination for worker-side input resolution, or a stopgap to retire?',
      'O executor de prefetch é o destino da resolução de entrada no worker, ou um paliativo a aposentar?'),
 'intro':('<strong>D2 in <code>PLAN.md</code> §7.</strong> A1 counted eligibility: <strong>78 of 15,984</strong> production flows satisfy <code>canUsePrefetchForFlow</code>. It reported usage as unverifiable, because CloudWatch Logs Insights is not enabled. The SSM parameter history answers it instead: <code>FLUX_EXEC_MEMORY_MODE_PROD</code> was <code>prefetch</code> for <strong>about 73 minutes</strong> on 2026-08-20 and <code>legacy</code> ever since, in dev and staging too.',
          '<strong>A D2 do <code>PLAN.md</code> §7.</strong> A A1 contou a elegibilidade: <strong>78 de 15.984</strong> fluxos de produção satisfazem o <code>canUsePrefetchForFlow</code>. O uso ficou como não verificável, porque o CloudWatch Logs Insights não está habilitado. O histórico do parâmetro no SSM responde: o <code>FLUX_EXEC_MEMORY_MODE_PROD</code> esteve em <code>prefetch</code> por <strong>cerca de 73 minutos</strong> em 20/08/2026 e em <code>legacy</code> desde então, em dev e staging também.'),
 'opts':[
  {'ltr':'A','no':True,'name':('Destination — widen it and relocate it','Destino — ampliar e realocar'),
   'tag':('not chosen','não escolhida'),
   'how':('Widen the whitelist as the A track lands and move the executor to the worker side.',
          'Ampliar a whitelist conforme a trilha A entrega e mover o executor para o lado do worker.'),
   'pros':[('Its pure pieces — <code>scanPlaceholderRefs</code>, <code>loadOutputsByRefs</code>, <code>buildAliasIndex</code> — are reusable as libraries','As peças puras — <code>scanPlaceholderRefs</code>, <code>loadOutputsByRefs</code>, <code>buildAliasIndex</code> — são reaproveitáveis como biblioteca')],
   'cons':[('It resolves in the back and dispatches through the back&#x27;s handlers: relocating it means rewriting it','Ele resolve no back e despacha pelos handlers do back: realocá-lo significa reescrevê-lo'),
           ('It has carried about 73 minutes of production traffic, ever — nothing proves it works','Carregou cerca de 73 minutos de tráfego de produção, no total — nada prova que funciona'),
           ('Its pointer map lives in the back&#x27;s process memory','O mapa de ponteiros dele vive na memória do processo do back')]},
  {'ltr':'B','pick':True,'name':('Stopgap — resolve in the worker, retire the executor','Paliativo — resolver no worker, aposentar o executor'),
   'tag':('settled','decidida'),
   'how':('The worker resolves placeholders on the substitution service B2 ported, and C2 retires the prefetch path.',
          'O worker resolve os placeholders com o serviço de substituição que a B2 portou, e a C2 aposenta o caminho de prefetch.'),
   'pros':[('One resolver, and it is the code production runs today','Um resolvedor, e é o código que a produção roda hoje'),
           ('The worker already has Postgres, <code>get-payload</code> and <code>resolveClaimRef</code>','O worker já tem Postgres, <code>get-payload</code> e <code>resolveClaimRef</code>'),
           ('The retirement already has an owner: C2','A aposentadoria já tem dono: a C2')],
   'cons':[('The worker must match the service exactly, alias collision included','O worker precisa bater exatamente com o serviço, colisão de alias inclusa')]},
  {'ltr':'C','no':True,'name':('Do not decide yet','Não decidir ainda'),
   'tag':('superseded','superada'),
   'how':('Wait for A1&#x27;s count. Both halves of the count now exist.',
          'Esperar a contagem da A1. As duas metades da contagem agora existem.')},
 ],
 'rec':('<p><strong>B, and it is decided (2026-10-09).</strong> This page recommended C — measure first, and choose B if the number never arrives. The number arrived: 0.5% of flows eligible, and the flag on in production for about 73 minutes. A path that has never carried traffic is not a destination.</p>',
        '<p><strong>B, e está decidido (09/10/2026).</strong> Esta página recomendava a C — medir antes, e escolher a B se o número nunca chegasse. O número chegou: 0,5% dos fluxos elegíveis, e a flag ligada em produção por cerca de 73 minutos. Um caminho que nunca carregou tráfego não é um destino.</p>'),
 'who':[('Engineering','Engenharia'),('B3 answered with A1&#x27;s count and the SSM history','A B3 respondeu com a contagem da A1 e o histórico do SSM')],
}

B3B = dict(
 TITLE=('Edge projection in the worker','Projeção das arestas no worker'),
 GOAL=('The worker builds each node&#x27;s <code>*Data</code> arrays from its upstreams&#x27; <code>node_executions</code> rows, so that <b>no node needs a round trip through the back to become runnable</b>. Split out of B3 on 2026-10-09.',
       'O worker monta os arrays <code>*Data</code> de cada node a partir das linhas de <code>node_executions</code> dos upstreams, para que <b>nenhum node precise de uma ida e volta ao back para ficar executável</b>. Separada da B3 em 09/10/2026.'),
 GLANCE=[
  ('crit',('Risk','Risco'),('A handle that delivers something else','Um handle que entrega outra coisa'),
   ('Every source/handle pair must produce byte-identical entries — the console join and the default strings are product behaviour.',
    'Todo par origem/handle precisa produzir entradas idênticas byte a byte — a junção do console e os textos padrão são comportamento do produto.')),
  ('dep',('Depends on','Depende de'),('B2, B3','B2, B3'),
   ('Blocks B4. Uses B2&#x27;s sync and drift test, and B3&#x27;s flag and upstream map.',
    'Bloqueia a B4. Usa o sync e o teste de divergência da B2, e a flag e o mapa de upstreams da B3.')),
  ('wave',('Wave','Onda'),('Wave 4','Onda 4'),
   ('Once the loop is a workflow the back no longer holds the node list, so a projection left there becomes a callback per node.',
    'Quando o laço vira workflow o back deixa de ter a lista de nodes, então uma projeção deixada ali vira um callback por node.')),
  ('ship',('Size','Tamanho'),('~1,070 lines','~1.070 linhas'),
   ('Inside a 2,337-line <code>helpers.ts</code> that is not pure — the same file B2 had to extract <code>singleConditionCheck</code> from.',
    'Dentro de um <code>helpers.ts</code> de 2.337 linhas que não é puro — o mesmo arquivo do qual a B2 precisou extrair o <code>singleConditionCheck</code>.')),
 ],
 LEDE=('<p>When a node completes, the back walks the edges leaving it and, for each one, decides <strong>which field of the source the handle stands for</strong>, then writes a <code>{ id, label, text }</code> entry into the target&#x27;s <code>*Data</code> array (<code>addConnectToNodes</code> → <code>givingDataToNode</code> / <code>getOutputByType</code>, <code>helpers.ts:20</code>).</p>'
       '<p>B3 first read this as a transform and left it in the back. It is <strong>field selection by handle</strong>: a pure function of the edge, the source&#x27;s output and the loop iteration, over data both writers already store in <code>node_executions.outputData</code>. It lives in the back only because the loop does.</p>',
       '<p>Quando um node completa, o back percorre as arestas que saem dele e, para cada uma, decide <strong>qual campo da origem o handle representa</strong>, e grava uma entrada <code>{ id, label, text }</code> no array <code>*Data</code> do destino (<code>addConnectToNodes</code> → <code>givingDataToNode</code> / <code>getOutputByType</code>, <code>helpers.ts:20</code>).</p>'
       '<p>A B3 leu isso como transformação e deixou no back. É <strong>seleção de campo por handle</strong>: uma função pura da aresta, da saída da origem e da iteração do loop, sobre dados que os dois gravadores já guardam em <code>node_executions.outputData</code>. Só mora no back porque o laço mora.</p>'),
 L1=('What the projection selects today','O que a projeção seleciona hoje'),
 TABLES=[
  dict(head=[('Source · handle','Origem · handle'),('What becomes the entry&#x27;s text','O que vira o texto da entrada'),('Where the worker reads it','Onde o worker lê')],
   rows=[
    [{'t':'scripting · output','mono':True},('<code>data.result</code>','<code>data.result</code>'),('upstream <code>outputData</code>','<code>outputData</code> do upstream')],
    [{'t':'scripting · console','mono':True},('<code>data.console</code>, lines joined with a newline','<code>data.console</code>, linhas unidas por quebra de linha'),('upstream <code>outputData</code>','<code>outputData</code> do upstream')],
    [{'t':'commandTextNode · fileLink','mono':True},('<code>data.fileLink.src</code>, or <code>&#x27;No Link generated&#x27;</code>','<code>data.fileLink.src</code>, ou <code>&#x27;No Link generated&#x27;</code>'),('upstream <code>outputData</code>','<code>outputData</code> do upstream')],
    [{'t':'commandTextNode · logs','mono':True},('<code>data.logs</code>, or <code>&#x27;No Logs generated&#x27;</code>','<code>data.logs</code>, ou <code>&#x27;No Logs generated&#x27;</code>'),('upstream <code>outputData</code>','<code>outputData</code> do upstream')],
    [{'t':'nodesBox · arrayNode · fluxBox','mono':True},('Values held in the back&#x27;s memory (<code>objectCallerData</code>, iterations, sub-runs)','Valores mantidos na memória do back (<code>objectCallerData</code>, iterações, sub-runs)'),('<strong>Not available.</strong> Stays on the back&#x27;s path until B6','<strong>Indisponível.</strong> Fica no caminho do back até a B6')],
   ]),
 ],
 PROSE1=('The only formatting is the console join and the default strings, and those are what the product promised each handle delivers. <strong>Port it, do not rewrite it</strong> — a rewrite is a second copy of the rule, and a second copy drifts silently.',
         'A única formatação é a junção do console e os textos padrão, e é isso que o produto prometeu que cada handle entrega. <strong>Portar, não reescrever</strong> — reescrever é uma segunda cópia da regra, e uma segunda cópia diverge em silêncio.'),
 LPARTS=('What the task does, in three parts','O que a task faz, em três partes'),
 PARTS=[
  {'n':'1','title':('Extract it pure','Extrair puro'),
   'loc':'helpers.ts · contants.ts · loop-iteration-context.ts',
   'purpose':('Behaviour-neutral, the way B2 extracted <code>singleConditionCheck</code> from the same file.',
              'Sem mudar comportamento, do jeito que a B2 extraiu o <code>singleConditionCheck</code> do mesmo arquivo.'),
   'body':('<p><code>getOutputByType</code>, <code>givingDataToNode</code>, <code>modifyData</code>, <code>addConnectToNodes</code>, <code>buildHandleEntryIdForWrite</code> and <code>reconcileEntries</code> move into a module with no impure imports. The loop iteration becomes an explicit argument instead of an <code>AsyncLocalStorage</code> read. The back keeps importing from the new module at its fourteen call sites.</p>',
           '<p><code>getOutputByType</code>, <code>givingDataToNode</code>, <code>modifyData</code>, <code>addConnectToNodes</code>, <code>buildHandleEntryIdForWrite</code> e <code>reconcileEntries</code> vão para um módulo sem imports impuros. A iteração do loop vira argumento explícito em vez de leitura do <code>AsyncLocalStorage</code>. O back continua importando do módulo novo nos seus catorze pontos de chamada.</p>'),
   'ba':(('Inside a 2,337-line file that imports the execution budget and an <code>AsyncLocalStorage</code>.','Dentro de um arquivo de 2.337 linhas que importa o orçamento de execução e um <code>AsyncLocalStorage</code>.'),
         ('A pure module the back imports and the worker can carry.','Um módulo puro que o back importa e o worker pode carregar.'))},
  {'n':'2','title':('Carry it with a drift test','Levar com teste de divergência'),
   'loc':'scripts/sync-ported-engine.ts · worker/src/ported/back',
   'purpose':('The worker gets a byte-for-byte copy through B2&#x27;s sync, and both drift tests cover it.',
              'O worker recebe uma cópia byte a byte pelo sync da B2, e os dois testes de divergência a cobrem.'),
   'body':('<p>Import the rule; never restate it. The back stays the source.</p>',
           '<p>Importe a regra; nunca a reescreva. O back continua sendo a fonte.</p>'),
   'ba':(('One implementation, in the back only.','Uma implementação, só no back.'),
         ('The same code in both repos, and a test that goes red when they differ.','O mesmo código nos dois repos, e um teste que fica vermelho quando divergem.'))},
  {'n':'3','title':('Run it in the worker','Rodar no worker'),
   'loc':('on B3&#x27;s flag','na flag da B3'),
   'purpose':('The worker builds the target&#x27;s <code>*Data</code> from the upstreams&#x27; rows, then B3 resolves the placeholders over the result.',
              'O worker monta os <code>*Data</code> do destino a partir das linhas dos upstreams, e então a B3 resolve os placeholders sobre o resultado.'),
   'body':('<p>The upstreams are found through the run&#x27;s completed <code>{ nodeId: execId }</code> map B3 introduces. A flow with an edge from a back-only source stays on the back&#x27;s path — a refusing rule, measured before it ships.</p>',
           '<p>Os upstreams são achados pelo mapa <code>{ nodeId: execId }</code> dos nodes completados que a B3 introduz. Um fluxo com aresta saindo de uma origem que só existe no back fica no caminho do back — uma regra que recusa, medida antes de entrar.</p>'),
   'ba':(('The back writes the projected <code>*Data</code> into the input before dispatch.','O back grava os <code>*Data</code> projetados na entrada antes do dispatch.'),
         ('The worker projects from references; B4 needs no callback per node.','O worker projeta a partir de referências; a B4 não precisa de callback por node.'))},
 ],
 VERIF=[
  (True,('Negative control','Controle negativo'),
   ('Change one branch of the ported copy (for example the console join separator) and watch the drift test go red. Then remove an upstream&#x27;s <code>outputData</code> on the new path and confirm the node fails loudly instead of receiving an empty entry.',
    'Mude um ramo da cópia portada (por exemplo o separador da junção do console) e veja o teste de divergência ficar vermelho. Depois remova o <code>outputData</code> de um upstream no caminho novo e confirme que o node falha alto em vez de receber uma entrada vazia.')),
  (False,('Equivalence over real flows','Equivalência sobre fluxos reais'),
   ('Build every node&#x27;s <code>*Data</code> both ways over stored runs and diff: every source/handle pair in the corpus, the default strings, loop iterations (<code>#N</code> ids) and an edge disconnected between runs.',
    'Monte os <code>*Data</code> de cada node pelos dois caminhos sobre runs guardados e compare: todo par origem/handle do corpus, os textos padrão, iterações de loop (ids <code>#N</code>) e uma aresta desconectada entre runs.')),
  (False,('Measure before refusing','Medir antes de recusar'),
   ('<strong>PLAN §3.3.2.</strong> The gate that keeps back-only sources on the back&#x27;s path refuses flows. Classify every refusal against stored flows and drive <em>refused-although-it-works</em> to <strong>zero</strong>.',
    '<strong>PLAN §3.3.2.</strong> O portão que mantém origens só-do-back no caminho do back recusa fluxos. Classifique toda recusa contra fluxos guardados e leve <em>recusada-embora-funcione</em> a <strong>zero</strong>.')),
 ],
 DONE=('On B3&#x27;s flag, the worker builds every <code>*Data</code> entry from references for flows without back-only sources; equivalence is proven over stored runs; the projection exists once, extracted and ported with a drift test; and the back&#x27;s path is still present and selectable.',
       'Na flag da B3, o worker monta toda entrada <code>*Data</code> a partir de referências para fluxos sem origens só-do-back; a equivalência está provada sobre runs guardados; a projeção existe uma vez, extraída e portada com teste de divergência; e o caminho do back continua presente e selecionável.'),
 FILES=[('back/src/app-api/folw/helpers/helpers.ts',False),
        ('back/src/app-api/folw/contants.ts',False),
        ('back/src/app-api/folw/helpers/loop-iteration-context.ts',False),
        ('back/scripts/sync-ported-engine.ts',False),
        ('worker/src/ported/back/',False),
        ('worker-side projection (new)',True)],
)

B4 = dict(
 TITLE=('Move the DAG loop into a Temporal workflow','Mover o laço do DAG para um workflow do Temporal'),
 GOAL=('The worker owns the execution sequence — and <b>this task ships with no parallelism at all</b>.',
       'O worker passa a ser dono da sequência de execução — e <b>esta task entrega sem nenhum paralelismo</b>.'),
 GLANCE=[
  ('crit',('Risk','Risco'),('Workflow history exhaustion','Esgotamento do histórico do workflow'),
   ('Risk R15 and review §4.1 — one workflow per run, <strong>no <code>continueAsNew</code> anywhere</strong>, terminated by the platform on the largest customer runs first.',
    'Risco R15 e review §4.1 — um workflow por run, <strong>nenhum <code>continueAsNew</code> em lugar algum</strong>, terminado pela plataforma primeiro nos maiores runs de cliente.')),
  ('dep',('Depends on','Depende de'),('B2, B3, B3b','B2, B3, B3b'),
   ('Blocks B5 and B6. Ships in the same wave as <strong>E1</strong>, not before it.',
    'Bloqueia a B5 e a B6. Entra na mesma onda que a <strong>E1</strong>, não antes dela.')),
  ('wave',('Wave','Onda'),('Wave 4','Onda 4'),
   ('Relocating the loop and letting it dispatch more than one node are <strong>two deploys, always</strong>.',
    'Realocar o laço e deixá-lo despachar mais de um node são <strong>dois deploys, sempre</strong>.')),
  ('ship',('Ships','Entrega'),('Sequential, batch size one','Sequencial, lote de um'),
   ('<code>allReady()</code> returning a single id <em>is</em> today&#x27;s behaviour. Nothing gets faster — that is the success criterion.',
    '<code>allReady()</code> devolvendo um único id <em>é</em> o comportamento de hoje. Nada fica mais rápido — esse é o critério de sucesso.')),
 ],
 LEDE=('<p>Two changes hide inside &#x27;move the graph&#x27;: <strong>relocating the loop</strong>, and <strong>letting it dispatch more than one node</strong>. Shipped together, a rollback cannot tell you which one broke the run. Shipped apart, each one is a one-line flag.</p>'
       '<p>Sequential is also nearly free to express: <code>allReady()</code> returning a single id <em>is</em> today&#x27;s behaviour. B4 builds the batch-capable machinery and configures it to a batch size of one. What it does pay back is the blocking wait — <code>await handle.result()</code> at <code>flux.service.ts</code>, which makes every migrated node a synchronous round trip today (analysis §9.2.2).</p>',
       '<p>Duas mudanças se escondem em &#x27;mover o grafo&#x27;: <strong>realocar o laço</strong>, e <strong>deixá-lo despachar mais de um node</strong>. Entregues juntas, um rollback não consegue dizer qual delas quebrou o run. Entregues separadas, cada uma é uma flag de uma linha.</p>'
       '<p>E expressar o modo sequencial é quase de graça: <code>allReady()</code> devolvendo um único id <em>é</em> o comportamento de hoje. A B4 constrói a maquinaria capaz de lote e a configura com lote de tamanho um. O que ela paga de volta é a espera bloqueante — o <code>await handle.result()</code> em <code>flux.service.ts</code>, que hoje faz de cada node migrado uma ida e volta síncrona (análise §9.2.2).</p>'),
 L1=('What already exists, and what B4 does with it','O que já existe, e o que a B4 faz com isso'),
 TABLES=[
  dict(head=[('Asset','O que existe'),('Where','Onde'),('State today','Estado hoje'),('What B4 does with it','O que a B4 faz com ele')],
   rows=[
    [{'t':('The graph itself','O grafo em si')},
     ('<code>flux/scheduler.ts</code>, extracted in <strong>B2</strong>','<code>flux/scheduler.ts</code>, extraído na <strong>B2</strong>'),
     {'t':('Correct and portable','Correto e portável'),'pill':'ok'},
     ('The workflow owns <code>SchedulerState</code> instead of the API','O workflow passa a ser dono do <code>SchedulerState</code> em vez da API')],
    [{'t':('The parallel loop','O laço paralelo')},
     ('<code>worker/src/modules/temporal/workflows/process-agent.workflow.ts</code>','<code>worker/src/modules/temporal/workflows/process-agent.workflow.ts</code>'),
     {'t':('Written, then commented out','Escrito, e comentado'),'pill':'weak'},
     ('<strong>Read it before writing a new one</strong> — in-degree per node, a <code>readyToRun</code> filter, <code>Promise.all</code> over the batch','<strong>Leia antes de escrever outro</strong> — in-degree por node, um filtro <code>readyToRun</code>, <code>Promise.all</code> sobre o lote')],
    [{'t':('The blocking wait','A espera bloqueante')},
     ('<code>back/src/app-api/flux/flux.service.ts</code>','<code>back/src/app-api/flux/flux.service.ts</code>'),
     {'t':('<code>await handle.result()</code> per node','<code>await handle.result()</code> por node'),'pill':'no'},
     ('Removed — this is the task that pays back the round trip in analysis §9.2.2','Removida — esta é a task que paga de volta a ida e volta da análise §9.2.2')],
   ]),
 ],
 PROSE1=('One more thing that already works and must keep working: <code>markCompleted</code> and <code>markDead</code> are <strong>set-based and already tolerate out-of-order completion</strong> — which is exactly what a batch produces. No change is needed there, and changing them would be the fastest way to break a scheduler that is currently correct.',
         'Mais uma coisa que já funciona e precisa continuar funcionando: <code>markCompleted</code> e <code>markDead</code> são <strong>baseados em conjunto e já toleram conclusão fora de ordem</strong> — que é exatamente o que um lote produz. Não é preciso mudar nada ali, e mudá-los seria o jeito mais rápido de quebrar um scheduler que hoje está correto.'),
 DECINTRO=('One decision, and it is the one the architecture review added after the fact. The rest of this task is a port with a flag; this part is a ceiling that does not exist yet anywhere in the worker.',
           'Uma decisão, e é a que a revisão de arquitetura acrescentou depois. O resto desta task é um port com flag; esta parte é um teto que ainda não existe em lugar nenhum do worker.'),
 LPARTS=('What the task does, in three parts','O que a task faz, em três partes'),
 PARTS=[
  {'n':'1','title':('The workflow owns <code>SchedulerState</code>','O workflow passa a ser dono do <code>SchedulerState</code>'),
   'loc':('new flow workflow · scheduler.ts from B2', 'novo workflow de fluxo · scheduler.ts da B2'),
   'purpose':('Everything the API&#x27;s loop does with the scheduler, the workflow does — with a batch size of one.',
              'Tudo o que o laço da API faz com o scheduler, o workflow passa a fazer — com lote de tamanho um.'),
   'body':('<p>The workflow owns the state, calls <code>allReady()</code>, dispatches, and applies <code>markCompleted</code> / <code>markDead</code> / <code>completeCondition</code> as results arrive.</p>'
           '<p><code>allReady(state): string[]</code> is added alongside <code>nextReady</code>, draining every eligible id and marking each <code>scheduled</code>. <strong><code>nextReady</code> stays while the backend loop exists</strong> — it is that loop&#x27;s primitive, and <code>C2</code> retires it with the loop. <code>mcp-write.service.ts</code> uses the scheduler too, but only <code>buildSchedulerState</code> and <code>classifyEdge</code>, so it is unaffected either way. Before writing <code>allReady()</code>, check whether the Temporal SDK offers a primitive for ready-set dispatch; decide during development — <code>D16</code> is unchanged whichever way it goes.</p>'
           '<p>The back&#x27;s role shrinks to three things: <strong>start the flow workflow</strong>, <strong>serve the callbacks it already owns</strong> — billing, model access, S3, file generation — and <strong>read the result</strong>. It stops being the loop. One more thing needs a writer once the loop leaves: <code>flow_execution_status</code> (PR #1902, read by <code>GET /flux/executions/:id</code>) — the workflow reports it through a callback, or <code>E1</code>&#x27;s collector writes it; decide and state it in the PR. A flag selects engine-in-back versus engine-in-workflow, <strong>per flow</strong>, defaulting to back.</p>',
           '<p>O workflow é dono do estado, chama <code>allReady()</code>, despacha, e aplica <code>markCompleted</code> / <code>markDead</code> / <code>completeCondition</code> conforme os resultados chegam.</p>'
           '<p><code>allReady(state): string[]</code> é adicionado ao lado do <code>nextReady</code>, drenando todos os ids elegíveis e marcando cada um como <code>scheduled</code>. <strong>O <code>nextReady</code> fica enquanto o laço do backend existir</strong> — é a primitiva desse laço, e a <code>C2</code> o aposenta junto com o laço. O <code>mcp-write.service.ts</code> também usa o scheduler, mas só <code>buildSchedulerState</code> e <code>classifyEdge</code>, então não é afetado de nenhum jeito. Antes de escrever o <code>allReady()</code>, verifique se o SDK do Temporal já oferece uma primitiva para dispatch por conjunto pronto; decida durante o desenvolvimento — a <code>D16</code> não muda em nenhum dos casos.</p>'
           '<p>O papel do back encolhe para três coisas: <strong>iniciar o workflow do fluxo</strong>, <strong>servir os callbacks de que já é dono</strong> — cobrança, acesso a modelo, S3, geração de arquivo — e <strong>ler o resultado</strong>. Ele deixa de ser o laço. Mais uma coisa precisa de um escritor quando o laço sair: o <code>flow_execution_status</code> (PR #1902, lido por <code>GET /flux/executions/:id</code>) — o workflow o reporta por callback, ou o coletor da <code>E1</code> o escreve; decida e declare no PR. Uma flag seleciona motor-no-back contra motor-no-workflow, <strong>por fluxo</strong>, com padrão no back.</p>'),
   'ba':(('The API&#x27;s loop calls <code>nextReady</code>, dispatches one node, and blocks on <code>await handle.result()</code> before asking for the next one.',
          'O laço da API chama <code>nextReady</code>, despacha um node, e bloqueia em <code>await handle.result()</code> antes de pedir o próximo.'),
         ('The workflow calls <code>allReady()</code> and dispatches the batch it returns — configured to one. <strong>Identical order, no blocking round trip through the back.</strong>',
          'O workflow chama <code>allReady()</code> e despacha o lote devolvido — configurado em um. <strong>Ordem idêntica, sem ida e volta bloqueante pelo back.</strong>')),
   'callouts':[('mig',('What stays out','O que fica de fora'),
     ('<p><strong>Batch size above one</strong> — that is B5, in the next wave. <strong>Control flow and sub-flows</strong> — B6. <strong>Deleting the back&#x27;s loop</strong> — C1/C2, after this has soaked. The backend loop stays in place through this whole wave and is only removed in Wave 6.</p>',
      '<p><strong>Lote acima de um</strong> — isso é a B5, na próxima onda. <strong>Controle de fluxo e sub-fluxos</strong> — B6. <strong>Apagar o laço do back</strong> — C1/C2, depois que isto tiver assentado. O laço do backend permanece durante toda esta onda e só é removido na Onda 6.</p>'))]},
  {'n':'2','title':('History is a storage medium, and it is bounded','O histórico é um meio de armazenamento, e ele tem limite'),
   'loc':('review §4.1 — a gap found after the plan was written', 'review §4.1 — uma lacuna encontrada depois de o plano ser escrito'),
   'purpose':('Two requirements, and neither is optional: <code>continueAsNew</code> at a boundary, and state carried <strong>by reference, never by value</strong>.',
              'Dois requisitos, e nenhum é opcional: <code>continueAsNew</code> num limite, e estado carregado <strong>por referência, nunca por valor</strong>.'),
   'body':('<p>A Temporal workflow accumulates history events, and both the event count and the total size are capped. The worker uses <strong>no <code>continueAsNew</code></strong> anywhere today. One workflow owning an entire flow run therefore grows with every activity scheduled and completed and every value passed — and it will be terminated by the platform on exactly the largest, most valuable customer runs.</p>'
           '<p>The second requirement is where the wave&#x27;s tasks meet: the id-based transport from <strong>B1</strong> is what makes by-reference possible. The workflow carries ids; the payloads stay in Postgres and S3. Passing a resolved input through workflow state would put node output into the history — the same failure by another route.</p>',
           '<p>Um workflow do Temporal acumula eventos de histórico, e tanto a contagem de eventos quanto o tamanho total têm teto. O worker não usa <strong>nenhum <code>continueAsNew</code></strong> hoje. Um workflow dono de um run inteiro, portanto, cresce a cada activity agendada e concluída e a cada valor passado — e será terminado pela plataforma justamente nos maiores e mais valiosos runs de cliente.</p>'
           '<p>O segundo requisito é onde as tasks da onda se encontram: o transporte por id da <strong>B1</strong> é o que torna o por-referência possível. O workflow carrega ids; os payloads ficam no Postgres e no S3. Passar uma entrada resolvida pelo estado do workflow colocaria saída de node dentro do histórico — a mesma falha por outro caminho.</p>'),
   'ba':(('No <code>continueAsNew</code> anywhere in the worker. A run&#x27;s history grows with every activity and every value passed, until the platform terminates it — biggest runs first.',
          'Nenhum <code>continueAsNew</code> em lugar nenhum do worker. O histórico de um run cresce a cada activity e a cada valor passado, até a plataforma terminá-lo — os maiores runs primeiro.'),
         ('The workflow continues at a <strong>stated boundary</strong> and carries ids, not payloads. The ceiling is a number someone wrote down and proved by running a graph past it.',
          'O workflow continua num <strong>limite declarado</strong> e carrega ids, não payloads. O teto é um número que alguém escreveu e provou rodando um grafo além dele.'))},
  {'n':'3','title':('A skipped node has to be loud','Um node pulado precisa ser barulhento'),
   'loc':'flux.service.ts · flux/node-cancel-watch.ts',
   'purpose':('The characteristic failure of a scheduler port is a node that is silently never run.',
              'A falha característica de um port de scheduler é um node que simplesmente nunca roda, em silêncio.'),
   'body':('<p>The back warns today when a node ends outside <code>completed</code> or <code>dead</code> (<code>flux.service.ts</code>). The workflow needs the equivalent, because <strong>unprocessed-node detection must survive the move</strong>.</p>'
           '<p>The related property is failing fast. A graph engine whose failure mode is &#x27;hangs for thirty minutes until the Temporal timeout&#x27; is not shippable — the stall has to be detected by the engine, not by the platform. Cancellation must also still work end to end, including the in-flight flag in <code>flux/node-cancel-watch.ts</code>; <strong>E2</strong> is what makes that native rather than ported.</p>',
           '<p>O back avisa hoje quando um node termina fora de <code>completed</code> ou <code>dead</code> (<code>flux.service.ts</code>). O workflow precisa do equivalente, porque <strong>a detecção de node não processado precisa sobreviver à mudança</strong>.</p>'
           '<p>A propriedade irmã é falhar rápido. Um motor de grafo cujo modo de falha é &#x27;trava por trinta minutos até o timeout do Temporal&#x27; não é entregável — a paralisação precisa ser detectada pelo motor, não pela plataforma. O cancelamento também precisa continuar funcionando ponta a ponta, incluindo a flag de in-flight em <code>flux/node-cancel-watch.ts</code>; a <strong>E2</strong> é o que torna isso nativo em vez de portado.</p>'),
   'ba':(('The back warns about a node that ended outside <code>completed</code> or <code>dead</code>. In a workflow-owned run, nobody is watching for it.',
          'O back avisa sobre um node que terminou fora de <code>completed</code> ou <code>dead</code>. Num run conduzido pelo workflow, ninguém está olhando isso.'),
         ('The workflow detects the stall itself and says which node it was, instead of waiting for the Temporal timeout to end the run.',
          'O próprio workflow detecta a paralisação e diz qual node foi, em vez de esperar o timeout do Temporal terminar o run.'))},
 ],
 VERIF=[
  (True,('Negative control','Controle negativo'),
   ('Break <code>markCompleted</code> so a completed node is not recorded, and confirm the workflow <strong>detects the stall</strong> rather than hanging until the Temporal timeout. A graph engine whose failure mode is &#x27;hangs for thirty minutes&#x27; is not shippable — prove it fails fast.',
    'Quebre o <code>markCompleted</code> para que um node concluído não seja registrado, e confirme que o workflow <strong>detecta a paralisação</strong> em vez de travar até o timeout do Temporal. Um motor de grafo cujo modo de falha é &#x27;trava por trinta minutos&#x27; não é entregável — prove que ele falha rápido.')),
  (False,('Order equivalence — the wave&#x27;s exit gate','Equivalência de ordem — o portão de saída da onda'),
   ('For a corpus of stored flows, assert the workflow executes nodes in the <strong>same order the back&#x27;s loop does, node for node</strong>. With batch size one this must be <em>exact</em>: any divergence is a defect in the port, and this is the last moment it is cheap to see.',
    'Para um corpus de fluxos guardados, afirme que o workflow executa os nodes na <strong>mesma ordem do laço do back, node a node</strong>. Com lote de tamanho um isso precisa ser <em>exato</em>: qualquer divergência é defeito de port, e este é o último momento em que é barato enxergar.')),
  (False,('Unprocessed-node detection survives','A detecção de node não processado sobrevive'),
   ('The back warns today when a node ends outside <code>completed</code> or <code>dead</code> (<code>flux.service.ts</code>). The workflow needs the equivalent — <strong>a silently skipped node is the characteristic failure of a scheduler port</strong>.',
    'O back avisa hoje quando um node termina fora de <code>completed</code> ou <code>dead</code> (<code>flux.service.ts</code>). O workflow precisa do equivalente — <strong>um node pulado em silêncio é a falha característica de um port de scheduler</strong>.')),
  (False,('Cancellation still works end to end','O cancelamento continua funcionando ponta a ponta'),
   ('Including the in-flight flag in <code>flux/node-cancel-watch.ts</code>. <strong>E2</strong> converges this on Temporal&#x27;s native mechanism; B4 must not break it in the meantime.',
    'Incluindo a flag de in-flight em <code>flux/node-cancel-watch.ts</code>. A <strong>E2</strong> converge isso para o mecanismo nativo do Temporal; a B4 não pode quebrá-lo no meio do caminho.')),
  (False,('History growth, measured','Crescimento do histórico, medido'),
   ('Run the <strong>widest</strong> and the <strong>longest</strong> real flow available and record the event count and history size at completion, against the platform&#x27;s limits. Then run one <strong>past</strong> the <code>continueAsNew</code> boundary and confirm it continues rather than being terminated. <strong>A graph engine whose ceiling is unknown has no ceiling.</strong>',
    'Rode o fluxo real mais <strong>largo</strong> e o mais <strong>longo</strong> disponíveis e registre a contagem de eventos e o tamanho do histórico ao concluir, contra os limites da plataforma. Depois rode um <strong>além</strong> do limite do <code>continueAsNew</code> e confirme que ele continua em vez de ser terminado. <strong>Um motor de grafo cujo teto é desconhecido não tem teto.</strong>')),
 ],
 DONE=('A flow runs start to finish under the workflow, <strong>in identical order</strong>, behind a flag <strong>defaulting off</strong>; the back&#x27;s loop is untouched and still selectable.',
       'Um fluxo roda do início ao fim sob o workflow, <strong>em ordem idêntica</strong>, atrás de uma flag <strong>desligada por padrão</strong>; o laço do back fica intocado e ainda selecionável.'),
 FILES=[('worker/src/modules/temporal/workflows/process-agent.workflow.ts',False),
        ('worker/src/modules/temporal/{activities,worker.service.ts,workflows/configs.ts}',False),
        ('back/src/app-api/flux/flux.service.ts (await handle.result() in processNodeViaTemporal · the while (scheduledId !== null) loop · the unprocessed-node warning)',False),
        ('the scheduler module from B2 (allReady)',False),
        ('new flow workflow',True)],
)

B4_DEC = {
 'k':'decision','id':'B4-a','status':'open','open':True,
 'q':('Where does <code>continueAsNew</code> cut the run, and at what number?',
      'Onde o <code>continueAsNew</code> corta o run, e em que número?'),
 'intro':('<strong>Review action #7, added to B4 after the plan was written.</strong> A Temporal workflow accumulates history events, and both the event count and the total size are capped. '
          'The worker uses <strong>no <code>continueAsNew</code></strong> anywhere today, so one workflow owning an entire flow run grows with every activity scheduled and completed and every value passed — '
          'and it will be terminated by the platform on <strong>exactly the largest, most valuable customer runs</strong> (review §4.1). '
          'The spec makes two things non-optional: a boundary, and state by reference. The <em>boundary</em> is the open part — <strong>iteration count or node count. Pick one, state the number, and prove it by running a graph past it.</strong>',
          '<strong>Ação #7 da revisão, acrescentada à B4 depois que o plano foi escrito.</strong> Um workflow do Temporal acumula eventos de histórico, e tanto a contagem de eventos quanto o tamanho total têm teto. '
          'O worker não usa <strong>nenhum <code>continueAsNew</code></strong> hoje, então um workflow dono de um run inteiro cresce a cada activity agendada e concluída e a cada valor passado — '
          'e será terminado pela plataforma <strong>justamente nos maiores e mais valiosos runs de cliente</strong> (review §4.1). '
          'A spec torna duas coisas não opcionais: um limite, e estado por referência. O <em>limite</em> é a parte em aberto — <strong>contagem de iterações ou contagem de nodes. Escolha uma, declare o número, e prove rodando um grafo além dele.</strong>'),
 'opts':[
  {'ltr':'A','pick':True,'name':('Node-execution count','Contagem de execuções de node'),
   'tag':('recommended','recomendada'),
   'how':('The workflow counts node executions and calls <code>continueAsNew</code> at a stated number, carrying the scheduler state forward by reference.',
          'O workflow conta execuções de node e chama <code>continueAsNew</code> num número declarado, levando o estado do scheduler adiante por referência.'),
   'pros':[('It counts the thing that actually produces history — <strong>every node execution is activities scheduled and completed</strong>','Conta o que de fato produz histórico — <strong>cada execução de node significa activities agendadas e concluídas</strong>'),
           ('It fires on <strong>every graph shape</strong>, including a wide graph that never loops','Dispara em <strong>toda forma de grafo</strong>, inclusive num grafo largo que nunca faz laço'),
           ('It shares its unit with <strong>S4&#x27;s per-run budget</strong>, so the two numbers can be read against each other instead of drifting apart','Compartilha a unidade com o <strong>orçamento por run da S4</strong>, então os dois números podem ser lidos um contra o outro em vez de divergirem')],
   'cons':[('A single execution that passes a very large value still grows history faster than the count suggests — size is the other cap','Uma única execução que passa um valor muito grande ainda cresce o histórico mais rápido que a contagem sugere — tamanho é o outro teto'),
           ('The number has to be re-derived if the average activity count per node changes','O número precisa ser recalculado se a média de activities por node mudar')],
   'cost':[('lo',('Client effort: <b>none — a continued run is still one run</b>','Esforço do cliente: <b>nenhum — um run continuado ainda é um run</b>')),
           ('',('Ours: <b>one counter, plus the boundary test</b>','Nosso: <b>um contador, mais o teste de limite</b>'))]},
  {'ltr':'B','name':('Loop-iteration count','Contagem de iterações de laço'),
   'how':('The workflow continues as new after a stated number of loop iterations — the shape that most obviously grows without bound.',
          'O workflow continua como novo depois de um número declarado de iterações de laço — a forma que mais obviamente cresce sem limite.'),
   'pros':[('Aims directly at the known growth case: a long loop, or an <code>arrayNode</code> over a big list','Mira direto no caso de crescimento conhecido: um laço longo, ou um <code>arrayNode</code> sobre uma lista grande'),
           ('Easy to explain to whoever is debugging a run that continued','Fácil de explicar para quem estiver depurando um run que continuou')],
   'cons':[('A <strong>wide graph with no loop at all</strong> can still exhaust history — the boundary simply never fires','Um <strong>grafo largo sem laço nenhum</strong> ainda pode esgotar o histórico — o limite simplesmente nunca dispara'),
           ('It measures a proxy rather than what accumulates, so the ceiling is only as good as the correlation','Mede um proxy em vez do que acumula, então o teto só vale o quanto a correlação valer')],
   'cost':[('lo',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('hi',('Ours: <b>a boundary that misses wide graphs</b>','Nosso: <b>um limite que não pega grafos largos</b>'))]},
  {'ltr':'C','no':True,'name':('No <code>continueAsNew</code> — lean on S4&#x27;s ceiling','Sem <code>continueAsNew</code> — apoiar-se no teto da S4'),
   'tag':('not viable','inviável'),
   'how':('<strong>S4</strong> already bounds node executions per run, and that bounds history growth. Let that ceiling be the only limit.',
          'A <strong>S4</strong> já limita execuções de node por run, e isso limita o crescimento do histórico. Deixar esse teto ser o único limite.'),
   'pros':[('Nothing new to build in B4, and one number instead of two to keep consistent','Nada novo a construir na B4, e um número em vez de dois para manter consistentes')],
   'cons':[('S4&#x27;s ceiling is deliberately set <strong>above the largest real run</strong> — so the largest real runs are exactly the ones it does not stop','O teto da S4 é deliberadamente colocado <strong>acima do maior run real</strong> — então os maiores runs reais são justamente os que ele não para'),
           ('S4&#x27;s own spec calls itself <em>&#x27;the other half of what B4&#x27;s <code>continueAsNew</code> is for&#x27;</em> — a complement, not a replacement','A própria spec da S4 se chama de <em>&#x27;a outra metade do que o <code>continueAsNew</code> da B4 faz&#x27;</em> — um complemento, não um substituto'),
           ('The residual failure is <strong>platform termination of a customer&#x27;s biggest run</strong>, which is not a failure we get to explain away','A falha residual é <strong>a plataforma terminar o maior run de um cliente</strong>, que não é uma falha que dá para explicar')],
   'cost':[('lo',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('hi',('Ours: <b>the largest customer runs stay terminable</b>','Nosso: <b>os maiores runs de cliente seguem termináveis</b>'))]},
 ],
 'rec':('<p><strong>A — node-execution count — with the number derived from the measurement the task already owes.</strong> Run the widest and the longest real flow available, record the event count and the history size at completion against the platform&#x27;s limits, then set the boundary <em>below</em> that with margin and run a graph past it. State the number in the PR; a ceiling nobody wrote down is not a ceiling.</p>'
        '<p>B is not wrong so much as partial: it aims at loops, and loops are only one of the two shapes that exhaust history. If loop iterations turn out to dominate in the real measurement, A still catches them — the reverse is not true.</p>'
        '<p>Whichever boundary wins, the second requirement is not negotiable: <strong>state by reference, never by value</strong>. The workflow carries the ids <strong>B1</strong> settles, and the payloads stay in Postgres and S3. Passing a resolved input through workflow state puts node output into the history and reintroduces the same failure from the other side.</p>',
        '<p><strong>A — contagem de execuções de node — com o número derivado da medição que a task já deve.</strong> Rode o fluxo real mais largo e o mais longo, registre a contagem de eventos e o tamanho do histórico ao concluir contra os limites da plataforma, e então coloque o limite <em>abaixo</em> disso com margem e rode um grafo além dele. Declare o número no PR; um teto que ninguém escreveu não é um teto.</p>'
        '<p>B não é tanto errada quanto parcial: mira em laços, e laços são só uma das duas formas que esgotam o histórico. Se as iterações de laço dominarem na medição real, A ainda as pega — o contrário não vale.</p>'
        '<p>Vencendo qualquer limite, o segundo requisito não é negociável: <strong>estado por referência, nunca por valor</strong>. O workflow carrega os ids que a <strong>B1</strong> resolve, e os payloads ficam no Postgres e no S3. Passar uma entrada resolvida pelo estado do workflow coloca saída de node no histórico e reintroduz a mesma falha pelo outro lado.</p>'),
 'who':[('Engineering','Engenharia'),('Infra states the platform limits','Infra declara os limites da plataforma')],
}
