# -*- coding: utf-8 -*-

B3 = dict(
 TITLE=('The consumer resolves its own input','O consumidor resolve a própria entrada'),
 GOAL=('Stop the API from pre-chewing every node&#x27;s input. Each node reads its upstream outputs <b>by reference</b> and resolves what it needs — <b>fetch only</b>: a <code>node_executions</code> row or a claim-check payload in S3, through the reference it was given. No transformation, no extraction, no OCR (confirmed 2026-09-02).',
       'Parar de a API pré-mastigar a entrada de cada node. Cada node lê as saídas de seus upstreams <b>por referência</b> e resolve o que precisa — <b>só fetch</b>: uma linha de <code>node_executions</code> ou um payload do claim check no S3, pela referência que recebeu. Sem transformação, sem extração, sem OCR (confirmado em 2026-09-02).'),
 GLANCE=[
  ('crit',('Risk','Risco'),('Silent empty resolution','Resolução vazia silenciosa'),
   ('The failure mode the spec names: a node pointed at an incomplete upstream resolving to an empty string looks like a prompt bug for weeks.',
    'O modo de falha que a spec nomeia: um node apontado para um upstream incompleto resolvendo para string vazia parece um bug de prompt por semanas.')),
  ('dep',('Depends on','Depende de'),('B1, B2','B1, B2'),
   ('Blocks B4. Blocked on decision <strong>D2</strong>.',
    'Bloqueia a B4. Bloqueada pela decisão <strong>D2</strong>.')),
  ('wave',('Wave','Onda'),('Wave 4','Onda 4'),
   ('While the API owns input resolution, the worker cannot own the graph — every node needs a round trip through the back to become runnable.',
    'Enquanto a API for dona da resolução de entrada, o worker não pode ser dono do grafo — todo node precisa de uma ida e volta ao back para ficar executável.')),
  ('ship',('Needs','Precisa de'),('A1&#x27;s measurement (Wave 2)','A medição da A1 (onda 2)'),
   ('How many stored flows satisfy the 17-type whitelist, how many ran with the flag on, and what the prefetch path actually saved. B3 answers D2 with those numbers.',
    'Quantos fluxos guardados satisfazem a whitelist de 17 tipos, quantos rodaram com a flag ligada, e o que o caminho de prefetch de fato economizou. A B3 responde a D2 com esses números.')),
 ],
 LEDE=('<p>Today the API resolves a node&#x27;s input and pre-saves it before dispatch: <code>openNodeExecution</code> INSERTs <code>node_executions.input</code>, and the worker only reads it — <code>fetch-node-row.ts</code> selects <code>input</code> when <code>execId</code> is present, and <strong>never reads the live row</strong>.</p>'
       '<p><strong>This is partly built already.</strong> The prefetch executor is in production behind <code>FLUX_EXEC_MEMORY_MODE=prefetch</code> (analysis §9.2.1). So this is not a design task. It is: <strong>measure what exists, decide whether it is the destination, and move it to the worker side of the boundary.</strong></p>',
       '<p>Hoje a API resolve a entrada de um node e a pré-salva antes do dispatch: o <code>openNodeExecution</code> faz INSERT em <code>node_executions.input</code>, e o worker apenas lê — o <code>fetch-node-row.ts</code> seleciona <code>input</code> quando há <code>execId</code>, e <strong>nunca lê a linha viva</strong>.</p>'
       '<p><strong>Isso já está parcialmente construído.</strong> O executor de prefetch está em produção atrás de <code>FLUX_EXEC_MEMORY_MODE=prefetch</code> (análise §9.2.1). Então esta não é uma task de projeto. É: <strong>medir o que existe, decidir se é o destino, e mover para o lado do worker na fronteira.</strong></p>'),
 L1=('What the prefetch executor already does','O que o executor de prefetch já faz'),
 TABLES=[
  dict(head=[('Piece','Peça'),('What it does today','O que faz hoje'),('Why it matters for B3','Por que importa para a B3')],
   rows=[
    [{'t':'scanPlaceholderRefs','mono':True},
     ('Discovers only the refs a node actually uses','Descobre apenas as refs que um node de fato usa'),
     ('It is already the &#x27;resolve what you need&#x27; rule this task is named after','Já é a regra de &#x27;resolva o que você precisa&#x27; que dá nome a esta task')],
    [{'t':'loadOutputsByRefs','mono':True},
     ('Fetches only those rows from <code>node_executions</code>','Busca apenas aquelas linhas de <code>node_executions</code>'),
     ('The read the consumer would do for itself, currently done on its behalf','A leitura que o consumidor faria por si, hoje feita em seu nome')],
    [{'t':'schemaForNode','mono':True},
     ('Builds a small per-node schema instead of mutating the global one','Monta um schema pequeno por node em vez de mutar o global'),
     ('A per-node schema is what makes resolution relocatable at all','Um schema por node é o que torna a resolução realocável')],
    [{'t':'OutputPointer','mono':True},
     ('Outputs travel as a pointer, not as a value','Saídas viajam como ponteiro, não como valor'),
     ('The by-reference transport <strong>B1</strong> is settling','O transporte por referência que a <strong>B1</strong> está resolvendo')],
    [{'t':'assembleFinalOutputsFromDb','mono':True},
     ('Assembles the final outputs at the end of the run','Monta as saídas finais no fim do run'),
     ('Whoever ends the run keeps this — it is not part of making a node runnable','Quem termina o run mantém isto — não faz parte de tornar um node executável')],
   ]),
 ],
 PROSE1=('The flag defaults to <code>legacy</code> and the whitelist covers 17 node types, excluding every Temporal type and every control-flow type (analysis §9.2.1). <strong>A path that is shipped and dormant looks exactly like a path that works</strong> — which is why the decision below refuses to be taken on impressions.',
         'A flag tem padrão <code>legacy</code> e a whitelist cobre 17 tipos de node, excluindo todo tipo Temporal e todo tipo de controle de fluxo (análise §9.2.1). <strong>Um caminho entregue e dormente parece exatamente um caminho que funciona</strong> — por isso a decisão abaixo se recusa a ser tomada por impressão.'),
 DECINTRO=('One decision, and the honest answer today is that it <strong>cannot be taken yet</strong>. The page states what would decide it, who owes the number, and what to do if the number never arrives.',
           'Uma decisão, e a resposta honesta hoje é que ela <strong>ainda não pode ser tomada</strong>. A página declara o que a decidiria, quem deve o número, e o que fazer se o número nunca chegar.'),
 LPARTS=('What the task does, in three parts','O que a task faz, em três partes'),
 PARTS=[
  {'n':'1','title':('<code>node_executions.input</code> changes meaning','O <code>node_executions.input</code> muda de significado'),
   'loc':'node-execution-store.ts · fetch-node-row.ts',
   'purpose':('It stops being a <strong>precondition for running</strong> and becomes a <strong>record of what the node ran with</strong>.',
              'Ele deixa de ser <strong>pré-condição para rodar</strong> e passa a ser <strong>registro do que o node rodou</strong>.'),
   'body':('<p>Today the column is load-bearing in the worst way: a node is not runnable until the API has resolved its input and written it, and the worker reads that write rather than the live row. That single fact is why the worker cannot own the graph — every node needs a round trip through the back to become runnable.</p>'
           '<p>After this task the column is still written, and it must be: <strong>run history and debugging depend on it</strong>. What changes is that nothing waits for it.</p>',
           '<p>Hoje a coluna é estrutural do pior jeito: um node não é executável até a API resolver a entrada dele e gravá-la, e o worker lê essa gravação em vez da linha viva. Esse único fato é a razão de o worker não poder ser dono do grafo — todo node precisa de uma ida e volta ao back para ficar executável.</p>'
           '<p>Depois desta task a coluna continua sendo escrita, e precisa ser: <strong>o histórico de runs e a depuração dependem dela</strong>. O que muda é que nada mais espera por ela.</p>'),
   'ba':(('A node becomes runnable only after the API resolves and writes its input. The worker reads that row and never the live one.',
          'Um node só fica executável depois que a API resolve e grava a entrada dele. O worker lê aquela linha e nunca a viva.'),
         ('A node becomes runnable from its <strong>references</strong>. <code>node_executions.input</code> still records what it ran with, so run history and debugging are unchanged.',
          'Um node fica executável a partir de suas <strong>referências</strong>. O <code>node_executions.input</code> continua registrando com o que ele rodou, então histórico e depuração não mudam.')),
   'callouts':[('decide',('Fetch, and only fetch','Fetch, e só fetch'),
     ('<p>Confirmed with the requester on 2026-09-02: the consumer <strong>loads what it needs, and only that</strong>, through the reference it was given — a <code>node_executions</code> row, or a claim-check payload in S3 (<code>get-payload</code>, the boundary S5 authorises). It does <strong>not transform, extract or OCR</strong> what it fetched: extraction is A8&#x27;s, and an OCR node is out of the epic (D24).</p>',
      '<p>Confirmado com quem pediu em 2026-09-02: o consumidor <strong>carrega o que precisa, e só isso</strong>, pela referência que recebeu — uma linha de <code>node_executions</code>, ou um payload do claim check no S3 (<code>get-payload</code>, a fronteira que a S5 autoriza). Ele <strong>não transforma, não extrai nem faz OCR</strong> do que buscou: extração é da A8, e um node de OCR está fora da épica (D24).</p>')),
    ('mig',('The back&#x27;s copy stays','A cópia do back fica'),
     ('<p>Removing the back&#x27;s resolution path is <strong>out of scope</strong>. It stays until this is proven (PLAN §3.2), and <strong>this step must be reversible above all others</strong> — it is the one that changes how a node becomes runnable at all.</p>',
      '<p>Remover o caminho de resolução do back está <strong>fora de escopo</strong>. Ele fica até isto estar provado (PLAN §3.2), e <strong>este passo precisa ser reversível acima de todos os outros</strong> — é o que muda como um node se torna executável.</p>'))]},
  {'n':'2','title':('The eligibility gate is a refusing rule','O portão de elegibilidade é uma regra que recusa'),
   'loc':('PLAN §3.3.2 — measure before refusing', 'PLAN §3.3.2 — medir antes de recusar'),
   'purpose':('Whatever decides &#x27;this flow can resolve worker-side&#x27; refuses flows, and a false refusal is worse than the defect it fixes.',
              'O que decide &#x27;este fluxo pode resolver no worker&#x27; recusa fluxos, e uma recusa falsa é pior que o defeito que ela corrige.'),
   'body':('<p>The prefetch whitelist is already such a gate, and the same discipline applies to whatever replaces it: classify <strong>every</strong> refusal against real stored flows as <em>correctly refused</em> or <em>refused although it works</em>, and drive the second count to <strong>zero</strong>.</p>'
           '<p>Where eligibility cannot be determined, report the flow as <strong>unverifiable</strong> — not as ineligible. A count that quietly rounds unknowns to zero is how a gate ships looking safe.</p>',
           '<p>A whitelist do prefetch já é um portão desses, e a mesma disciplina vale para o que a substituir: classifique <strong>toda</strong> recusa contra fluxos reais guardados como <em>corretamente recusada</em> ou <em>recusada embora funcione</em>, e leve a segunda contagem a <strong>zero</strong>.</p>'
           '<p>Onde a elegibilidade não puder ser determinada, reporte o fluxo como <strong>não verificável</strong> — não como inelegível. Uma contagem que arredonda desconhecidos para zero em silêncio é como um portão entra em produção parecendo seguro.</p>'),
   'ba':(('The whitelist refuses by node type and nobody has counted what it refuses. Dormant and broken look the same from here.',
          'A whitelist recusa por tipo de node e ninguém contou o que ela recusa. Dormente e quebrado parecem a mesma coisa daqui.'),
         ('Every refusal is classified against stored flows, refused-although-it-works is zero, and the unknowns are reported as unknown.',
          'Toda recusa é classificada contra fluxos guardados, recusada-embora-funcione é zero, e os desconhecidos são reportados como desconhecidos.'))},
  {'n':'3','title':('Equivalence, on all three key shapes','Equivalência, nas três formas de chave'),
   'loc':('the substitution module from B2', 'o módulo de substituição, vindo da B2'),
   'purpose':('Placeholder resolution has three key shapes per node in the schema, and the collision case is the one that decides correctness.',
              'A resolução de placeholders tem três formas de chave por node no schema, e o caso de colisão é o que decide a correção.'),
   'body':('<p>For a corpus of stored runs, resolve each node&#x27;s input <strong>both ways and diff</strong>. The three shapes are the <code>nodeId</code>, the normalised ref-key, and the lowercased label alias — and the alias is where two nodes sharing a label collide.</p>'
           '<p>That collision is not an edge case invented for the test: labels are user-typed, and two nodes called &#x27;Prompt&#x27; in the same flow is a thing people do. Whichever implementation wins has to resolve it the same way the current one does, or a customer&#x27;s flow quietly starts reading the wrong upstream.</p>',
           '<p>Para um corpus de runs guardados, resolva a entrada de cada node <strong>pelos dois caminhos e compare</strong>. As três formas são o <code>nodeId</code>, a ref-key normalizada e o alias de label em minúsculas — e é no alias que dois nodes com o mesmo label colidem.</p>'
           '<p>Essa colisão não é um caso de borda inventado para o teste: labels são digitados pelo usuário, e dois nodes chamados &#x27;Prompt&#x27; no mesmo fluxo é coisa que as pessoas fazem. A implementação vencedora tem de resolver isso do mesmo jeito que a atual, ou o fluxo de um cliente passa silenciosamente a ler o upstream errado.</p>'),
   'ba':(('One implementation resolves placeholders, so nothing compares them. The alias collision resolves however it resolves.',
          'Uma implementação resolve placeholders, então nada as compara. A colisão de alias resolve como resolver.'),
         ('Both implementations are run over stored runs and diffed, with the alias collision covered explicitly — the two agree or the task is not done.',
          'As duas implementações são rodadas sobre runs guardados e comparadas, com a colisão de alias coberta explicitamente — ou as duas concordam, ou a task não está pronta.'))},
 ],
 VERIF=[
  (True,('Negative control','Controle negativo'),
   ('Point a node at an upstream that has <strong>not completed</strong> and confirm it fails loudly rather than resolving to an empty string. <strong>Silent empty resolution is the failure mode that will otherwise reach production and look like a prompt bug for weeks.</strong>',
    'Aponte um node para um upstream que <strong>não completou</strong> e confirme que ele falha alto em vez de resolver para string vazia. <strong>A resolução vazia silenciosa é o modo de falha que, caso contrário, chega em produção e parece um bug de prompt por semanas.</strong>')),
  (False,('Output equivalence over real flows','Equivalência de saída sobre fluxos reais'),
   ('For a corpus of stored runs, resolve each node&#x27;s input <strong>both ways and diff</strong>. Cover all three key shapes — <code>nodeId</code>, normalised ref-key, lowercased label alias — <strong>including the alias collision case where two nodes share a label</strong>.',
    'Para um corpus de runs guardados, resolva a entrada de cada node <strong>pelos dois caminhos e compare</strong>. Cubra as três formas de chave — <code>nodeId</code>, ref-key normalizada, alias de label em minúsculas — <strong>incluindo o caso de colisão em que dois nodes têm o mesmo label</strong>.')),
  (False,('Measure before refusing','Medir antes de recusar'),
   ('<strong>PLAN §3.3.2.</strong> Whatever gate decides &#x27;this flow can resolve worker-side&#x27; is a refusing rule. Classify every refusal against real stored flows and drive <em>refused-although-it-works</em> to <strong>zero</strong>.',
    '<strong>PLAN §3.3.2.</strong> O portão que decide &#x27;este fluxo pode resolver no worker&#x27; é uma regra que recusa. Classifique toda recusa contra fluxos reais guardados e leve <em>recusada-embora-funcione</em> a <strong>zero</strong>.')),
 ],
 DONE=('A node can be made runnable <strong>without the API resolving its input</strong>; equivalence is proven; and the back&#x27;s path is <strong>still present and revertible by flag</strong>.',
       'Um node pode ficar executável <strong>sem a API resolver a entrada dele</strong>; a equivalência está provada; e o caminho do back <strong>continua presente e reversível por flag</strong>.'),
 FILES=[('back/src/app-api/flux/prefetch/**',False),
        ('back/src/temporal/single-node-legacy/node-execution-store.ts',False),
        ('worker/src/modules/nodes/shared/fetch-node-row.ts',False),
        ('the substitution module from B2',False),
        ('worker-side resolution (new)',True)],
)

B3_DEC = {
 'k':'decision','id':'B3-a','plan':'D2','status':'open','open':True,
 'q':('Is the prefetch executor the destination for worker-side input resolution, or a stopgap to retire?',
      'O executor de prefetch é o destino da resolução de entrada no worker, ou um paliativo a aposentar?'),
 'intro':('<strong>D2 in <code>PLAN.md</code> §7 — and the measurement it needs is <code>A1</code>&#x27;s, taken in Wave 2 while <code>A1</code> runs <code>canUsePrefetchForFlow</code> against every stored flow.</strong> '
          'The executor ships behind <code>FLUX_EXEC_MEMORY_MODE</code>, defaulting to <code>legacy</code>, with a <strong>17-type whitelist that excludes every Temporal type and every control-flow type</strong>. '
          'A flag defaulting to <code>legacy</code> whose whitelist excludes every LLM node may be <strong>shipped but dormant</strong> — and dormant code generalises badly. '
          'A1 reports the count: how many stored flows satisfy <code>canUsePrefetchForFlow</code>, how many of those ran with the flag on, and what it saved — memory, latency, row size.',
          '<strong>A D2 do <code>PLAN.md</code> §7 — e a medição de que ela precisa é da <code>A1</code>, feita na onda 2 enquanto a <code>A1</code> roda o <code>canUsePrefetchForFlow</code> contra todo fluxo guardado.</strong> '
          'O executor está em produção atrás de <code>FLUX_EXEC_MEMORY_MODE</code>, com padrão <code>legacy</code>, e uma <strong>whitelist de 17 tipos que exclui todo tipo Temporal e todo tipo de controle de fluxo</strong>. '
          'Uma flag com padrão <code>legacy</code> cuja whitelist exclui todo node de LLM pode estar <strong>entregue mas dormente</strong> — e código dormente generaliza mal. '
          'A A1 reporta a contagem: quantos fluxos guardados satisfazem o <code>canUsePrefetchForFlow</code>, quantos deles rodaram com a flag ligada, e o que isso economizou — memória, latência, tamanho de linha.'),
 'opts':[
  {'ltr':'A','name':('Destination — widen it and relocate it','Destino — ampliar e realocar'),
   'tag':('needs the number','depende do número'),
   'how':('The executor is the model B3 generalises: widen the whitelist as the A track lands, move the resolution to the worker side, keep the executor&#x27;s shape.',
          'O executor é o modelo que a B3 generaliza: ampliar a whitelist conforme a trilha A entrega, mover a resolução para o lado do worker, manter o formato do executor.'),
   'pros':[('The mechanism is already in production and already reference-based — <code>OutputPointer</code> is the transport B1 is settling','O mecanismo já está em produção e já é baseado em referência — o <code>OutputPointer</code> é o transporte que a B1 está resolvendo'),
           ('Nothing is thrown away, and the per-node schema is the hard part that already works','Nada é jogado fora, e o schema por node é a parte difícil que já funciona'),
           ('The whitelist becomes the eligibility gate B3 needs anyway','A whitelist vira o portão de elegibilidade de que a B3 precisa de qualquer forma')],
   'cons':[('It is only the destination <strong>if the measurement says it works</strong>: a near-zero eligible-flow count would mean generalising something never exercised','Só é o destino <strong>se a medição disser que funciona</strong>: uma contagem próxima de zero significaria generalizar algo nunca exercitado'),
           ('The whitelist is a fourth list of node types in a codebase where <strong>A1 exists to collapse them into one</strong>','A whitelist é uma quarta lista de tipos de node num código onde <strong>a A1 existe para colapsá-las em uma</strong>')],
   'cost':[('lo',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('',('Ours: <b>widen a whitelist the A track keeps moving</b>','Nosso: <b>ampliar uma whitelist que a trilha A move o tempo todo</b>'))]},
  {'ltr':'B','name':('Stopgap — resolve in the worker, retire the executor','Paliativo — resolver no worker, aposentar o executor'),
   'tag':('the default if unmeasured','o padrão se não medido'),
   'how':('The worker resolves its own input using the substitution module extracted in <strong>B2</strong>, and the prefetch path is retired by <strong>C2</strong> — removing a fourth list from the world.',
          'O worker resolve a própria entrada usando o módulo de substituição extraído na <strong>B2</strong>, e o caminho de prefetch é aposentado pela <strong>C2</strong> — tirando uma quarta lista do mundo.'),
   'pros':[('One implementation of placeholder resolution instead of two live paths','Uma implementação de resolução de placeholders em vez de dois caminhos vivos'),
           ('The retirement is <strong>already scheduled in C2</strong>, so the cleanup has an owner and a date','A aposentadoria <strong>já está agendada na C2</strong>, então a limpeza tem dono e data'),
           ('B2&#x27;s module is the same code the API resolves with today, so equivalence starts from the same source','O módulo da B2 é o mesmo código com que a API resolve hoje, então a equivalência parte da mesma origem')],
   'cons':[('It discards a path already proven in production — <em>if</em> the measurement shows it was carrying real traffic','Descarta um caminho já provado em produção — <em>se</em> a medição mostrar que ele carregava tráfego real'),
           ('The worker-side resolver must reproduce all three key shapes exactly, alias collision included','O resolvedor no worker precisa reproduzir as três formas de chave exatamente, colisão de alias inclusa')],
   'cost':[('lo',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('hi',('Ours: <b>a resolver that must match the old one exactly</b>','Nosso: <b>um resolvedor que precisa bater exatamente com o antigo</b>'))]},
  {'ltr':'C','pick':True,'name':('Do not decide yet — gate B3 on A1&#x27;s count','Não decidir ainda — condicionar a B3 à contagem da A1'),
   'tag':('recommended','recomendada'),
   'how':('Run A1&#x27;s measurement first — eligible flows, flows that actually ran with the flag on, and what it saved — and let the number choose between A and B. Nothing in B3 is written against the prefetch executor until it exists.',
          'Rodar antes a medição da A1 — fluxos elegíveis, fluxos que realmente rodaram com a flag ligada, e o que economizou — e deixar o número escolher entre A e B. Nada da B3 é escrito contra o executor de prefetch até esse número existir.'),
   'pros':[('The decision becomes a <strong>measurement, not a preference</strong> — which is what the PLAN row already says it must be','A decisão vira uma <strong>medição, não uma preferência</strong> — que é o que a linha do PLAN já diz que ela precisa ser'),
           ('A1 owes the same count regardless, so this is <strong>not extra work</strong>, only extra ordering','A A1 deve a mesma contagem de qualquer forma, então isto <strong>não é trabalho extra</strong>, só ordem extra'),
           ('A wrong answer is expensive in <em>both</em> directions — generalising dead code, or discarding a working path','Uma resposta errada é cara nos <em>dois</em> sentidos — generalizar código morto, ou descartar um caminho que funciona')],
   'cons':[('It puts a dependency on A1&#x27;s measurement in the middle of Wave 4 — A1 is Wave 2, so the number should exist by then','Coloca uma dependência da medição da A1 no meio da Onda 4 — a A1 é onda 2, então o número deve existir até lá'),
           ('If the measurement cannot be produced, someone still has to choose — and then it is B by default','Se a medição não puder ser produzida, alguém ainda precisa escolher — e aí é B por padrão')],
   'cost':[('lo',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('lo',('Ours: <b>a count A1 owes anyway</b>','Nosso: <b>uma contagem que a A1 já deve</b>'))]},
 ],
 'rec':('<p><strong>C first, then A or B on the number.</strong> This is the one decision in Wave 4 whose inputs do not exist yet, and pretending otherwise picks between a production-proven path and a dormant one on vibes.</p>'
        '<p>Two conditions on the measurement itself. Report flows whose eligibility cannot be determined as <strong>unverifiable, not ineligible</strong> — C2&#x27;s own verification says so, and a count that rounds unknowns to zero is how &#x27;nobody uses it&#x27; becomes a self-fulfilling conclusion. And measure <em>usage</em>, not just <em>eligibility</em>: a flow that could have used prefetch but ran under <code>legacy</code> proves nothing about whether prefetch works.</p>'
        '<p><strong>If the measurement never arrives, choose B.</strong> The substitution module exists either way after B2, and one resolver is cheaper to own than two — the whitelist is a fourth list of node types in a codebase A1 exists to reduce to one.</p>',
        '<p><strong>C primeiro, depois A ou B pelo número.</strong> Esta é a única decisão da Onda 4 cujos insumos ainda não existem, e fingir o contrário é escolher entre um caminho provado em produção e um dormente no feeling.</p>'
        '<p>Duas condições sobre a própria medição. Reporte como <strong>não verificáveis, não inelegíveis</strong>, os fluxos cuja elegibilidade não puder ser determinada — a verificação da própria C2 diz isso, e uma contagem que arredonda desconhecidos para zero é como &#x27;ninguém usa&#x27; vira conclusão autorrealizável. E meça <em>uso</em>, não só <em>elegibilidade</em>: um fluxo que poderia ter usado prefetch mas rodou em <code>legacy</code> não prova nada sobre o prefetch funcionar.</p>'
        '<p><strong>Se a medição nunca chegar, escolha B.</strong> O módulo de substituição existe de qualquer forma depois da B2, e um resolvedor é mais barato de manter que dois — a whitelist é uma quarta lista de tipos de node num código que a A1 existe para reduzir a uma.</p>'),
 'who':[('Engineering','Engenharia'),('A1 owns the measurement (Wave 2)','A A1 é dona da medição (onda 2)')],
}

B4 = dict(
 TITLE=('Move the DAG loop into a Temporal workflow','Mover o laço do DAG para um workflow do Temporal'),
 GOAL=('The worker owns the execution sequence — and <b>this task ships with no parallelism at all</b>.',
       'O worker passa a ser dono da sequência de execução — e <b>esta task entrega sem nenhum paralelismo</b>.'),
 GLANCE=[
  ('crit',('Risk','Risco'),('Workflow history exhaustion','Esgotamento do histórico do workflow'),
   ('Risk R15 and review §4.1 — one workflow per run, <strong>no <code>continueAsNew</code> anywhere</strong>, terminated by the platform on the largest customer runs first.',
    'Risco R15 e review §4.1 — um workflow por run, <strong>nenhum <code>continueAsNew</code> em lugar algum</strong>, terminado pela plataforma primeiro nos maiores runs de cliente.')),
  ('dep',('Depends on','Depende de'),('B2, B3','B2, B3'),
   ('Blocks B5 and B6. Ships in the same wave as <strong>E1</strong>, not before it.',
    'Bloqueia a B5 e a B6. Entra na mesma onda que a <strong>E1</strong>, não antes dela.')),
  ('wave',('Wave','Onda'),('Wave 4','Onda 4'),
   ('Relocating the loop and letting it dispatch more than one node are <strong>two deploys, always</strong>.',
    'Realocar o laço e deixá-lo despachar mais de um node são <strong>dois deploys, sempre</strong>.')),
  ('ship',('Ships','Entrega'),('Sequential, batch size one','Sequencial, lote de um'),
   ('<code>allReady()</code> returning a single id <em>is</em> today&#x27;s behaviour. Nothing gets faster — that is the success criterion.',
    '<code>allReady()</code> devolvendo um único id <em>é</em> o comportamento de hoje. Nada fica mais rápido — esse é o critério de sucesso.')),
 ],
 LEDE=('<p>Two changes hide inside &#x27;move the graph&#x27;: <strong>relocating the loop</strong>, and <strong>letting it dispatch more than one node</strong>. Shipped together, a rollback cannot tell you which one broke the run. Shipped apart, each one is a one-line flag.</p>'
       '<p>Sequential is also nearly free to express: <code>allReady()</code> returning a single id <em>is</em> today&#x27;s behaviour. B4 builds the batch-capable machinery and configures it to a batch size of one. What it does pay back is the blocking wait — <code>await handle.result()</code> at <code>flux.service.ts</code>, which makes every migrated node a synchronous round trip today (analysis §9.2.2).</p>',
       '<p>Duas mudanças se escondem em &#x27;mover o grafo&#x27;: <strong>realocar o laço</strong>, e <strong>deixá-lo despachar mais de um node</strong>. Entregues juntas, um rollback não consegue dizer qual delas quebrou o run. Entregues separadas, cada uma é uma flag de uma linha.</p>'
       '<p>E expressar o modo sequencial é quase de graça: <code>allReady()</code> devolvendo um único id <em>é</em> o comportamento de hoje. A B4 constrói a maquinaria capaz de lote e a configura com lote de tamanho um. O que ela paga de volta é a espera bloqueante — o <code>await handle.result()</code> em <code>flux.service.ts</code>, que hoje faz de cada node migrado uma ida e volta síncrona (análise §9.2.2).</p>'),
 L1=('What already exists, and what B4 does with it','O que já existe, e o que a B4 faz com isso'),
 TABLES=[
  dict(head=[('Asset','O que existe'),('Where','Onde'),('State today','Estado hoje'),('What B4 does with it','O que a B4 faz com ele')],
   rows=[
    [{'t':('The graph itself','O grafo em si')},
     ('<code>flux/scheduler.ts</code>, extracted in <strong>B2</strong>','<code>flux/scheduler.ts</code>, extraído na <strong>B2</strong>'),
     {'t':('Correct and portable','Correto e portável'),'pill':'ok'},
     ('The workflow owns <code>SchedulerState</code> instead of the API','O workflow passa a ser dono do <code>SchedulerState</code> em vez da API')],
    [{'t':('The parallel loop','O laço paralelo')},
     ('<code>worker/src/modules/temporal/workflows/process-agent.workflow.ts</code>','<code>worker/src/modules/temporal/workflows/process-agent.workflow.ts</code>'),
     {'t':('Written, then commented out','Escrito, e comentado'),'pill':'weak'},
     ('<strong>Read it before writing a new one</strong> — in-degree per node, a <code>readyToRun</code> filter, <code>Promise.all</code> over the batch','<strong>Leia antes de escrever outro</strong> — in-degree por node, um filtro <code>readyToRun</code>, <code>Promise.all</code> sobre o lote')],
    [{'t':('The blocking wait','A espera bloqueante')},
     ('<code>back/src/app-api/flux/flux.service.ts</code>','<code>back/src/app-api/flux/flux.service.ts</code>'),
     {'t':('<code>await handle.result()</code> per node','<code>await handle.result()</code> por node'),'pill':'no'},
     ('Removed — this is the task that pays back the round trip in analysis §9.2.2','Removida — esta é a task que paga de volta a ida e volta da análise §9.2.2')],
   ]),
 ],
 PROSE1=('One more thing that already works and must keep working: <code>markCompleted</code> and <code>markDead</code> are <strong>set-based and already tolerate out-of-order completion</strong> — which is exactly what a batch produces. No change is needed there, and changing them would be the fastest way to break a scheduler that is currently correct.',
         'Mais uma coisa que já funciona e precisa continuar funcionando: <code>markCompleted</code> e <code>markDead</code> são <strong>baseados em conjunto e já toleram conclusão fora de ordem</strong> — que é exatamente o que um lote produz. Não é preciso mudar nada ali, e mudá-los seria o jeito mais rápido de quebrar um scheduler que hoje está correto.'),
 DECINTRO=('One decision, and it is the one the architecture review added after the fact. The rest of this task is a port with a flag; this part is a ceiling that does not exist yet anywhere in the worker.',
           'Uma decisão, e é a que a revisão de arquitetura acrescentou depois. O resto desta task é um port com flag; esta parte é um teto que ainda não existe em lugar nenhum do worker.'),
 LPARTS=('What the task does, in three parts','O que a task faz, em três partes'),
 PARTS=[
  {'n':'1','title':('The workflow owns <code>SchedulerState</code>','O workflow passa a ser dono do <code>SchedulerState</code>'),
   'loc':('new flow workflow · scheduler.ts from B2', 'novo workflow de fluxo · scheduler.ts da B2'),
   'purpose':('Everything the API&#x27;s loop does with the scheduler, the workflow does — with a batch size of one.',
              'Tudo o que o laço da API faz com o scheduler, o workflow passa a fazer — com lote de tamanho um.'),
   'body':('<p>The workflow owns the state, calls <code>allReady()</code>, dispatches, and applies <code>markCompleted</code> / <code>markDead</code> / <code>completeCondition</code> as results arrive.</p>'
           '<p><code>allReady(state): string[]</code> is added alongside <code>nextReady</code>, draining every eligible id and marking each <code>scheduled</code>. <strong><code>nextReady</code> stays while the backend loop exists</strong> — it is that loop&#x27;s primitive, and <code>C2</code> retires it with the loop. <code>mcp-write.service.ts</code> uses the scheduler too, but only <code>buildSchedulerState</code> and <code>classifyEdge</code>, so it is unaffected either way. Before writing <code>allReady()</code>, check whether the Temporal SDK offers a primitive for ready-set dispatch; decide during development — <code>D16</code> is unchanged whichever way it goes.</p>'
           '<p>The back&#x27;s role shrinks to three things: <strong>start the flow workflow</strong>, <strong>serve the callbacks it already owns</strong> — billing, model access, S3, file generation — and <strong>read the result</strong>. It stops being the loop. One more thing needs a writer once the loop leaves: <code>flow_execution_status</code> (PR #1902, read by <code>GET /flux/executions/:id</code>) — the workflow reports it through a callback, or <code>E1</code>&#x27;s collector writes it; decide and state it in the PR. A flag selects engine-in-back versus engine-in-workflow, <strong>per flow</strong>, defaulting to back.</p>',
           '<p>O workflow é dono do estado, chama <code>allReady()</code>, despacha, e aplica <code>markCompleted</code> / <code>markDead</code> / <code>completeCondition</code> conforme os resultados chegam.</p>'
           '<p><code>allReady(state): string[]</code> é adicionado ao lado do <code>nextReady</code>, drenando todos os ids elegíveis e marcando cada um como <code>scheduled</code>. <strong>O <code>nextReady</code> fica enquanto o laço do backend existir</strong> — é a primitiva desse laço, e a <code>C2</code> o aposenta junto com o laço. O <code>mcp-write.service.ts</code> também usa o scheduler, mas só <code>buildSchedulerState</code> e <code>classifyEdge</code>, então não é afetado de nenhum jeito. Antes de escrever o <code>allReady()</code>, verifique se o SDK do Temporal já oferece uma primitiva para dispatch por conjunto pronto; decida durante o desenvolvimento — a <code>D16</code> não muda em nenhum dos casos.</p>'
           '<p>O papel do back encolhe para três coisas: <strong>iniciar o workflow do fluxo</strong>, <strong>servir os callbacks de que já é dono</strong> — cobrança, acesso a modelo, S3, geração de arquivo — e <strong>ler o resultado</strong>. Ele deixa de ser o laço. Mais uma coisa precisa de um escritor quando o laço sair: o <code>flow_execution_status</code> (PR #1902, lido por <code>GET /flux/executions/:id</code>) — o workflow o reporta por callback, ou o coletor da <code>E1</code> o escreve; decida e declare no PR. Uma flag seleciona motor-no-back contra motor-no-workflow, <strong>por fluxo</strong>, com padrão no back.</p>'),
   'ba':(('The API&#x27;s loop calls <code>nextReady</code>, dispatches one node, and blocks on <code>await handle.result()</code> before asking for the next one.',
          'O laço da API chama <code>nextReady</code>, despacha um node, e bloqueia em <code>await handle.result()</code> antes de pedir o próximo.'),
         ('The workflow calls <code>allReady()</code> and dispatches the batch it returns — configured to one. <strong>Identical order, no blocking round trip through the back.</strong>',
          'O workflow chama <code>allReady()</code> e despacha o lote devolvido — configurado em um. <strong>Ordem idêntica, sem ida e volta bloqueante pelo back.</strong>')),
   'callouts':[('mig',('What stays out','O que fica de fora'),
     ('<p><strong>Batch size above one</strong> — that is B5, in the next wave. <strong>Control flow and sub-flows</strong> — B6. <strong>Deleting the back&#x27;s loop</strong> — C1/C2, after this has soaked. The backend loop stays in place through this whole wave and is only removed in Wave 6.</p>',
      '<p><strong>Lote acima de um</strong> — isso é a B5, na próxima onda. <strong>Controle de fluxo e sub-fluxos</strong> — B6. <strong>Apagar o laço do back</strong> — C1/C2, depois que isto tiver assentado. O laço do backend permanece durante toda esta onda e só é removido na Onda 6.</p>'))]},
  {'n':'2','title':('History is a storage medium, and it is bounded','O histórico é um meio de armazenamento, e ele tem limite'),
   'loc':('review §4.1 — a gap found after the plan was written', 'review §4.1 — uma lacuna encontrada depois de o plano ser escrito'),
   'purpose':('Two requirements, and neither is optional: <code>continueAsNew</code> at a boundary, and state carried <strong>by reference, never by value</strong>.',
              'Dois requisitos, e nenhum é opcional: <code>continueAsNew</code> num limite, e estado carregado <strong>por referência, nunca por valor</strong>.'),
   'body':('<p>A Temporal workflow accumulates history events, and both the event count and the total size are capped. The worker uses <strong>no <code>continueAsNew</code></strong> anywhere today. One workflow owning an entire flow run therefore grows with every activity scheduled and completed and every value passed — and it will be terminated by the platform on exactly the largest, most valuable customer runs.</p>'
           '<p>The second requirement is where the wave&#x27;s tasks meet: the id-based transport from <strong>B1</strong> is what makes by-reference possible. The workflow carries ids; the payloads stay in Postgres and S3. Passing a resolved input through workflow state would put node output into the history — the same failure by another route.</p>',
           '<p>Um workflow do Temporal acumula eventos de histórico, e tanto a contagem de eventos quanto o tamanho total têm teto. O worker não usa <strong>nenhum <code>continueAsNew</code></strong> hoje. Um workflow dono de um run inteiro, portanto, cresce a cada activity agendada e concluída e a cada valor passado — e será terminado pela plataforma justamente nos maiores e mais valiosos runs de cliente.</p>'
           '<p>O segundo requisito é onde as tasks da onda se encontram: o transporte por id da <strong>B1</strong> é o que torna o por-referência possível. O workflow carrega ids; os payloads ficam no Postgres e no S3. Passar uma entrada resolvida pelo estado do workflow colocaria saída de node dentro do histórico — a mesma falha por outro caminho.</p>'),
   'ba':(('No <code>continueAsNew</code> anywhere in the worker. A run&#x27;s history grows with every activity and every value passed, until the platform terminates it — biggest runs first.',
          'Nenhum <code>continueAsNew</code> em lugar nenhum do worker. O histórico de um run cresce a cada activity e a cada valor passado, até a plataforma terminá-lo — os maiores runs primeiro.'),
         ('The workflow continues at a <strong>stated boundary</strong> and carries ids, not payloads. The ceiling is a number someone wrote down and proved by running a graph past it.',
          'O workflow continua num <strong>limite declarado</strong> e carrega ids, não payloads. O teto é um número que alguém escreveu e provou rodando um grafo além dele.'))},
  {'n':'3','title':('A skipped node has to be loud','Um node pulado precisa ser barulhento'),
   'loc':'flux.service.ts · flux/node-cancel-watch.ts',
   'purpose':('The characteristic failure of a scheduler port is a node that is silently never run.',
              'A falha característica de um port de scheduler é um node que simplesmente nunca roda, em silêncio.'),
   'body':('<p>The back warns today when a node ends outside <code>completed</code> or <code>dead</code> (<code>flux.service.ts</code>). The workflow needs the equivalent, because <strong>unprocessed-node detection must survive the move</strong>.</p>'
           '<p>The related property is failing fast. A graph engine whose failure mode is &#x27;hangs for thirty minutes until the Temporal timeout&#x27; is not shippable — the stall has to be detected by the engine, not by the platform. Cancellation must also still work end to end, including the in-flight flag in <code>flux/node-cancel-watch.ts</code>; <strong>E2</strong> is what makes that native rather than ported.</p>',
           '<p>O back avisa hoje quando um node termina fora de <code>completed</code> ou <code>dead</code> (<code>flux.service.ts</code>). O workflow precisa do equivalente, porque <strong>a detecção de node não processado precisa sobreviver à mudança</strong>.</p>'
           '<p>A propriedade irmã é falhar rápido. Um motor de grafo cujo modo de falha é &#x27;trava por trinta minutos até o timeout do Temporal&#x27; não é entregável — a paralisação precisa ser detectada pelo motor, não pela plataforma. O cancelamento também precisa continuar funcionando ponta a ponta, incluindo a flag de in-flight em <code>flux/node-cancel-watch.ts</code>; a <strong>E2</strong> é o que torna isso nativo em vez de portado.</p>'),
   'ba':(('The back warns about a node that ended outside <code>completed</code> or <code>dead</code>. In a workflow-owned run, nobody is watching for it.',
          'O back avisa sobre um node que terminou fora de <code>completed</code> ou <code>dead</code>. Num run conduzido pelo workflow, ninguém está olhando isso.'),
         ('The workflow detects the stall itself and says which node it was, instead of waiting for the Temporal timeout to end the run.',
          'O próprio workflow detecta a paralisação e diz qual node foi, em vez de esperar o timeout do Temporal terminar o run.'))},
 ],
 VERIF=[
  (True,('Negative control','Controle negativo'),
   ('Break <code>markCompleted</code> so a completed node is not recorded, and confirm the workflow <strong>detects the stall</strong> rather than hanging until the Temporal timeout. A graph engine whose failure mode is &#x27;hangs for thirty minutes&#x27; is not shippable — prove it fails fast.',
    'Quebre o <code>markCompleted</code> para que um node concluído não seja registrado, e confirme que o workflow <strong>detecta a paralisação</strong> em vez de travar até o timeout do Temporal. Um motor de grafo cujo modo de falha é &#x27;trava por trinta minutos&#x27; não é entregável — prove que ele falha rápido.')),
  (False,('Order equivalence — the wave&#x27;s exit gate','Equivalência de ordem — o portão de saída da onda'),
   ('For a corpus of stored flows, assert the workflow executes nodes in the <strong>same order the back&#x27;s loop does, node for node</strong>. With batch size one this must be <em>exact</em>: any divergence is a defect in the port, and this is the last moment it is cheap to see.',
    'Para um corpus de fluxos guardados, afirme que o workflow executa os nodes na <strong>mesma ordem do laço do back, node a node</strong>. Com lote de tamanho um isso precisa ser <em>exato</em>: qualquer divergência é defeito de port, e este é o último momento em que é barato enxergar.')),
  (False,('Unprocessed-node detection survives','A detecção de node não processado sobrevive'),
   ('The back warns today when a node ends outside <code>completed</code> or <code>dead</code> (<code>flux.service.ts</code>). The workflow needs the equivalent — <strong>a silently skipped node is the characteristic failure of a scheduler port</strong>.',
    'O back avisa hoje quando um node termina fora de <code>completed</code> ou <code>dead</code> (<code>flux.service.ts</code>). O workflow precisa do equivalente — <strong>um node pulado em silêncio é a falha característica de um port de scheduler</strong>.')),
  (False,('Cancellation still works end to end','O cancelamento continua funcionando ponta a ponta'),
   ('Including the in-flight flag in <code>flux/node-cancel-watch.ts</code>. <strong>E2</strong> converges this on Temporal&#x27;s native mechanism; B4 must not break it in the meantime.',
    'Incluindo a flag de in-flight em <code>flux/node-cancel-watch.ts</code>. A <strong>E2</strong> converge isso para o mecanismo nativo do Temporal; a B4 não pode quebrá-lo no meio do caminho.')),
  (False,('History growth, measured','Crescimento do histórico, medido'),
   ('Run the <strong>widest</strong> and the <strong>longest</strong> real flow available and record the event count and history size at completion, against the platform&#x27;s limits. Then run one <strong>past</strong> the <code>continueAsNew</code> boundary and confirm it continues rather than being terminated. <strong>A graph engine whose ceiling is unknown has no ceiling.</strong>',
    'Rode o fluxo real mais <strong>largo</strong> e o mais <strong>longo</strong> disponíveis e registre a contagem de eventos e o tamanho do histórico ao concluir, contra os limites da plataforma. Depois rode um <strong>além</strong> do limite do <code>continueAsNew</code> e confirme que ele continua em vez de ser terminado. <strong>Um motor de grafo cujo teto é desconhecido não tem teto.</strong>')),
 ],
 DONE=('A flow runs start to finish under the workflow, <strong>in identical order</strong>, behind a flag <strong>defaulting off</strong>; the back&#x27;s loop is untouched and still selectable.',
       'Um fluxo roda do início ao fim sob o workflow, <strong>em ordem idêntica</strong>, atrás de uma flag <strong>desligada por padrão</strong>; o laço do back fica intocado e ainda selecionável.'),
 FILES=[('worker/src/modules/temporal/workflows/process-agent.workflow.ts',False),
        ('worker/src/modules/temporal/{activities,worker.service.ts,workflows/configs.ts}',False),
        ('back/src/app-api/flux/flux.service.ts (await handle.result() in processNodeViaTemporal · the while (scheduledId !== null) loop · the unprocessed-node warning)',False),
        ('the scheduler module from B2 (allReady)',False),
        ('new flow workflow',True)],
)

B4_DEC = {
 'k':'decision','id':'B4-a','status':'open','open':True,
 'q':('Where does <code>continueAsNew</code> cut the run, and at what number?',
      'Onde o <code>continueAsNew</code> corta o run, e em que número?'),
 'intro':('<strong>Review action #7, added to B4 after the plan was written.</strong> A Temporal workflow accumulates history events, and both the event count and the total size are capped. '
          'The worker uses <strong>no <code>continueAsNew</code></strong> anywhere today, so one workflow owning an entire flow run grows with every activity scheduled and completed and every value passed — '
          'and it will be terminated by the platform on <strong>exactly the largest, most valuable customer runs</strong> (review §4.1). '
          'The spec makes two things non-optional: a boundary, and state by reference. The <em>boundary</em> is the open part — <strong>iteration count or node count. Pick one, state the number, and prove it by running a graph past it.</strong>',
          '<strong>Ação #7 da revisão, acrescentada à B4 depois que o plano foi escrito.</strong> Um workflow do Temporal acumula eventos de histórico, e tanto a contagem de eventos quanto o tamanho total têm teto. '
          'O worker não usa <strong>nenhum <code>continueAsNew</code></strong> hoje, então um workflow dono de um run inteiro cresce a cada activity agendada e concluída e a cada valor passado — '
          'e será terminado pela plataforma <strong>justamente nos maiores e mais valiosos runs de cliente</strong> (review §4.1). '
          'A spec torna duas coisas não opcionais: um limite, e estado por referência. O <em>limite</em> é a parte em aberto — <strong>contagem de iterações ou contagem de nodes. Escolha uma, declare o número, e prove rodando um grafo além dele.</strong>'),
 'opts':[
  {'ltr':'A','pick':True,'name':('Node-execution count','Contagem de execuções de node'),
   'tag':('recommended','recomendada'),
   'how':('The workflow counts node executions and calls <code>continueAsNew</code> at a stated number, carrying the scheduler state forward by reference.',
          'O workflow conta execuções de node e chama <code>continueAsNew</code> num número declarado, levando o estado do scheduler adiante por referência.'),
   'pros':[('It counts the thing that actually produces history — <strong>every node execution is activities scheduled and completed</strong>','Conta o que de fato produz histórico — <strong>cada execução de node significa activities agendadas e concluídas</strong>'),
           ('It fires on <strong>every graph shape</strong>, including a wide graph that never loops','Dispara em <strong>toda forma de grafo</strong>, inclusive num grafo largo que nunca faz laço'),
           ('It shares its unit with <strong>S4&#x27;s per-run budget</strong>, so the two numbers can be read against each other instead of drifting apart','Compartilha a unidade com o <strong>orçamento por run da S4</strong>, então os dois números podem ser lidos um contra o outro em vez de divergirem')],
   'cons':[('A single execution that passes a very large value still grows history faster than the count suggests — size is the other cap','Uma única execução que passa um valor muito grande ainda cresce o histórico mais rápido que a contagem sugere — tamanho é o outro teto'),
           ('The number has to be re-derived if the average activity count per node changes','O número precisa ser recalculado se a média de activities por node mudar')],
   'cost':[('lo',('Client effort: <b>none — a continued run is still one run</b>','Esforço do cliente: <b>nenhum — um run continuado ainda é um run</b>')),
           ('',('Ours: <b>one counter, plus the boundary test</b>','Nosso: <b>um contador, mais o teste de limite</b>'))]},
  {'ltr':'B','name':('Loop-iteration count','Contagem de iterações de laço'),
   'how':('The workflow continues as new after a stated number of loop iterations — the shape that most obviously grows without bound.',
          'O workflow continua como novo depois de um número declarado de iterações de laço — a forma que mais obviamente cresce sem limite.'),
   'pros':[('Aims directly at the known growth case: a long loop, or an <code>arrayNode</code> over a big list','Mira direto no caso de crescimento conhecido: um laço longo, ou um <code>arrayNode</code> sobre uma lista grande'),
           ('Easy to explain to whoever is debugging a run that continued','Fácil de explicar para quem estiver depurando um run que continuou')],
   'cons':[('A <strong>wide graph with no loop at all</strong> can still exhaust history — the boundary simply never fires','Um <strong>grafo largo sem laço nenhum</strong> ainda pode esgotar o histórico — o limite simplesmente nunca dispara'),
           ('It measures a proxy rather than what accumulates, so the ceiling is only as good as the correlation','Mede um proxy em vez do que acumula, então o teto só vale o quanto a correlação valer')],
   'cost':[('lo',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('hi',('Ours: <b>a boundary that misses wide graphs</b>','Nosso: <b>um limite que não pega grafos largos</b>'))]},
  {'ltr':'C','no':True,'name':('No <code>continueAsNew</code> — lean on S4&#x27;s ceiling','Sem <code>continueAsNew</code> — apoiar-se no teto da S4'),
   'tag':('not viable','inviável'),
   'how':('<strong>S4</strong> already bounds node executions per run, and that bounds history growth. Let that ceiling be the only limit.',
          'A <strong>S4</strong> já limita execuções de node por run, e isso limita o crescimento do histórico. Deixar esse teto ser o único limite.'),
   'pros':[('Nothing new to build in B4, and one number instead of two to keep consistent','Nada novo a construir na B4, e um número em vez de dois para manter consistentes')],
   'cons':[('S4&#x27;s ceiling is deliberately set <strong>above the largest real run</strong> — so the largest real runs are exactly the ones it does not stop','O teto da S4 é deliberadamente colocado <strong>acima do maior run real</strong> — então os maiores runs reais são justamente os que ele não para'),
           ('S4&#x27;s own spec calls itself <em>&#x27;the other half of what B4&#x27;s <code>continueAsNew</code> is for&#x27;</em> — a complement, not a replacement','A própria spec da S4 se chama de <em>&#x27;a outra metade do que o <code>continueAsNew</code> da B4 faz&#x27;</em> — um complemento, não um substituto'),
           ('The residual failure is <strong>platform termination of a customer&#x27;s biggest run</strong>, which is not a failure we get to explain away','A falha residual é <strong>a plataforma terminar o maior run de um cliente</strong>, que não é uma falha que dá para explicar')],
   'cost':[('lo',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('hi',('Ours: <b>the largest customer runs stay terminable</b>','Nosso: <b>os maiores runs de cliente seguem termináveis</b>'))]},
 ],
 'rec':('<p><strong>A — node-execution count — with the number derived from the measurement the task already owes.</strong> Run the widest and the longest real flow available, record the event count and the history size at completion against the platform&#x27;s limits, then set the boundary <em>below</em> that with margin and run a graph past it. State the number in the PR; a ceiling nobody wrote down is not a ceiling.</p>'
        '<p>B is not wrong so much as partial: it aims at loops, and loops are only one of the two shapes that exhaust history. If loop iterations turn out to dominate in the real measurement, A still catches them — the reverse is not true.</p>'
        '<p>Whichever boundary wins, the second requirement is not negotiable: <strong>state by reference, never by value</strong>. The workflow carries the ids <strong>B1</strong> settles, and the payloads stay in Postgres and S3. Passing a resolved input through workflow state puts node output into the history and reintroduces the same failure from the other side.</p>',
        '<p><strong>A — contagem de execuções de node — com o número derivado da medição que a task já deve.</strong> Rode o fluxo real mais largo e o mais longo, registre a contagem de eventos e o tamanho do histórico ao concluir contra os limites da plataforma, e então coloque o limite <em>abaixo</em> disso com margem e rode um grafo além dele. Declare o número no PR; um teto que ninguém escreveu não é um teto.</p>'
        '<p>B não é tanto errada quanto parcial: mira em laços, e laços são só uma das duas formas que esgotam o histórico. Se as iterações de laço dominarem na medição real, A ainda as pega — o contrário não vale.</p>'
        '<p>Vencendo qualquer limite, o segundo requisito não é negociável: <strong>estado por referência, nunca por valor</strong>. O workflow carrega os ids que a <strong>B1</strong> resolve, e os payloads ficam no Postgres e no S3. Passar uma entrada resolvida pelo estado do workflow coloca saída de node no histórico e reintroduz a mesma falha pelo outro lado.</p>'),
 'who':[('Engineering','Engenharia'),('Infra states the platform limits','Infra declara os limites da plataforma')],
}
