# -*- coding: utf-8 -*-

E1 = dict(
 TITLE=('Run observability when the worker owns the loop','Observabilidade de run quando o worker é dono do laço'),
 GOAL=('Keep the <b>nested run timeline</b>, the <b>per-node billing attribution</b> and the <b>secret redaction</b> working once the loop is not in the backend&#x27;s process.',
       'Manter a <b>linha do tempo aninhada do run</b>, a <b>atribuição de cobrança por node</b> e a <b>redação de segredos</b> funcionando depois que o laço sai do processo do backend.'),
 GLANCE=[
  ('crit',('Risk','Risco'),('A run nobody can debug','Um run que ninguém consegue depurar'),
   ('Risk R9 — the timeline, the billing attribution and <code>redactSecrets</code> all live in the backend process and have no owner in a worker-orchestrated run. Analysis §11.3.',
    'Risco R9 — a linha do tempo, a atribuição de cobrança e o <code>redactSecrets</code> vivem todos no processo do backend e não têm dono num run orquestrado pelo worker. Análise §11.3.')),
  ('dep',('Depends on','Depende de'),('B2','B2'),
   ('<strong>Must land with B4</strong>, not after it.',
    '<strong>Precisa entrar junto com a B4</strong>, não depois dela.')),
  ('wave',('Wave','Onda'),('Wave 4','Onda 4'),
   ('The moment the loop leaves the process, three subsystems lose their host at once.',
    'No instante em que o laço sai do processo, três subsistemas perdem o hospedeiro de uma vez.')),
  ('ship',('Ship order','Ordem de entrega'),('With B4, not after','Com a B4, não depois'),
   ('<strong>A B4 that ships without E1 ships a run nobody can debug</strong> (PLAN §5).',
    '<strong>Uma B4 que sai sem a E1 entrega um run que ninguém consegue depurar</strong> (PLAN §5).')),
 ],
 LEDE=('<p><code>RunLogCollector</code> is an in-memory <strong>tree</strong> living in the backend process for the length of a run: <code>startNode</code> / <code>endNode</code> per node, <code>innerSteps</code> for sub-steps, <code>subRun</code> plus <code>startLoopBody</code> and <code>startLibrarySubRun</code> for nested runs, debounced into <code>space_run_logs</code> and finalised with a synchronous <code>flushNow</code>. The product surface built on it — the nested run timeline — depends on the <strong>hierarchy</strong>, not just on the events.</p>'
       '<p>Two more things ride on it. <code>redactSecrets</code> is <strong>the only</strong> place credentials are scrubbed before reaching a log — leaking into <code>space_run_logs</code> is a <strong>security event</strong>. And <code>chargeContext</code>, the AsyncLocalStorage the backend uses to attribute token spend to the current node, is <strong>single-process by construction</strong>. None of this survives the loop moving, and none of it belongs to any node&#x27;s task.</p>',
       '<p>O <code>RunLogCollector</code> é uma <strong>árvore</strong> em memória que vive no processo do backend pela duração de um run: <code>startNode</code> / <code>endNode</code> por node, <code>innerSteps</code> para sub-passos, <code>subRun</code> mais <code>startLoopBody</code> e <code>startLibrarySubRun</code> para runs aninhados, com debounce para <code>space_run_logs</code> e finalização por um <code>flushNow</code> síncrono. A superfície de produto construída sobre ele — a linha do tempo aninhada — depende da <strong>hierarquia</strong>, não só dos eventos.</p>'
       '<p>Mais duas coisas pegam carona. O <code>redactSecrets</code> é <strong>o único</strong> lugar onde credenciais são limpas antes de chegar a um log — vazar para <code>space_run_logs</code> é um <strong>evento de segurança</strong>. E o <code>chargeContext</code>, o AsyncLocalStorage que o backend usa para atribuir gasto de tokens ao node atual, é <strong>mono-processo por construção</strong>. Nada disso sobrevive à mudança do laço, e nada disso pertence à task de nenhum node.</p>'),
 L1=('What loses its host when the loop moves','O que perde o hospedeiro quando o laço se muda'),
 TABLES=[
  dict(head=[('What','O quê'),('What it does today','O que faz hoje'),('Survives the move?','Sobrevive à mudança?'),('Where it lands','Onde vai parar')],
   rows=[
    [{'t':'RunLogCollector','mono':True},
     ('One hierarchical tree in memory for the length of the run, debounced into <code>space_run_logs</code> and finalised by <code>flushNow</code>',
      'Uma árvore hierárquica em memória pela duração do run, com debounce para <code>space_run_logs</code> e finalizada pelo <code>flushNow</code>'),
     {'t':('Not as a tree','Não como árvore'),'pill':'no'},
     ('The backend <strong>rebuilds the tree from events the worker emits</strong> — decided, not open (review §4.3)',
      'O backend <strong>reconstrói a árvore a partir de eventos emitidos pelo worker</strong> — decidido, não em aberto (review §4.3)')],
    [{'t':'redactSecrets','mono':True},
     ('The only place credentials are scrubbed before reaching a log',
      'O único lugar onde credenciais são limpas antes de chegar a um log'),
     {'t':('Only if kept deliberately','Só se mantido de propósito'),'pill':'weak'},
     ('Preserved explicitly, <strong>with a test</strong> — leaking into <code>space_run_logs</code> is a security event',
      'Preservado explicitamente, <strong>com teste</strong> — vazar para <code>space_run_logs</code> é evento de segurança')],
    [{'t':'chargeContext (ALS)','mono':True},
     ('Attributes token spend to the current node inside one process',
      'Atribui gasto de tokens ao node atual dentro de um processo'),
     {'t':('Single-process by construction','Mono-processo por construção'),'pill':'no'},
     ('Explicit <code>execId</code>/<code>nodeId</code> over HTTP — <strong>the worker&#x27;s pattern, adopted by the backend</strong>',
      '<code>execId</code>/<code>nodeId</code> explícitos via HTTP — <strong>o padrão do worker, adotado pelo backend</strong>')],
    [{'t':('Snapshot subtraction','Subtração de snapshot')},
     ('Computes a node&#x27;s spend by subtracting an accumulator before and after',
      'Calcula o gasto de um node subtraindo um acumulador antes e depois'),
     {'t':('Breaks under parallel siblings','Quebra com irmãos em paralelo'),'pill':'no'},
     ('Dedup by primary key in <code>token_transactions</code>, <strong>settled before B5, not after</strong>',
      'Dedup por chave primária em <code>token_transactions</code>, <strong>resolvido antes da B5, não depois</strong>')],
   ]),
 ],
 PROSE1=('This is why E1 is a <strong>subsystem, not a detail</strong>, and why it ships in the same wave as the move rather than in a follow-up. Wave 4&#x27;s promise is that <em>nothing gets faster and nothing changes for a user</em> — a run whose timeline stopped nesting, or whose billing shifted, would break that promise while looking like a success.',
         'É por isso que a E1 é um <strong>subsistema, não um detalhe</strong>, e por isso entra na mesma onda que a mudança em vez de num follow-up. A promessa da Onda 4 é que <em>nada fica mais rápido e nada muda para o usuário</em> — um run cuja linha do tempo parou de aninhar, ou cuja cobrança mudou, quebraria essa promessa parecendo um sucesso.'),
 DECINTRO=None,
 LPARTS=('What the task does, in three parts','O que a task faz, em três partes'),
 PARTS=[
  {'n':'1','title':('Event-sourced, not a tree inside the workflow','Baseada em eventos, não uma árvore dentro do workflow'),
   'loc':('review §4.3 · analysis §11.3', 'review §4.3 · análise §11.3'),
   'purpose':('The model is <strong>decided, not open</strong>: the backend rebuilds the tree from events the worker emits.',
              'O modelo está <strong>decidido, não em aberto</strong>: o backend reconstrói a árvore a partir dos eventos que o worker emite.'),
   'body':('<p>An earlier draft of this task offered <em>&#x27;worker keeps the tree&#x27;</em> as an equivalent option. It is not. Keeping the tree inside the workflow makes <strong>workflow state grow with the run</strong>, which collides directly with the history limits <strong>B4</strong> now has to respect. Event-sourced reconstruction is the only shape compatible with both parallelism and bounded history — and it is <strong>already how the Temporal path behaves</strong>, emitting status through Redis and writing <code>execution_logs</code>.</p>'
           '<p>What remains to design is the <strong>event contract</strong>: enough to rebuild <code>innerSteps</code> and <code>subRun</code> ordering without replaying the tree itself. That is the whole engineering content of this part — not which model, but what an event has to carry for the hierarchy to be reconstructible from it.</p>',
           '<p>Um rascunho anterior desta task oferecia <em>&#x27;o worker guarda a árvore&#x27;</em> como opção equivalente. Não é. Manter a árvore dentro do workflow faz o <strong>estado do workflow crescer com o run</strong>, o que colide diretamente com os limites de histórico que a <strong>B4</strong> agora precisa respeitar. A reconstrução baseada em eventos é a única forma compatível com paralelismo <em>e</em> histórico limitado — e é <strong>como o caminho Temporal já se comporta</strong>, emitindo status pelo Redis e escrevendo <code>execution_logs</code>.</p>'
           '<p>O que resta projetar é o <strong>contrato de evento</strong>: o suficiente para reconstruir a ordenação de <code>innerSteps</code> e <code>subRun</code> sem reproduzir a árvore em si. Esse é todo o conteúdo de engenharia desta parte — não qual modelo, mas o que um evento precisa carregar para a hierarquia ser reconstruível a partir dele.</p>'),
   'ba':(('One in-memory tree in the backend process, written by the loop that owns the run. Nesting is implicit in who called whom.',
          'Uma árvore em memória no processo do backend, escrita pelo laço dono do run. O aninhamento é implícito em quem chamou quem.'),
         ('The worker emits events and the backend reconstructs the hierarchy from them. <strong>Nothing about the run lives in workflow state.</strong>',
          'O worker emite eventos e o backend reconstrói a hierarquia a partir deles. <strong>Nada sobre o run vive no estado do workflow.</strong>')),
   'callouts':[('decide',('Decision to write down — the event contract','Decisão a registrar — o contrato de evento'),
     ('<p>The model is settled; the contract is not. It has to carry enough to rebuild <code>innerSteps</code> and <code>subRun</code> ordering — <strong>and not the tree, and not less</strong>. Write it down before the first emitter is coded, because every emitter added afterwards makes it harder to change.</p>',
      '<p>O modelo está decidido; o contrato não. Ele precisa carregar o suficiente para reconstruir a ordenação de <code>innerSteps</code> e <code>subRun</code> — <strong>e não a árvore, e não menos</strong>. Registre-o antes de codar o primeiro emissor, porque cada emissor adicionado depois torna a mudança mais difícil.</p>'))]},
  {'n':'2','title':('Charge accounting converges on the worker&#x27;s pattern','A contabilidade de cobrança converge para o padrão do worker'),
   'loc':'token_transaction/ · back/src/temporal/worker.controller.ts',
   'purpose':('Explicit <code>execId</code>/<code>nodeId</code> over HTTP is the <strong>better</strong> design; the backend adopts it rather than the worker replicating AsyncLocalStorage.',
              '<code>execId</code>/<code>nodeId</code> explícitos via HTTP são o design <strong>melhor</strong>; o backend o adota em vez de o worker replicar AsyncLocalStorage.'),
   'body':('<p>The step documentation argues it and this epic accepts it: when <code>onUpdateTokens</code> and <code>chargeContext</code> disappear, <strong>that is progress, not loss</strong>. An implicit per-process context is replaced by two explicit ids on the wire, which is also the only version of this that works when the caller is a different process.</p>'
           '<p>The harder half is arithmetic. Under parallelism the before/after snapshot subtraction that computes a node&#x27;s spend <strong>stops working</strong> — two siblings both move the accumulator, and each attributes the other&#x27;s spend to itself. Billing must <strong>dedup by primary key in <code>token_transactions</code></strong> instead. This has to be settled <strong>before B5</strong>, not after: B5 is the wave where two siblings actually run at once.</p>',
           '<p>A documentação do passo defende e este épico aceita: quando <code>onUpdateTokens</code> e <code>chargeContext</code> desaparecerem, <strong>isso é progresso, não perda</strong>. Um contexto implícito por processo é substituído por dois ids explícitos no fio, que é também a única versão disto que funciona quando quem chama é outro processo.</p>'
           '<p>A metade mais difícil é aritmética. Sob paralelismo, a subtração de snapshot antes/depois que calcula o gasto de um node <strong>para de funcionar</strong> — dois irmãos movem o acumulador, e cada um atribui a si o gasto do outro. A cobrança precisa <strong>deduplicar por chave primária em <code>token_transactions</code></strong>. Isto precisa estar resolvido <strong>antes da B5</strong>, não depois: a B5 é a onda em que dois irmãos de fato rodam ao mesmo tempo.</p>'),
   'ba':(('A node&#x27;s spend is the difference between two readings of a shared accumulator, inside one process, with one node running at a time.',
          'O gasto de um node é a diferença entre duas leituras de um acumulador compartilhado, dentro de um processo, com um node rodando por vez.'),
         ('Each charge is a row attributed by <code>execId</code>/<code>nodeId</code> and deduplicated by primary key. <strong>Two siblings charging at once produce the same total as one after the other.</strong>',
          'Cada cobrança é uma linha atribuída por <code>execId</code>/<code>nodeId</code> e deduplicada por chave primária. <strong>Dois irmãos cobrando ao mesmo tempo produzem o mesmo total que um depois do outro.</strong>'))},
  {'n':'3','title':('Redaction is a security control, not a formatting step','Redação é controle de segurança, não passo de formatação'),
   'loc':('back/src/app-api/space_run_logs/ · the RunLogCollector implementation', 'back/src/app-api/space_run_logs/ · a implementação do RunLogCollector'),
   'purpose':('<code>redactSecrets</code> is the only place credentials are scrubbed before reaching a log, so the refactor must keep the hook — deliberately, with a test.',
              'O <code>redactSecrets</code> é o único lugar onde credenciais são limpas antes de chegar a um log, então o refactor precisa manter o gancho — de propósito, com teste.'),
   'body':('<p>A hook that exists on one write path and is forgotten on the new one does not fail loudly: the logs keep being written, and they simply contain more than they should. That is why this gets its own test rather than a line in a checklist — <strong>a leak into <code>space_run_logs</code> is a security event, not a bug</strong>.</p>'
           '<p>Out of scope: redesigning the timeline UX or the <code>space_run_logs</code> schema. The JSONB there may need partitioning eventually; that is a separate concern and this task does not open it.</p>',
           '<p>Um gancho que existe num caminho de escrita e é esquecido no novo não falha alto: os logs continuam sendo escritos, e simplesmente contêm mais do que deveriam. Por isso isto ganha teste próprio em vez de uma linha num checklist — <strong>um vazamento para <code>space_run_logs</code> é evento de segurança, não bug</strong>.</p>'
           '<p>Fora de escopo: redesenhar a UX da linha do tempo ou o schema de <code>space_run_logs</code>. O JSONB de lá pode precisar de particionamento algum dia; isso é outro assunto e esta task não o abre.</p>'),
   'ba':(('The hook sits on the backend&#x27;s write path, which every log line takes today because every log line is written there.',
          'O gancho fica no caminho de escrita do backend, que toda linha de log percorre hoje porque toda linha de log é escrita ali.'),
         ('The hook sits on the path the worker&#x27;s events take, and <strong>a test fails if a credential reaches <code>space_run_logs</code></strong>.',
          'O gancho fica no caminho que os eventos do worker percorrem, e <strong>um teste falha se uma credencial chegar a <code>space_run_logs</code></strong>.'))},
 ],
 VERIF=[
  (True,('Negative control','Controle negativo'),
   ('Remove the nesting so loop iterations are emitted as <strong>siblings of the loop</strong> rather than children, and confirm a test fails on the <strong>tree shape</strong>. This is not hypothetical: the same source records it as the classic bug in this code — using <code>runLogCollector</code> where <code>loopRunLogCollector</code> was meant. Reproduce it deliberately, then guard it.',
    'Remova o aninhamento para que as iterações do laço sejam emitidas como <strong>irmãs do laço</strong> em vez de filhas, e confirme que um teste falha na <strong>forma da árvore</strong>. Isto não é hipotético: a mesma fonte registra isso como o bug clássico deste código — usar <code>runLogCollector</code> onde se queria <code>loopRunLogCollector</code>. Reproduza de propósito, e então proteja.')),
  (False,('Redaction','Redação'),
   ('Feed a credential through a node and assert it <strong>does not appear</strong> in <code>space_run_logs</code>. Then break <code>redactSecrets</code> and <strong>watch the test go red</strong>.',
    'Passe uma credencial por um node e afirme que ela <strong>não aparece</strong> em <code>space_run_logs</code>. Depois quebre o <code>redactSecrets</code> e <strong>veja o teste ficar vermelho</strong>.')),
  (False,('Billing parity under concurrency','Paridade de cobrança sob concorrência'),
   ('Run a flow with <strong>two parallel siblings that both charge</strong>, and assert the total matches the sequential run <strong>exactly</strong>. Subtraction-based accounting fails here — <strong>that failure is the point of the test</strong>.',
    'Rode um fluxo com <strong>dois irmãos em paralelo que ambos cobram</strong>, e afirme que o total bate <strong>exatamente</strong> com o do run sequencial. A contabilidade por subtração falha aqui — <strong>essa falha é o objetivo do teste</strong>.')),
  (False,('Timeline equivalence','Equivalência da linha do tempo'),
   ('A nested <code>fluxBox</code> run renders <strong>the same tree</strong> before and after. The hierarchy is the product surface — matching events with a flattened shape is not a pass.',
    'Um run aninhado de <code>fluxBox</code> renderiza <strong>a mesma árvore</strong> antes e depois. A hierarquia é a superfície de produto — bater os eventos com a forma achatada não é aprovação.')),
 ],
 DONE=('The timeline is <strong>identical for nested runs</strong>, secrets are still redacted, billing matches under concurrency, and <strong>no run-scoped state depends on AsyncLocalStorage</strong>.',
       'A linha do tempo é <strong>idêntica para runs aninhados</strong>, segredos continuam redigidos, a cobrança bate sob concorrência, e <strong>nenhum estado de escopo de run depende de AsyncLocalStorage</strong>.'),
 FILES=[('back/src/app-api/space_run_logs/',False),
        ('the RunLogCollector implementation',False),
        ('back/src/app-api/flux/flux.service.ts:2290–2293, 3281–3316, 4537–4562, 4824–4862',False),
        ('back/src/app-api/token_transaction/',False),
        ('back/src/temporal/worker.controller.ts',False),
        ('the worker flow workflow',True),
        ('the run-event contract',True)],
)

E2 = dict(
 TITLE=('Align cancellation with Temporal','Alinhar cancelamento com o Temporal'),
 GOAL=('Cancelling a run works when the loop is in the worker — by <b>using what Temporal already provides</b>, not by reimplementing the current design somewhere else.',
       'Cancelar um run funciona com o laço no worker — <b>usando o que o Temporal já oferece</b>, não reimplementando o desenho atual em outro lugar.'),
 GLANCE=[
  ('crit',('Risk','Risco'),('Cancellation stops propagating','O cancelamento para de propagar'),
   ('The regression this task exists to prevent: a cancel that does not stop the next node from starting — and it is invisible without a test.',
    'A regressão que esta task existe para evitar: um cancelamento que não impede o próximo node de começar — e ela é invisível sem teste.')),
  ('dep',('Depends on','Depende de'),('B4','B4'),
   ('The loop has to be in the worker before its cancellation can be Temporal-native. Analysis §11.4.',
    'O laço precisa estar no worker antes de o cancelamento poder ser nativo do Temporal. Análise §11.4.')),
  ('wave',('Wave','Onda'),('Wave 4','Onda 4'),
   ('Same wave as the move, because the move is what breaks the current mechanism.',
    'Mesma onda que a mudança, porque é a mudança que quebra o mecanismo atual.')),
  ('ship',('Shape','Formato'),('Delete, not port','Apagar, não portar'),
   ('The per-node poller and <code>nodeCancelContext</code> are removed — sixty nodes stop meaning sixty timers.',
    'O poller por node e o <code>nodeCancelContext</code> são removidos — sessenta nodes deixam de significar sessenta timers.')),
 ],
 LEDE=('<p>The current mechanism <strong>cannot move as-is</strong>: <code>nodeCancelContext</code> is AsyncLocalStorage, so it is blind the moment the handler runs in another process. The rest of it — a Postgres status column, a WebSocket signal, a poll — is portable, but it is not what you would build on Temporal.</p>'
       '<p>Temporal already has this. <code>WorkflowHandle.cancel()</code> on the backend side and <code>Context.current().cancelled</code> on the worker side give cooperative cancellation with <strong>none of the polling</strong>. There is also a cost to carrying the current design forward: it runs <strong>one <code>setInterval</code> per node</strong>, so a sixty-node agent holds sixty timers hitting the database.</p>',
       '<p>O mecanismo atual <strong>não pode se mudar como está</strong>: o <code>nodeCancelContext</code> é AsyncLocalStorage, então fica cego no instante em que o handler roda em outro processo. O resto dele — uma coluna de status no Postgres, um sinal por WebSocket, um poll — é portável, mas não é o que se construiria sobre o Temporal.</p>'
       '<p>O Temporal já tem isso. <code>WorkflowHandle.cancel()</code> do lado do backend e <code>Context.current().cancelled</code> do lado do worker dão cancelamento cooperativo <strong>sem nenhum polling</strong>. E há um custo em levar o desenho atual adiante: ele roda <strong>um <code>setInterval</code> por node</strong>, então um agente de sessenta nodes segura sessenta timers batendo no banco.</p>'),
 L1=('The current mechanism, piece by piece','O mecanismo atual, peça por peça'),
 TABLES=[
  dict(head=[('Piece','Peça'),('What it does today','O que faz hoje'),('Moves to the worker?','Vai para o worker?'),('Temporal&#x27;s answer','A resposta do Temporal')],
   rows=[
    [{'t':'nodeCancelContext','mono':True},
     ('AsyncLocalStorage carrying the cancel state for the current node','AsyncLocalStorage carregando o estado de cancelamento do node atual'),
     {'t':('No — blind across processes','Não — cego entre processos'),'pill':'no'},
     ('Deleted. Cancellation is a workflow property, not a per-process context.','Apagado. Cancelamento é propriedade do workflow, não contexto por processo.')],
    [{'t':('Status column in Postgres','Coluna de status no Postgres')},
     ('Records that the run was cancelled','Registra que o run foi cancelado'),
     {'t':('Portable','Portável'),'pill':'ok'},
     ('Kept — the cancel footprint is a product surface, and <code>finishCancelledNode</code> must still mark state correctly','Mantida — a pegada do cancelamento é superfície de produto, e o <code>finishCancelledNode</code> precisa continuar marcando o estado corretamente')],
    [{'t':('WebSocket signal','Sinal por WebSocket')},
     ('Tells the running process that a cancel was requested','Avisa o processo em execução que um cancelamento foi pedido'),
     {'t':('Portable, but redundant','Portável, mas redundante'),'pill':'weak'},
     ('<code>WorkflowHandle.cancel()</code> reaches the workflow directly','O <code>WorkflowHandle.cancel()</code> chega ao workflow diretamente')],
    [{'t':('Per-node poller (setInterval)','Poller por node (setInterval)')},
     ('One timer per node, polling the database for the cancel state','Um timer por node, consultando o banco pelo estado de cancelamento'),
     {'t':('Would multiply','Multiplicaria'),'pill':'no'},
     ('<code>Context.current().cancelled</code> — cooperative, no polling at all','<code>Context.current().cancelled</code> — cooperativo, sem polling nenhum')],
    [{'t':'NODE_CANCEL_IN_FLIGHT_FLAG','mono':True},
     ('A feature flag added after the original design','Uma feature flag adicionada depois do desenho original'),
     {'t':('Unproven at scale','Não provada em escala'),'pill':'weak'},
     ('Validate its current state <strong>before</strong> relying on it','Validar o estado atual dela <strong>antes</strong> de depender dela')],
   ]),
 ],
 PROSE1=('So the migration gets cancellation <strong>almost for free</strong>, and the work is to converge on it rather than to rebuild it. What is <em>not</em> free is the part Temporal does not do: writing the product&#x27;s state. Temporal cancels a workflow; it does not record which node the run was on when the user clicked.',
         'Ou seja: a migração ganha o cancelamento <strong>quase de graça</strong>, e o trabalho é convergir para ele em vez de reconstruí-lo. O que <em>não</em> é de graça é a parte que o Temporal não faz: escrever o estado do produto. O Temporal cancela um workflow; ele não registra em qual node o run estava quando o usuário clicou.'),
 DECINTRO=('One decision. It is the default any team reaches for when a mechanism has to keep working somewhere else — <em>port it</em> — and the spec answers it in its own title. The page records the two facts that make the answer stick.',
           'Uma decisão. É o reflexo de qualquer time quando um mecanismo precisa continuar funcionando em outro lugar — <em>portar</em> — e a spec responde isso no próprio título. A página registra os dois fatos que sustentam a resposta.'),
 LPARTS=('What the task does, in five parts','O que a task faz, em cinco partes'),
 PARTS=[
  {'n':'1','title':('Cancel becomes a workflow call','Cancelar vira uma chamada de workflow'),
   'loc':'back/src/temporal/temporal.service.ts · flux/node-cancel-watch.ts',
   'purpose':('The backend asks Temporal to cancel; the worker cooperates. Nothing polls.',
              'O backend pede ao Temporal para cancelar; o worker coopera. Nada faz polling.'),
   'body':('<p>The backend calls <code>handle.cancel()</code> when a cancel is requested, and the worker respects <code>Context.current().cancelled</code>. The per-node poller is retired along with <code>nodeCancelContext</code>.</p>'
           '<p>The child-workflow case is the one that proves the design rather than merely implementing it: cancelling a run that is inside a <code>fluxBox</code> or a <code>libraryNode</code> has to stop the child too, and <strong>cancellation propagation is native for child workflows</strong>. That is a cheap test and a strong signal — the hand-built alternative would need that propagation written and maintained.</p>',
           '<p>O backend chama <code>handle.cancel()</code> quando um cancelamento é pedido, e o worker respeita o <code>Context.current().cancelled</code>. O poller por node é aposentado junto com o <code>nodeCancelContext</code>.</p>'
           '<p>O caso de child workflow é o que prova o desenho, e não apenas o implementa: cancelar um run que está dentro de um <code>fluxBox</code> ou de um <code>libraryNode</code> precisa parar o filho também, e <strong>a propagação de cancelamento é nativa para child workflows</strong>. É um teste barato e um sinal forte — a alternativa feita à mão precisaria escrever e manter essa propagação.</p>'),
   'ba':(('A cancel writes a status column, emits a WebSocket signal, and each node&#x27;s own <code>setInterval</code> polls the database for it — a sixty-node agent holding sixty timers.',
          'Um cancelamento escreve uma coluna de status, emite um sinal por WebSocket, e o <code>setInterval</code> de cada node consulta o banco por ele — um agente de sessenta nodes segurando sessenta timers.'),
         ('The backend calls <code>handle.cancel()</code> and the worker checks <code>Context.current().cancelled</code>. <strong>The poller and <code>nodeCancelContext</code> are deleted</strong>, and child workflows stop for free.',
          'O backend chama <code>handle.cancel()</code> e o worker checa <code>Context.current().cancelled</code>. <strong>O poller e o <code>nodeCancelContext</code> são apagados</strong>, e os child workflows param de graça.')),
   'callouts':[('mig',('Out of scope','Fora de escopo'),
     ('<p>Changing what cancellation <em>means</em> to the user, or cancelling side effects that already committed. <strong>A cancelled push that already reached Stripe stays sent.</strong></p>',
      '<p>Mudar o que cancelamento <em>significa</em> para o usuário, ou cancelar efeitos colaterais já efetivados. <strong>Um push cancelado que já chegou ao Stripe continua enviado.</strong></p>'))]},
  {'n':'2','title':('What the product keeps','O que o produto mantém'),
   'loc':'flux.service.ts:3192–3194, 4516–4530',
   'purpose':('Temporal cancels a workflow; it does not write the product&#x27;s state. That part stays ours.',
              'O Temporal cancela um workflow; ele não escreve o estado do produto. Essa parte continua sendo nossa.'),
   'body':('<p>Two things survive the convergence unchanged. The <strong>cancel footprint</strong> — which node the run was on when it was cancelled — is shown to the user and stays. And <code>finishCancelledNode</code> must still mark state correctly, <strong>so a cancelled run does not look stalled</strong>: a run that was cancelled and a run that hung look identical from the outside unless someone writes the difference down.</p>'
           '<p>The feature flag needs its own check before any of this leans on it. <code>NODE_CANCEL_IN_FLIGHT_FLAG</code> was added after the original design and <strong>is not proven at production scale</strong> — validate its current state rather than assuming it is on and working.</p>',
           '<p>Duas coisas sobrevivem inalteradas à convergência. A <strong>pegada do cancelamento</strong> — em qual node o run estava quando foi cancelado — é mostrada ao usuário e fica. E o <code>finishCancelledNode</code> precisa continuar marcando o estado corretamente, <strong>para que um run cancelado não pareça travado</strong>: um run cancelado e um run que travou parecem idênticos de fora, a menos que alguém escreva a diferença.</p>'
           '<p>A feature flag precisa da própria checagem antes de qualquer coisa se apoiar nela. O <code>NODE_CANCEL_IN_FLIGHT_FLAG</code> foi adicionado depois do desenho original e <strong>não está provado em escala de produção</strong> — valide o estado atual dele em vez de supor que está ligado e funcionando.</p>'),
   'ba':(('The footprint and the cancelled state are written by the backend loop that owned the run and observed the cancel.',
          'A pegada e o estado cancelado são escritos pelo laço do backend que era dono do run e observou o cancelamento.'),
         ('The same footprint and the same terminal state are written from the worker-owned run — <strong>the UX is unchanged, which is the point</strong>.',
          'A mesma pegada e o mesmo estado terminal são escritos a partir do run conduzido pelo worker — <strong>a UX não muda, e esse é o objetivo</strong>.'))},
  {'n':'3','title':('What the ledger records when a generation is cancelled','O que o extrato registra quando uma geração é cancelada'),
   'loc':('D22','D22'),
   'purpose':('Make a cancelled generation legible in the ledger instead of silently free.',
              'Tornar uma geração cancelada legível no extrato em vez de silenciosamente gratuita.'),
   'body':('<p>We ask the provider to cancel, and what we can record depends on what it answers.</p>'
           '<p><strong>If it reports the tokens spent up to that point</strong>, record the charge <em>normally</em> — exactly as a generation that completed. '
           'The work was really done and really cost. <strong>If it reports nothing</strong>, record what is available and mark the entry as cancelled or aborted '
           'by the user.</p>',
           '<p>Pedimos ao provider que cancele, e o que conseguimos registrar depende do que ele responde.</p>'
           '<p><strong>Se ele informa os tokens gastos até ali</strong>, registre a cobrança <em>normalmente</em> — exatamente como uma geração que terminou. '
           'O trabalho foi mesmo feito e mesmo custou. <strong>Se ele não informa nada</strong>, registre o que estiver disponível e marque o lançamento como '
           'cancelado ou abortado pelo usuário.</p>'),
   'callouts':[('warn',('Never record zero','Nunca registrar zero'),
     ('<p>Zero for a cancelled generation that consumed tokens is the case that makes the ledger disagree with the provider&#x27;s invoice — '
      '<strong>and it disagrees silently</strong>, which is why it is worth a rule rather than a habit.</p>',
      '<p>Zero para uma geração cancelada que consumiu tokens é o caso que faz o extrato divergir da fatura do provider — '
      '<strong>e diverge em silêncio</strong>, e é por isso que merece uma regra e não um hábito.</p>'))]},

  {'n':'4','title':('Cancellation reaches the children','O cancelamento alcança os filhos'),
   'loc':('D23 · D20','D23 · D20'),
   'purpose':('Stop a container node instead of letting it finish, because what it would finish is unbounded.',
              'Parar um node contêiner em vez de deixá-lo terminar, porque o que ele terminaria é ilimitado.'),
   'body':('<p><code>D20</code> lets an in-flight node finish, because a generation is short, already paid for, and yields a result. '
           '<strong>A <code>fluxBox</code>, <code>libraryNode</code> or <code>arrayNode</code> is not that:</strong> its execution is an open-ended amount of '
           'further work, which is exactly what is being refused.</p>'
           '<p>So a container node is <strong>cancelled</strong>, and the cancellation propagates down the chain — native for Temporal child workflows, and what '
           'the <code>parentRunId</code> chain from <code>S1</code> exists to carry. For <code>arrayNode</code>, the element already generating finishes; '
           '<strong>the remaining elements never start</strong>.</p>',
           '<p>A <code>D20</code> deixa um node em voo terminar, porque uma geração é curta, já foi paga e entrega um resultado. '
           '<strong>Um <code>fluxBox</code>, <code>libraryNode</code> ou <code>arrayNode</code> não é isso:</strong> a execução dele é uma quantidade aberta de '
           'trabalho futuro, que é exatamente o que se quer recusar.</p>'
           '<p>Então um node contêiner é <strong>cancelado</strong>, e o cancelamento propaga pela cadeia — nativo em child workflow do Temporal, e é para isso '
           'que a cadeia <code>parentRunId</code> da <code>S1</code> existe. No <code>arrayNode</code>, o elemento que já está gerando termina; '
           '<strong>os elementos restantes nunca começam</strong>.</p>'),
   'callouts':[('mig',('<code>nodesBox</code> is not in this list','<code>nodesBox</code> não entra nesta lista'),
     ('<p>Checked against <code>back@origin/production</code>: <code>nodesBox</code> dispatches to <code>objectCaller</code>, whose body contains no <code>apiV2</code> and no node execution of any kind — it reads and writes an object&#x27;s session state. Cancelling it prevents no spend and leaves the object half-written, so under <code>D20</code> it finishes. Its hazard is concurrent writes once <code>B5</code> parallelises, which is <code>A7</code>&#x27;s ordering contract.</p>',
      '<p>Verificado contra o <code>back@origin/production</code>: o <code>nodesBox</code> despacha para o <code>objectCaller</code>, cujo corpo não tem <code>apiV2</code> nem execução de node nenhuma — ele lê e escreve o estado de sessão de um objeto. Cancelá-lo não impede gasto nenhum e deixa o objeto pela metade, então pela <code>D20</code> ele termina. O risco dele é escrita concorrente quando o <code>B5</code> paralelizar, que é o contrato de ordenação da <code>A7</code>.</p>'))]},

  {'n':'5','title':('State the latency, do not assume it','Declarar a latência, não presumir'),
   'loc':('a 1500 ms cache over a 2000 ms poll', 'um cache de 1500 ms sobre um poll de 2000 ms'),
   'purpose':('Today up to <strong>3.5 s</strong> can pass between the click and the effective cancel. Native cancellation should improve that — <em>should</em> is not a contract.',
              'Hoje podem passar até <strong>3,5 s</strong> entre o clique e o cancelamento efetivo. O cancelamento nativo deveria melhorar isso — <em>deveria</em> não é contrato.'),
   'body':('<p>The 3.5 s is arithmetic, not measurement: a 1500 ms cache sitting over a 2000 ms poll. Replacing the poll with cooperative cancellation removes both terms, but the number that matters is the one measured on a real run, before and after.</p>'
           '<p>The other measurement is the timers. Run a <strong>sixty-node agent</strong> and count active timers and the database query rate against the pre-change baseline — the claim that the poller is a performance offender in its own right is either demonstrable or it is not worth making.</p>',
           '<p>Os 3,5 s são aritmética, não medição: um cache de 1500 ms sobre um poll de 2000 ms. Trocar o poll por cancelamento cooperativo elimina os dois termos, mas o número que importa é o medido num run real, antes e depois.</p>'
           '<p>A outra medição são os timers. Rode um <strong>agente de sessenta nodes</strong> e conte timers ativos e a taxa de consultas ao banco contra a linha de base anterior — a afirmação de que o poller é, por si só, um problema de performance ou é demonstrável ou não vale a pena ser feita.</p>'),
   'ba':(('Up to 3.5 s, derived from the cache and poll intervals. Nobody has measured the real click-to-effective-cancel time.',
          'Até 3,5 s, derivados dos intervalos de cache e de poll. Ninguém mediu o tempo real entre o clique e o cancelamento efetivo.'),
         ('A measured click-to-effective-cancel number, before and after, stated in the PR — along with the timer count for a sixty-node agent.',
          'Um número medido de clique até cancelamento efetivo, antes e depois, declarado no PR — junto com a contagem de timers de um agente de sessenta nodes.')),
   'callouts':[('decide',('Decision to write down — the latency contract','Decisão a registrar — o contrato de latência'),
     ('<p>&#x27;Should improve&#x27; is not a contract; a number is. Decide what click-to-effective-cancel the product promises, then measure against it — <strong>and if the measured number is worse than 3.5 s anywhere, that is a finding, not a rounding error</strong>.</p>',
      '<p>&#x27;Deveria melhorar&#x27; não é contrato; um número é. Decida qual tempo de clique até cancelamento efetivo o produto promete, e então meça contra ele — <strong>e se o número medido for pior que 3,5 s em algum lugar, isso é um achado, não erro de arredondamento</strong>.</p>'))]},
 ],
 VERIF=[
  (True,('Negative control','Controle negativo'),
   ('Cancel a run mid-node and assert <strong>the next node never starts</strong>. Then break the propagation and watch it start anyway — <strong>that is the regression this task exists to prevent, and it is invisible without the test</strong>.',
    'Cancele um run no meio de um node e afirme que <strong>o próximo node nunca começa</strong>. Depois quebre a propagação e veja-o começar assim mesmo — <strong>essa é a regressão que esta task existe para evitar, e ela é invisível sem o teste</strong>.')),
  (False,('Cancel during a child workflow','Cancelar durante um child workflow'),
   ('With a <code>fluxBox</code> or <code>libraryNode</code> running, cancel the parent: <strong>the child must stop too</strong>. Cancellation propagation is native for child workflows, so this test is cheap — and it is what <strong>proves the design choice</strong> rather than the implementation.',
    'Com um <code>fluxBox</code> ou <code>libraryNode</code> rodando, cancele o pai: <strong>o filho precisa parar também</strong>. A propagação de cancelamento é nativa para child workflows, então este teste é barato — e é o que <strong>prova a escolha de desenho</strong>, não a implementação.')),
  (False,('Measure click-to-effective-cancel','Medir clique até cancelamento efetivo'),
   ('Before and after. Today a <strong>1500 ms cache over a 2000 ms poll</strong> can leave up to <strong>3.5 s</strong>; native cancellation should improve that — <strong>state the number rather than assuming</strong>.',
    'Antes e depois. Hoje um <strong>cache de 1500 ms sobre um poll de 2000 ms</strong> pode deixar até <strong>3,5 s</strong>; o cancelamento nativo deveria melhorar isso — <strong>declare o número em vez de supor</strong>.')),
  (False,('The per-node timers are gone','Os timers por node sumiram'),
   ('Run a <strong>sixty-node agent</strong> and count active timers and the database query rate against the pre-change baseline. One <code>setInterval</code> per node is the cost this task removes; if the count does not drop, it was not removed.',
    'Rode um <strong>agente de sessenta nodes</strong> e conte timers ativos e a taxa de consultas ao banco contra a linha de base anterior. Um <code>setInterval</code> por node é o custo que esta task remove; se a contagem não cair, ele não foi removido.')),
 ],
 DONE=('Cancellation is <strong>Temporal-native end to end</strong>, including child workflows; the poller and the ALS context are <strong>removed</strong>; the footprint UX is unchanged; and the latency is <strong>measured</strong>.',
       'O cancelamento é <strong>nativo do Temporal ponta a ponta</strong>, inclusive em child workflows; o poller e o contexto ALS estão <strong>removidos</strong>; a UX da pegada não muda; e a latência está <strong>medida</strong>.'),
 FILES=[('back/src/app-api/flux/node-cancel-watch.ts',False),
        ('back/src/app-api/flux/flux.service.ts:3192–3194, 4516–4530',False),
        ('back/src/temporal/temporal.service.ts',False),
        ('the worker flow workflow and its activities',False),
        ('NODE_CANCEL_IN_FLIGHT_FLAG (validate, then retire)',False)],
)

E2_DEC = {
 'k':'decision','id':'E2-a','status':'rec','open':True,
 'q':('Do we port the cancellation mechanism into the worker, or converge on Temporal&#x27;s?',
      'Portamos o mecanismo de cancelamento para o worker, ou convergimos para o do Temporal?'),
 'intro':('The spec answers this in its own title, and it is recorded here because <em>port it</em> is the default any team reaches for when a mechanism has to keep working somewhere else. '
          'Two facts decide it. <strong><code>nodeCancelContext</code> is AsyncLocalStorage</strong> and cannot cross a process boundary at all, so &#x27;identical semantics&#x27; is not actually on offer. '
          'And the portable remainder runs <strong>one <code>setInterval</code> per node</strong> — a sixty-node agent holds sixty timers hitting the database. Behind a flag that is tolerable; on by default and unoptimised it becomes a performance offender in its own right.',
          'A spec responde isso no próprio título, e fica registrado aqui porque <em>portar</em> é o reflexo de qualquer time quando um mecanismo precisa continuar funcionando em outro lugar. '
          'Dois fatos decidem. <strong>O <code>nodeCancelContext</code> é AsyncLocalStorage</strong> e não atravessa fronteira de processo de forma alguma, então &#x27;semântica idêntica&#x27; não está de fato em oferta. '
          'E o restante portável roda <strong>um <code>setInterval</code> por node</strong> — um agente de sessenta nodes segura sessenta timers batendo no banco. Atrás de uma flag isso é tolerável; ligado por padrão e sem otimização vira um problema de performance por si só.'),
 'opts':[
  {'ltr':'A','pick':True,'name':('Temporal-native cancellation','Cancelamento nativo do Temporal'),
   'tag':('recommended','recomendada'),
   'how':('The backend calls <code>handle.cancel()</code>; the worker respects <code>Context.current().cancelled</code>. The per-node poller and <code>nodeCancelContext</code> are retired.',
          'O backend chama <code>handle.cancel()</code>; o worker respeita o <code>Context.current().cancelled</code>. O poller por node e o <code>nodeCancelContext</code> são aposentados.'),
   'pros':[('The mechanism <strong>already exists on both sides</strong> — the migration gets cancellation almost for free','O mecanismo <strong>já existe dos dois lados</strong> — a migração ganha o cancelamento quase de graça'),
           ('Propagation into child workflows (<code>fluxBox</code> / <code>libraryNode</code>) is <strong>native</strong>, so B6&#x27;s sub-flows inherit it','A propagação para child workflows (<code>fluxBox</code> / <code>libraryNode</code>) é <strong>nativa</strong>, então os sub-fluxos da B6 a herdam'),
           ('Sixty timers and their database queries disappear from a sixty-node agent','Sessenta timers e suas consultas ao banco desaparecem de um agente de sessenta nodes'),
           ('Latency should improve — today a 1500 ms cache over a 2000 ms poll can leave up to <strong>3.5 s</strong>','A latência deve melhorar — hoje um cache de 1500 ms sobre um poll de 2000 ms pode deixar até <strong>3,5 s</strong>')],
   'cons':[('The cancel footprint and <code>finishCancelledNode</code> still have to be wired by hand — <strong>Temporal cancels a workflow, it does not write the product&#x27;s state</strong>','A pegada do cancelamento e o <code>finishCancelledNode</code> ainda precisam ser ligados à mão — <strong>o Temporal cancela um workflow, ele não escreve o estado do produto</strong>'),
           ('Cooperative cancellation only stops what checks it: an activity in the middle of a provider call finishes that call','Cancelamento cooperativo só para o que o consulta: uma activity no meio de uma chamada a provedor termina aquela chamada')],
   'cost':[('lo',('Client effort: <b>none — the cancel button is unchanged</b>','Esforço do cliente: <b>nenhum — o botão de cancelar não muda</b>')),
           ('lo',('Ours: <b>we delete more than we add</b>','Nosso: <b>apagamos mais do que escrevemos</b>'))]},
  {'ltr':'B','name':('Port the portable remainder','Portar o restante portável'),
   'how':('Keep the status column, the signal and the poll, and re-implement the per-node watch inside the worker — replacing the ALS context with something that crosses processes.',
          'Manter a coluna de status, o sinal e o poll, e reimplementar a vigília por node dentro do worker — trocando o contexto ALS por algo que atravesse processos.'),
   'pros':[('The semantics stay literally identical, so nothing about the footprint UX has to be re-reasoned','A semântica fica literalmente idêntica, então nada da UX da pegada precisa ser repensado'),
           ('No dependence on Temporal cancellation semantics the team has not exercised yet','Sem dependência de semânticas de cancelamento do Temporal que o time ainda não exercitou')],
   'cons':[('It carries <strong>one <code>setInterval</code> per node</strong> into a fleet that is about to have more replicas','Leva <strong>um <code>setInterval</code> por node</strong> para uma frota que está prestes a ter mais réplicas'),
           ('The ALS context has no cross-process equivalent, so it has to be rebuilt anyway — <strong>&#x27;identical&#x27; is not on offer</strong>','O contexto ALS não tem equivalente entre processos, então precisa ser reconstruído de qualquer jeito — <strong>&#x27;idêntico&#x27; não está em oferta</strong>'),
           ('Child-workflow propagation would have to be written and maintained, when Temporal gives it','A propagação para child workflows teria de ser escrita e mantida, quando o Temporal já a dá')],
   'cost':[('lo',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('hi',('Ours: <b>sixty timers per agent, plus hand-written propagation</b>','Nosso: <b>sessenta timers por agente, mais propagação escrita à mão</b>'))]},
  {'ltr':'C','no':True,'name':('Carry <code>nodeCancelContext</code> as it is','Levar o <code>nodeCancelContext</code> como está'),
   'tag':('not viable','inviável'),
   'how':('Keep the AsyncLocalStorage context and let the worker read it.',
          'Manter o contexto AsyncLocalStorage e deixar o worker lê-lo.'),
   'pros':[('No work','Nenhum trabalho')],
   'cons':[('AsyncLocalStorage <strong>does not cross a process boundary</strong> — the context is simply empty in the worker','AsyncLocalStorage <strong>não atravessa fronteira de processo</strong> — o contexto simplesmente fica vazio no worker'),
           ('The failure is silent: the cancel appears to succeed and the next node starts anyway','A falha é silenciosa: o cancelamento parece ter funcionado e o próximo node começa assim mesmo')],
   'cost':[('lo',('Client effort: <b>none</b>','Esforço do cliente: <b>nenhum</b>')),
           ('hi',('Ours: <b>a cancel that silently does nothing</b>','Nosso: <b>um cancelamento que silenciosamente não faz nada</b>'))]},
 ],
 'rec':('<p><strong>A.</strong> It is the spec&#x27;s answer and the two supporting facts are not close: the ALS context cannot move at all, and the portable remainder is a per-node timer we would be carrying into a bigger fleet. The child-workflow test is the cheap proof — propagation is native there, and B is the option that would have to build it.</p>'
        '<p>Two things must not be lost in the convergence. The <strong>cancel footprint</strong> — which node the run was on when it was cancelled — stays a product surface. And <code>finishCancelledNode</code> must still mark state correctly, <strong>so a cancelled run does not look stalled</strong>.</p>'
        '<p>Before any of this leans on it, <strong>validate the current state of <code>NODE_CANCEL_IN_FLIGHT_FLAG</code></strong>: it was added after the original design and is not proven at production scale. A flag assumed on is a flag nobody tested.</p>',
        '<p><strong>A.</strong> É a resposta da spec, e os dois fatos que a sustentam não são disputáveis: o contexto ALS não se move, e o restante portável é um timer por node que estaríamos levando para uma frota maior. O teste de child workflow é a prova barata — a propagação é nativa ali, e a B é a opção que teria de construí-la.</p>'
        '<p>Duas coisas não podem se perder na convergência. A <strong>pegada do cancelamento</strong> — em qual node o run estava quando foi cancelado — continua sendo superfície de produto. E o <code>finishCancelledNode</code> precisa continuar marcando o estado corretamente, <strong>para que um run cancelado não pareça travado</strong>.</p>'
        '<p>Antes de qualquer coisa se apoiar nela, <strong>valide o estado atual do <code>NODE_CANCEL_IN_FLIGHT_FLAG</code></strong>: ele foi adicionado depois do desenho original e não está provado em escala de produção. Uma flag presumida ligada é uma flag que ninguém testou.</p>'),
 'who':[('Engineering','Engenharia'),('Product keeps the footprint UX','Produto mantém a UX da pegada')],
}
